### ISSUE TITLE
Please link repo description to Mozilla page and replace .github/issues.template

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/redash#1]
This repository was cloned from an upstream third-party, keeping in place the default repo description and issue template.

Please replace the description with a description that references Mozilla's fork of this project, and the issue template:

"Make Your Company Data Driven. Connect to any data source, easily visualize and share your data. http://redash.io/"

And replace the GitHub issue template as shown below:

--

Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by rafrombrc** [comment]
I've updated the repo description and have (for now) deleted the issue template. Thanks.
