### ISSUE TITLE
Remove AthenaDirect data source?

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#104]
Once data source types have been updated on all Athena connections in staging and production, do we remove the AthenaDirect connection type from the Mozilla fork?

**Comment by alison985** [comment]
Depends on #103, so I think it will actually be M8.

**Comment by alison985** [comment]
@robotblake The staging and production Athena datasource is using the upstream PyAthena query runner now. Am I good to remove the other 2 versions of the Athena query runner?

**Comment by alison985** [comment]
Answer was yes on Wednesday call.

**Comment by alison985** [comment]
PR #192

**Comment by madalincm** [comment]
The athena direct data source is no longer displayed in the selector when creating a new query. @alison985 
 Other than that is there any other way to very this?
