### ISSUE TITLE
Resolve inconsistencies in date dash handling

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#11]
re:dash can return different search results for date searches depending on what type of dashes are used in the dates, see https://bugzilla.mozilla.org/show_bug.cgi?id=1311487. We should look into how dashes are being handled, determine if there's a better way, and provide best practices on how to do date searches in s.t.m.o.

**Comment by washort** [comment]
This was not redash-related, see my comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1311487#c4 .
