### ISSUE TITLE
M6 in staging doesn't show query editor

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#111]
This is what I'm getting in staging right now after the M6 deploy.
![Screenshot 2017-07-11 23.11.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416703e7855e37923cbb279f1172843434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c061983fe593ca99148c951f44ae54857b65e.png)

**Comment by alison985** [comment]
Did PR #112 and cut tag m6.01.

**Comment by alison985** [comment]
Changes the error message, but does not resolve. Links to this Angular documentation page: https://docs.angularjs.org/error/$injector/unpr?p0=eProvider%20%3C-%20e
![Screenshot 2017-07-12 00.26.30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416703e7856e37b20cbb17ef1112b43434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c071e83fe593ca99148ce5cf742e14953b65e.png)

**Comment by alison985** [comment]
Fixed PR #114.

**Comment by madalincm** [comment]
Issue no longer reproducing in stage. Marking as verified fixed.
