### ISSUE TITLE
Queries against Redash metadata are failing

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#116]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open the new query page and select Redash metadata as data source.
3. Enter a simple query like "select * from events limit 20" and click the execute button

### Expected results:
The query is run, results are displayed.

### Actual results:
The query can't be executed, the following error is displayed: "Error running query: (psycopg2.ProgrammingError) column "data_scanned" of relation "query_results" does not exist LINE 1: ..., query_hash, query, data, runtime, retrieved_at, data_scann... ^ "

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage
Screenshot for this issue:
![redashmetadataerror](https://user-images.githubusercontent.com/15685441/28125204-96970cec-672e-11e7-8fe3-cd2024611725.png)

**Comment by alison985** [comment]
@robotblake There is a migration to run. Please let me know what you need from me to run it.

**Comment by alison985** [comment]
This is working for me on staging now.

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in STMO-stage
Postfix screencast:
![116postfix](https://user-images.githubusercontent.com/15685441/28167412-47a8eaa4-67e4-11e7-8c02-6ec54b7f081a.png)
