### ISSUE TITLE
Error/warning message displayed in new query page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#117]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open the new query page and select Athena (direct) as data source.

### Expected results:
There are no layout or display issues.

### Actual results:
A warning/error message is displayed next to the data source "AthenaDirect' object has no attribute 'data_source_version_query'"

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage
Screenshot for this issue:
![antenadirectwarningmessage](https://user-images.githubusercontent.com/15685441/28125420-3ad46048-672f-11e7-8df3-a950cb40efec.png)

**Comment by alison985** [comment]
PR #118

**Comment by madalincm** [comment]
Verified as fixed in FF54(win7) in STMO-stage
Postfix screencast:
![117postfix](https://user-images.githubusercontent.com/15685441/28166788-f9a87ad8-67e1-11e7-917c-d304342c2409.png)
