### ISSUE TITLE
query returns 500 but remains in queue

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#12]
There are cases where a server is returning a 500 response for a query but re:dash is continuing to display the query as in process in the queue, see https://bugzilla.mozilla.org/show_bug.cgi?id=1313219. It would be great to reproduce and resolve this so 500 responses show up as query failure.

**Comment by arikfr** [comment]
Are you running version 0.12 in production? Because this was addressed here: https://github.com/getredash/redash/pull/1121/files

**Comment by rafrombrc** [comment]
@arikfr Awesome, thanks for the tip! We'll be updating our deployed code soon.
