### ISSUE TITLE
Error displayed when running a query in data_source table

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#121]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open the new query page and select redash metadata as data source.
3. Execute the following query: "select * from data_sources"

### Expected results:
The query is run, results are displayed.

### Actual results:
The query can't be executed, the following error is displayed: Error running query: permission denied for relation data_sources 

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage and STMO-prod
Screenshot for this issue:
![data_sourceerror](https://user-images.githubusercontent.com/15685441/28167297-cba609b4-67e3-11e7-8e02-97d16b5fa12e.png)

**Comment by alison985** [comment]
@robotblake Could you please confirm that this is a security feature, not a bug? I think the permission denial is happening at the postgres database level, is that correct?

**Comment by robotblake** [comment]
That is correct, we only allow access to several columns in that table. If you replace the `SELECT *` with `SELECT id, name, type` the query works just fine.
