### ISSUE TITLE
Mobile dashboards showing up empty

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#138]
@osunick sent me a link to the following embedded graph:

https://sql.telemetry.mozilla.org/embed/query/845/visualization/1439?api_key=eb9e12449cac3888d3c2467bad46664816118c5a

When I visited it, I could see the title, but the graph itself was completely blank. I hit browser refresh several times, no change. I then clicked on the chain link icon near the bottom right to visit the query. Once on the query I clicked on the refresh icon on the page to rerun the query. After that, the original page started working correctly, the graph started showing up.

We need to figure out how the graph got into the weird state in the first place, and how we might be able to prevent this from happening.

**Comment by alison985** [comment]
Looks like null data got pulled from the Google Spreadsheet source and then saved. https://sql.telemetry.mozilla.org/queries/5904/source @osunick was the spreadsheet not working or being edited on 7/18-7/19-ish?

**Comment by rafrombrc** [comment]
We haven't gotten a reply on this one, but I also haven't heard any further reports of these dashboards not working. I'm closing this one for now, we can reopen if it starts happening again.
