### ISSUE TITLE
Alerts detail page can't be opened

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#139]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/alerts
2. Click on any alert.

### Expected results:
The alert detail page is displayed, details can be edited.

### Actual results:
The alert detail page can't be opened.

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage
Screenshot for this issue:
![alertsdetailpage](https://user-images.githubusercontent.com/15685441/28418819-d4241cca-6d65-11e7-895c-0d0ceb608485.gif)

**Comment by alison985** [comment]
Code from this came from upstream. I have it working locally. @rafrombrc Can I contribute it upstream as well?

**Comment by rafrombrc** [comment]
Yes, definitely, I'm always +1 to fixes landing upstream.

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in stmo-stage
Postfix screencast:
![alertseditfix](https://user-images.githubusercontent.com/15685441/28463940-abc53ca2-6e2b-11e7-9f03-ead37e5d7bb1.gif)

Marking as verified fixed.
