### ISSUE TITLE
Investigate exponential back-off for heavy queries

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#14]
We're having issues with heavy queries failing, then immediately being added to the end of the queue, only to fail again, continuing to suck up resources. We might want to consider allowing exponential back off on the retry, or some other strategy to help prevent heavy queries from consuming more resources than necessary.

**Comment by arikfr** [comment]
Relevant: https://github.com/getredash/redash/issues/613.

**Comment by washort** [comment]
https://github.com/getredash/redash/pull/1584
