### ISSUE TITLE
Queries can't be run against tables that contains "-"

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#140]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open new Query page and select ActiveData as a data source: https://pipeline-sql.stage.mozaws.net/queries/new
2. Execute the following query: "select * from overage-summary.source.file.covered limit 20"

### Expected results:
The query is executed, results are displayed.

### Actual results:
The following error is displayed: Error running query: Expected end of text (at char 22), (line:1, col:23)

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced in STMO-stage
Screenshot for this issue:
![query-](https://user-images.githubusercontent.com/15685441/28419413-8889f026-6d67-11e7-8c3b-785cb8fa991b.png)

**Comment by alison985** [comment]
The query works if you quote the table. i.e. select * from "coverage-summary" limit 10. I think this is a SQL/query dialect thing with ActiveData and that it's okay to go to production. @klahnakoski do you agree?

**Comment by klahnakoski** [comment]
@madalincm good parsing errors is hard, and the one shown is not too bad. The [moz-sql-parser](https://github.com/mozilla/moz-sql-parser) is used to parse the queries and return an error.

 @alison985 the query_runner is still good; it is correctly reporting the error it gets back from ActiveData.

**Comment by klahnakoski** [comment]
For clarity, this is not a problem with the query_runner, rather the ActiveData service endpoint:

    curl http://activedata.allizom.org/sql -d "{\"sql\": \"select * from overage-summary.source.file.covered limit 20\"}"

**Comment by klahnakoski** [comment]
see https://github.com/mozilla/moz-sql-parser/issues/1

**Comment by alison985** [comment]
I'm going to remove the bug label from this and move it to Milestone 7 since it's a nice to have but not required for release.

**Comment by klahnakoski** [comment]
This issue should be closed.  There is nothing the query_runner, or the redash code, can do to improve the error message.

**Comment by madalincm** [comment]
Due to the discussion above I will mark this bug as wontfix.
