### ISSUE TITLE
Recent Queries section is empty in production

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#143]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage: https://sql.telemetry.mozilla.org/
2. Observe the Recent Queries section.

### Expected results:
A list of recent queries is displayed.

### Actual results:
The recent queries section is empty

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO production
Screenshot for this issue:
![recentqueries](https://user-images.githubusercontent.com/15685441/28465691-57d00120-6e32-11e7-9ef0-434b5d9cb387.png)

**Comment by alison985** [comment]
This is what I currently see in production: 
<img width="1276" alt="screenshot 2017-07-21 12 22 02" src="https://user-images.githubusercontent.com/1840865/28474216-58297324-6e0d-11e7-8704-cb94494006c5.png">

**Comment by alison985** [comment]
@madalincm I looked at the code and it's filtered by user id. If you haven't actually run a query in production recently I would expect the list to be blank.

**Comment by madalincm** [comment]
I'm not sure that is the way that list is working. Now I have a full list of queries in that list:
![querieslist](https://user-images.githubusercontent.com/15685441/28521347-e24aa562-707b-11e7-921a-7f3e03ba8fa1.png)

I haven't run any queries in production since i was reproducing the empty list issue.

**Comment by alison985** [comment]
Interesting. I checked for alerts or a schedule on the top query listed in your screenshot in production and didn't find anything but also the code on production hasn't changed yet to M6 yet.

**Comment by rafrombrc** [comment]
I'm not seeing this issue, and we've had no further reports of the 'recent queries' list being empty. Closing this unless and until we see the problem again.
