### ISSUE TITLE
Error displayed when executing queries against telemetry.main_summary in production

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#144]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO new query page: https://sql.telemetry.mozilla.org/queries/new
2. Execute the following query: "select * from telemetry.main_summary limit 20"

### Expected results:
The query is executed, results are displayed.

### Actual results:
The following error is displayed: "Error running query: getArray"

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO production
Screenshot for this issue:
![main summaryerror](https://user-images.githubusercontent.com/15685441/28468496-cc8f172c-6e3b-11e7-90c0-12e13ad9b674.png)

**Comment by alison985** [comment]
This query is running in production for me on Athena now that M6 is in prod.

**Comment by madalincm** [comment]
Issue is no longer reproducing in production. Marking as verified fixed.
