### ISSUE TITLE
Feature: Which data sources are being used where?

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#146]
Give M6's data_scanned feature for Athena affecting other data sources, it occurs to me that we could use an administrative page to list which data sources have a) saved queries published, b) saved queries unpublished, c) queries on dashboards, d) queries with alerts.

This at a glance could tell us which data sources are being used, how much they are being used, and where they are being used.

@arikfr thoughts?

**Comment by arikfr** [comment]
As a simple prototype for this you can create a query in Redash that queries the metadata and gives these answers.

**Comment by alison985** [comment]
Prototype:
```
select ds.name -- , q.id, w.*
  , count(distinct q.id) as total_query_count
  , count(distinct case when is_archived = false and is_draft = false then q.id End) as queries_published_non_archived
  , count(distinct w.id) as widgets_using_data_source
  , count(distinct dashboard_id) as dashboards_using_data_source
  , max(q.updated_at) as latest_query_update
from data_sources as ds 
  left join queries as q on q.data_source_id = ds.id 
    left join visualizations as v on v.query_id = q.id
      left join widgets as w on w.visualization_id = v.id 
group by 1
order by 2 desc
```

or  https://pipeline-sql.stage.mozaws.net/queries/70/source#table

**Comment by alison985** [comment]
After discussion with Rob, I've published this query to staging and prod with the tag of #admin.

**Comment by madalincm** [comment]
The query is published in production and can be found in here: https://sql.telemetry.mozilla.org/queries/18907/source#table But the query can't be executed. I get this error when trying to execute it: "Error running query: line 7:6: Table hive.default.data_sources does not exist"

@alison985 I see that the query has the data source set to Presto.  Shouldn't be re:dash metadata? I've created the same query against re:dash metadata and it is working: https://sql.telemetry.mozilla.org/queries/23013/source
