### ISSUE TITLE
How do I find queries I've archived?

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#150]
1. create a query and save it.
2. Archive the query.
3. Try to find it - not listed on https://pipeline-sql.stage.mozaws.net/queries/my?page=1

Are archived queries supposed to be listed anywhere? It also does not show up from a search in the top navigation bar.

**Comment by jezdez** [comment]
@alison985 Thanks for raising the question in https://github.com/getredash/redash/pull/2573!

**Comment by arikfr** [comment]
We can add "Archived" section along with "Favorites"/"My"/etc. But I wouldn't do it now, as that branch is already very massive, so better to land it first and expand later.

**Comment by alison985** [comment]
Makes complete sense to me @arikfr. Thanks!

**Comment by jezdez** [comment]
@arikfr Awesome thanks!

**Comment by jezdez** [comment]
@alison985 This seems like ready to be worked on again.

**Comment by jezdez** [comment]
Pushed PR in https://github.com/getredash/redash/pull/2888

**Comment by jezdez** [comment]
This was merged upstream. 🎉
