### ISSUE TITLE
Ability to define colors for pie charts

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#153]
From upstream: https://github.com/getredash/redash/issues/1354

Example pie chart query on staging: https://pipeline-sql.stage.mozaws.net/queries/48/source#55

**Comment by madalincm** [comment]
The pie chart is not displayed for the query in comment 1. I tried creating other query with pie charts and they don't show up.  Also when trying to edit the color of the pie chart nothing is displayed. Please view this screenshot:
![piechartcoloredit](https://user-images.githubusercontent.com/15685441/29671753-ff600748-88f2-11e7-97d4-7211acd6699c.png)

**Comment by madalincm** [comment]
Verified in FF55(win7) in stmo stage.
The pie charts are now displayed and the ability to define colors was added. There is an issue when changing colors but I will log a separate issue for it for easier tracking.

**Comment by madalincm** [comment]
Logged #242 as a follow up
