### ISSUE TITLE
Add last_active column to users page

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#155]
From upstream: https://github.com/getredash/redash/issues/789

**Comment by alison985** [comment]
@robotblake This may, in some respects double database writes upon each event in re:Dash. Specifically, when a recordable event call happens it will record the event to re:Dash's meta database and update the user's last_active_at time. Is that something you would have concerns about?

**Comment by rafrombrc** [comment]
Discussed in a meeting... we're not especially concerned about this, the write load is pretty low, let's try it out and see how things look in QA.

**Comment by rafrombrc** [comment]
With the caveat that we'd want some details on what, exactly, causes the last_active to be updated. We wouldn't want to write on every asset fetch, for instance. Is there already a user_id value in the events table, so that we could do a join to fetch this rather than writing to the user table?

**Comment by alison985** [comment]
@rafrombrc - The original concept from Arik was to update the user table. However,  there is a user_id field in the events table that is a much better answer.  Thanks!

**Comment by alison985** [comment]
PR #191

**Comment by madalincm** [comment]
Verified in FF55(Win7) in STMO-stage
Postfix screencast: 
![lastactive](https://user-images.githubusercontent.com/15685441/29655329-68ec84c8-88b9-11e7-888a-23b6c64a5d0b.png)
