### ISSUE TITLE
Auto deactivation of unused / unvisited queries / dashboards?

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#16]
Sometimes queries are scheduled to run repeatedly but they end up getting very little use, so they end up continuing to consume server resources while not providing much value. Issue #15 is one way to help alleviate this, but it might also be useful to have redash itself notice when a scheduled query is unused, sending notifications or possibly even deactivating the unused queries.

**Comment by arikfr** [comment]
I prefer this solution than to complicate the UI with the solution proposed in #15. I suspect that people will ignore the expiration setting anyway.

At EverythingMe, we had a Jenkins job that used the `events` table to find unused scheduled queries and unschedule them. It will be great to have this as a feature in Redash, but till then you can do something similar. Should be quite simple.
