### ISSUE TITLE
Editing a query name publishes that query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#160]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open an unpublished query page.
2. Edit the query name

### Expected results:
The query name is changed, the unpublished tag is still displayed.

### Actual results:
The query name is changed and the query becomes public.

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO production and STMO stage
Screenshot for this issue:
![publisheditname](https://user-images.githubusercontent.com/15685441/28574848-ccc9d320-7157-11e7-96ac-beefae7de4b8.gif)

**Comment by alison985** [comment]
Confirmed on staging (and demo.redash.io FWIW). 

There is a new config flag from upstream `clientConfig.autoPublishNamedQueries` that seems to be the cause. If you add `export FEATURE_AUTO_PUBLISH_NAMED_QUERIES=false` to the config (in my case, the .env file locally) then it behaves as expected.

@robotblake, could you please add this configuration option to our dev, staging, and production instances?

**Comment by robotblake** [comment]
This is now added to the configs but will need a new deploy to pickup the change.
