### ISSUE TITLE
It should be optional to display the variable boxes in template queries in a dashboard

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#163]
First I will describe the use-case here. If I'm generating dashboards via the API, the templating mechanism is useful to me to set variables for a query given the data my redash client has. However, once I've set them and generated a dashboard, I don't want it to be possible for these to be easily changed and I don't want to have those text boxes in the dashboard.

I understand why they're there by default since templated queries in the UI are designed to be used this way. However it would be nice if there was an option to turn them off.

### Steps to Reproduce

1. Go to https://sql.telemetry.mozilla.org/dashboard/test_9

Expected Result: It should be possible to remove the variable boxes in a dashboard so that it's easier to read.
Actual Result: The variable boxes add clutter to the dashboard which makes the dashboard harder to read.

**Comment by alison985** [comment]
Okay, I made it so if you append hideParameters=true to the URL it will hide parameters in a dashboard.

Here's normal view:
![Screenshot 2017-07-28 14.22.57.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416703e7b5ce37a24cbb17af1172c43434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c071e83fe5835a19b4cce5afe49e74a5db65e.png)

Here's with the extra parameter:
![Screenshot 2017-07-28 16.26.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416703e7b5ce37a26cbb17ef1112e43434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c071e83fe5835a19b4cce5bf34ce14e50b65e.png)

**Comment by alison985** [comment]
PR #177

**Comment by alison985** [comment]
Verified fixed on staging based on PR comment: https://github.com/mozilla/redash/pull/177#issuecomment-320674769
