### ISSUE TITLE
Schema viewer should expose partitioned columns

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#185]
This only applies to tables which *have* partitions, i.e. just those in the Hive metastore (unless some RDBMS tables are sharded but... let's not go there). Exposing this information would make it easier to say to people "filter on partitions!" rather than have that be intimate knowledge for each dataset.

**Comment by alison985** [comment]
@fbertsch To make sure I'm understanding this right: in Hive data sources display to the user which columns there are partitions on. Perhaps with a [P] designation next to the field name?

**Comment by fbertsch** [comment]
@alison985 right - here is an example `DESCRIBE` query output - I've highlighted the partitions descriptions: https://pastebin.mozilla.org/9029373

[P] could work, something that goes along with whatever the schema browser's type information (which I haven't seen yet).

**Comment by alison985** [comment]
@fbertsch That pastebin doesn't work for me. Could you try again or another way please?

**Comment by fbertsch** [comment]
@alison985 https://pastebin.mozilla.org/9029674

**Comment by alison985** [comment]
Thanks. PR #201
