### ISSUE TITLE
Non-postgres data source doesn't display column type

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#186]
### Issue Summary
In the schema browser for the Athena upstream query runner the column types aren't displaying. 

### Steps to Reproduce

1. Go to query page and select Athena data source.
2. Click on a table to open a list of columns. The column type should be displayed in (). However neither the () or column type are currently being displayed.

Reference: https://github.com/mozilla/redash/pull/173#issuecomment-321536169

**Comment by alison985** [comment]
This works without code change, you just have to click the refresh schema button for each data source to get it to show up.

**Comment by madalincm** [comment]
The column type is displayed for all the data sources except ActiveData. Please view this screencast: 
![activedatatype](https://user-images.githubusercontent.com/15685441/29622449-24cac102-882c-11e7-9873-51d5e75c7c65.png)
Reopening the bug.

**Comment by rafrombrc** [comment]
Let's punt on ActiveData for now, we can open an issue just for ActiveData if we decide to add that later.

**Comment by madalincm** [comment]
As discussed in our meeting I will mark this bug as verified fixed.
The issue with ActiveData data source will be tracked in #219
