### ISSUE TITLE
Add Finer-grained scheduling

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#187]
I just ran into a problem. I have a dataset that updates weekly, so I know at a certain time on Sundays the data will be ready. What I wanted to do was set my plots to update at that time, weekly; but all I could do was select "every 7 days", which doesn't indicate to me when that is. There could be a delay of up to 7 additional days with that option.

Instead I had to set them to update every day at XX:XX, which is not a great solution because now I'm running 7x the number of queries on the DB.

**Comment by arikfr** [comment]
Maybe add a refresh API call to the job that updates the dataset?

Will give you the best result as it will always be in sync with the data update.

**Comment by fbertsch** [comment]
@arikfr that is a good idea. We could build an Airflow operator that integrates with Re:dash, have you considered this before?

**Comment by arikfr** [comment]
I haven't but sounds like something that will be useful for many. 

Let me know if you need details on the refresh API.

**Comment by alison985** [comment]
@fbertsch Based on the conversation above I'm pulling this out of the milestone 9 plan. I'm going to leave the ticket open for continued conversation.

**Comment by fbertsch** [comment]
@arikfr mind pointing me at info on the API endpoints we would need for this task?

**Comment by arikfr** [comment]
The API call is: `POST /api/queries/<query id>/refresh` and currently it needs to be run with a user API key (rather than a query API key).

**Comment by rafrombrc** [comment]
Upstream maintainers have been giving feedback on our proposed UI, we're currently integrating requested changes and will open a PR when the implementation is ready and tests are passing.

**Comment by emtwo** [comment]
https://github.com/getredash/redash/pull/2426

**Comment by emtwo** [comment]
Note: This probably needs a bit of a re-write and perhaps a change into React

**Comment by rafrombrc** [comment]
This has been ported to React and is undergoing final review upstream.

**Comment by jezdez** [comment]
This is now done via https://github.com/getredash/redash/pull/2426. Awesome work @emtwo! 🎉
