### ISSUE TITLE
Dashboard Forking

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#19]
Make it possible to fork dashboards similar to forking single queries.

**Comment by washort** [comment]
Tell me more about your use case here. My first guess for how to do this would be to create a new dashboard referring to the same queries; is that what you want, or do you want to fork queries as well as part of this process?

**Comment by emtwo** [comment]
Good question. I would want the dashboard to fork the queries as part of the process. This is useful for wanting to make a copy of a dashboard with slight modifications and without affecting the existing dashboard.

**Comment by emtwo** [comment]
For a more specific example, we use this to create a dashboard for every new A/B test we do in Activity Stream.

**Comment by arikfr** [comment]
@emtwo have you considered using parameters instead of creating a new dashboard?

**Comment by emtwo** [comment]
Yes. It's not exactly ideal to have to set the parameters for every new A/B experiment that we run. And there might be 15 or more graphs per dashboard that each need to change their parameters to look at a new experiment. Several of these experiments may be running at once and we'd need to switch back and forth between the parameters whenever we wanted to look at a different one. Some dashboards may have 1 or 2 additional or different graphs.

In my mind I want to think of it as a "base class" dashboard which has the minimally required graphs I need to show for an experiment. I then "subclass" it (aka fork) and perhaps I **also** have parameters in all of these graphs that are set when it's forked. I can then add additional graphs or modify graphs (in a way that can't be done with just parameters) as needed in the fork.

**Comment by washort** [comment]
I'm looking at the various ways to do this; it occurs to me that this could be done from the client side by firing off requests to fork all the queries and create a new dashboard, etc. @arikfr, are you interested in having something like this upstream? If so I'd obviously like to work with that.

**Comment by emtwo** [comment]
For my workflow, this was originally an intermediate solution until an API was ready. Since the API exists, I personally don't need this feature as much.

**Comment by rafrombrc** [comment]
Closing this b/c solution can be achieved w [redash_client](https://github.com/mozilla/redash_client).
