### ISSUE TITLE
Query version does not make sense for queries having only one version

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#194]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a query with a single version i.e: https://pipeline-sql.stage.mozaws.net/queries/80/source
2. Click on the options button and then on the Query Versions

### Expected results:
a) The Query Versions link is not displayed or it is disabled as there are no other queries to which current one can be revert to.
b) The query Version is displayed and when opening the compare page the current version section is not empty.

### Actual results:
When opening the compare query page the current version section is empty.

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![qv oneversion](https://user-images.githubusercontent.com/15685441/29274988-4b4ab1d2-8112-11e7-96e1-f2dabd48c44a.png)

**Comment by spasovski** [comment]
True - I will disable the link in this case.

**Comment by spasovski** [comment]
https://github.com/mozilla/redash/pull/206

**Comment by madalincm** [comment]
The link is removed for queries having only one version.
Postfix screencast: 
![qv singleversion](https://user-images.githubusercontent.com/15685441/29619406-ba30736c-8823-11e7-880f-9a4811475b64.png)
