### ISSUE TITLE
Wrong information displayed when comparing versions for a 2 versions query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#195]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a query with 2 versions i.e: https://pipeline-sql.stage.mozaws.net/queries/81/source
2. Click on the options button and then on the Query Versions.
3. Select Version 1 from the "Compare current version to" menu.

### Expected results:
When selecting version 1 the correct query should be displayed in the current and previous version section.

### Actual results:
The latest query version is displayed in both Current Query and Previous Query section. When you select version 2 the same thing is displayed.

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![qv oneversion](https://user-images.githubusercontent.com/15685441/29274988-4b4ab1d2-8112-11e7-96e1-f2dabd48c44a.png)

**Comment by spasovski** [comment]
https://github.com/mozilla/redash/pull/203 should also resolve this

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in STMO-stage
![195postfix](https://user-images.githubusercontent.com/15685441/29364279-9680b7fc-829b-11e7-927c-5f2a12af5893.png)
