### ISSUE TITLE
Colors presented in the Compare Query page for the Previous Version section suggests that the Previous Version will be modified 

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#196]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a query with 3 versions: https://pipeline-sql.stage.mozaws.net/queries/83/source
2. Click on the options button and then on the Query Versions.
3. Select Version 1 from the "Compare current version to" menu.

### Expected results:
In the Previous Version section there are is no color text because the previous version will not be modified.

### Actual results:
In the Previous Version section some of the text is red and some of the text is green which suggests that the version will be modified. 

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![qc colorpreviousversion](https://user-images.githubusercontent.com/15685441/29275704-a8aedd10-8114-11e7-87f5-2f91c0fea9e2.png)

**Comment by spasovski** [comment]
Very good call - should be fixed now: https://github.com/mozilla/redash/pull/203

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in STMO-stage
Postfix screencast:
![195postfix](https://user-images.githubusercontent.com/15685441/29364345-c8968fd2-829b-11e7-91b7-7e9ae34c245b.png)
