### ISSUE TITLE
When reverting a query to a previous version a new version is generated

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#197]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a query with 3 versions: https://pipeline-sql.stage.mozaws.net/queries/83/source
2. Click on the options button and then on the Query Versions.
3. Select Version 1 from the "Compare current version to" menu and click the Revert to version 1 button.

### Expected results:
The Query is reverted to version 1 state. No New versions are generated.

### Actual results:
A new version 4 is generated. The query is now in version 4 state.

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![qv newversgeneratedwhenreverting](https://user-images.githubusercontent.com/15685441/29275967-a6ce9aac-8115-11e7-87b5-e8aeb6410508.gif)

**Comment by alison985** [comment]
@spasovski I think this is intentional, but please confirm.

**Comment by rafrombrc** [comment]
I can confirm that this is indeed the intended behavior. Version history is additive... "revert" doesn't mean erase the version history, but instead create a new version that matches the chosen revision.
