### ISSUE TITLE
Query versions are not correctly ordered

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#198]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open any query with multiple versions: i.e. https://pipeline-sql.stage.mozaws.net/queries/85/source#table
2. Click on the options button and then on the Query Versions.
3. Click on the "Compare current version to" button

### Expected results:
The Versions are correctly ordered.

### Actual results:
The versions are not ordered

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![qv wrongorder](https://user-images.githubusercontent.com/15685441/29276145-535d76bc-8116-11e7-8b26-1433c7490a94.png)

**Comment by spasovski** [comment]
https://github.com/mozilla/redash/pull/207

**Comment by madalincm** [comment]
Verified as fixed in FF55 in STMO-stage.
Postfix screencast: 
![198postfix](https://user-images.githubusercontent.com/15685441/29526845-9faf0830-869f-11e7-9a45-957c766b8e70.png)
