### ISSUE TITLE
Query Versions are not correctly saved

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#199]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce:
1. Created a new query as it follows:
version 1: test1
version 2: test2
version 3: test3
version 4: test4
version 5: test5
2. Go to compare versions and select from the drop down menu Compare current version to version 1

### Expected results:
The Version 1 has the value "test1". In Current Version section the following is displayed: test1 (in red) 5(in green) 

### Actual results:
The Version 1 appears to have the value "test2"  In Current Version section the following is displayed: test2 (in red) 5(in green) 

### Notes/Issues:
Verified in FF54(Win7).  Issue can be reproduced only in STMO stage
The test query used can be found in here: https://pipeline-sql.stage.mozaws.net/queries/88/source

**Comment by spasovski** [comment]
should be addressed via: https://github.com/mozilla/redash/pull/203 -> I just tested it on stage

**Comment by madalincm** [comment]
The versions are now correctly saved and reverting works good. Marking the bug as verified fixed.
