### ISSUE TITLE
Add scrollbar to "Dashboards" dropdown accessible

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#2]
When the Dashboards dropdown grows beyond the end of the screen, it becomes impossible to access the records below the fold. Ultimately this should have an entirely different UI, providing search and filtering similar to the queries UI, but adding a scrollbar as a short term solution will at least make it possible to access all of the dashboards again.

**Comment by washort** [comment]
Arik's plan is to move the dashboard listing to its own page.
The workaround I saw suggested was to remove `position: fixed` from the CSS so the page could at least scroll.

**Comment by arikfr** [comment]
You can follow https://github.com/getredash/redash/issues/1393 for more
info. Luke seems committed to this so we might see a solution soon.

**Comment by spasovski** [comment]
Our temporary fix is here: https://github.com/mozilla/redash/pull/13 but it won't play well with older browsers so I wouldn't recommend it for an uplift.
