### ISSUE TITLE
Cannot edit existing graphs that I own

### ISSUE THREAD

**Issue by davismtl** [mozilla/redash#204]
### Issue Summary

I can't edit any of the charts that a part of a query that I made.

The save button is disabled and I am seeing the following error/warning messages for the first time:

-  **You have more than 2 columns in your result set.** You may wish to make the Stacking option equal to `Enabled` or `Percent`.

- You have more than 2 columns in your result set. To ensure the chart is accurate, please do one of the following:
  -  Change the SQL query to give 2 result columns. You can CONCAT() columns together if you wish.
  - Select column(s) to group by.

<img width="777" alt="screen shot 2017-08-15 at 4 13 00 pm" src="https://user-images.githubusercontent.com/19537086/29340586-a1cac156-81d4-11e7-888c-468be88fe037.png">

### Steps to Reproduce

1. Go to this query: https://sql.telemetry.mozilla.org/queries/18471/source?p_days=60#46875 
2. Try to edit any of the graphs
3. Try to hit save
4. You will not be able to hit save

Note that the chart was forked from this one which seems to suffer from the same bug:
https://sql.telemetry.mozilla.org/queries/4620/source?p_start_date=2007-04-01&p_end_date=2017-05-17#9385

### Technical details:

* Redash Version: Whatever mozilla uses.
* Browser/OS: Firefox Nightly 57

**Comment by alison985** [comment]
PR #205

**Comment by madalincm** [comment]
I'm not sure how to test this on stage as the data source used in the production query is not available in stage and I can't replicate the exact query. @alison985 do you have any suggestions? 

I have created a simpler query in stage and I'm able to edit the chart and save it.  (https://pipeline-sql.stage.mozaws.net/queries/102/source#112)
