### ISSUE TITLE
dot menu appears for query when no options in menu

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#208]
https://www.dropbox.com/s/qblzudhdyd6eir2/Screenshot%202017-08-17%2010.21.41.png?dl=0

**Comment by spasovski** [comment]
https://github.com/mozilla/redash/pull/209

**Comment by madalincm** [comment]
I can reproduce it, this is happening for queries that are not saved.

**Comment by madalincm** [comment]
The button is no longer displayed for queries that are not saved.
Postfix screencast: 
![unsavedqueries](https://user-images.githubusercontent.com/15685441/29618783-e3e7af74-8821-11e7-95f4-5abd081234cd.png)
