### ISSUE TITLE
Dashboarding API

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#21]
Add an API to create dashboards from existing graphs. The inputs could perhaps be:

1. An array of JSON objects that look something like:
```
{
  "graph_link": "<existing stmo graph link>",
  "size": "<Regular/Double>"
}
```
2. Title

The output could be an stmo link to the dashboard

**Comment by arikfr** [comment]
Everything you can do with the UI you can do via the API, as this is what the UI uses. Currently it's not one API call though. You will need to make N+1 (N=number of widgets) -- create dashboard and a call for each widget.

**Comment by arikfr** [comment]
(same goes for #20)

**Comment by emtwo** [comment]
Oh great! Is this API accessible to end-users? Or do you mean it's the API used by the UI?

**Comment by arikfr** [comment]
It's both - it's the API used by the UI and it's accessible to end-users. It's not documented, but you can open the browser's network panel to see the calls Redash makes. You can find your API key in your user profile page.

**Comment by fbertsch** [comment]
Maybe we can document this internally? @arikfr is there any reason it's not documented publically?

**Comment by arikfr** [comment]
No real reason. Just lack of resources.

I'll be happy if you share the docs publicly.

**Comment by emtwo** [comment]
Circling back here as I wasn't able to find the correct way to authenticate and form queries using the API Key. I'm able to mimic API calls that I can see in my network panel by using the session cookie.

Is there any basic example of a query using an API key @arikfr? Thanks!

**Comment by arikfr** [comment]
There are two ways to pass the API key:

* via query string: `https://redash/api/queries?api_key=...`
* Using the `Authorization` header: `Authorization: Key ...`

(replace ... with the API key)

**Comment by washort** [comment]
I've made a start on some API docs, I put them up on my people.m.o account for the moment: https://people-mozilla.org/~ashort/redash_docs/api.html

I'll continue to fill this out and hopefully we can find an official place for them soon.
