### ISSUE TITLE
STMO stage is not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#215]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/

### Expected results:
The page loads.

### Actual results:
The page does not load.

### Notes/Issues:
Verified in FF55(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![stagenotloading](https://user-images.githubusercontent.com/15685441/29562913-02646b24-8744-11e7-921c-d1f699b00d5a.png)

**Comment by alison985** [comment]
@madalincm  I reverted the upstream rebase and stage seems fine now.

**Comment by madalincm** [comment]
Stage is working now. Marking this bug as verified fixed.
