### ISSUE TITLE
Column type is not displayed for ActiveData data source

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#219]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Go to query page and select ActiveData data source.
2. Click on a table to open a list of columns. 

### Expected results:
 The column type is  displayed in ().

### Actual results:
The column type is not displayed.

### Notes/Issues:
Verified in FF55(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![activedatatype](https://user-images.githubusercontent.com/15685441/29654888-b3a1fcfc-88b7-11e7-9fe7-fc0e4d42d28f.png)

**Comment by alison985** [comment]
@klahnakoski Would you like us to add the column_type to the schema browser for an ActiveData data source in re:dash? If so, how would I query the column_type for a field?

**Comment by klahnakoski** [comment]
Hmm, that is going to be hard, since the columns are dynamically typed, maybe even whole JSON documents.

**Comment by klahnakoski** [comment]
Maybe we can pretend all the columns are strings?

**Comment by klahnakoski** [comment]
I made a pull request https://github.com/mozilla/redash/pull/231

The solution is a bit of a lie, but a reasonable approximation.

**Comment by madalincm** [comment]
Verified in FF55(Win7) in STMO-stage
Postfix screencast: 
![activedatareopen](https://user-images.githubusercontent.com/15685441/29878650-bed70de4-8dab-11e7-82ce-002b37b6c53f.png)
