### ISSUE TITLE
Inaccurate bars on ATMO Metrics dashboard

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#221]
The 'ATMO Cluster time to ready' graph on the 'ATMO Metrics' dashboard (https://sql.telemetry.mozilla.org/dashboard/atmo-metrics) is mostly accurate, but some of the bars on the graph don't match the values that they're supposed to represent. On Aug 22 there's a bar that looks like it stretches to 47, but mousing over it shows a value of 38, and another (earlier in the day) that looks like 27 but shows a value of 17. On Aug 21 a bar that stretches to 30 shows a value of 11. There may be more, this was just from a quick spot check.

**Comment by alison985** [comment]
Waiting on this one to see if the upstream error bar change in the rebase effects this.

**Comment by alison985** [comment]
@rafrombrc I can't reproduce this. This is what I see:
![Screenshot 2017-09-01 16.36.46.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167e3e7955e37a26cbb07ef1162d43434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c041f83fe5835a49a4bc851f64ee84f5db65e.png) I checked and the bars match the data in the table.

Moving to blocked until we can reproduce.

**Comment by rafrombrc** [comment]
I can no longer reproduce this either. Closing unless and until it resurfaces.
