### ISSUE TITLE
Show partitioned columns first

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#227]
Right now, partitioned columns show up last in the list of columns. Best to put it first so they are front and center.

**Comment by alison985** [comment]
I did this as part of another ticket. It's actually on prod right now as part of m9.1.

**Comment by madalincm** [comment]
The partitioned columns marked with [P] are now displayed first:
![partitionedcolumns](https://user-images.githubusercontent.com/15685441/30032351-1da88a64-919e-11e7-8b99-4990d53ef7db.png)

Marking bug as verified fixed.
