### ISSUE TITLE
If xaxis is datetime, auto-change it to datetime

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#228]
Right now the xaxis is assumed to be a datetime measure. If it is not you have to manually change it to something like "category". This is mildly annoying. We should be able to detect the xaxis type and auto-change it for the user.

**Comment by alison985** [comment]
Pausing this for a bit as it's become larger than I originally thought. It requires referring to the actual chart data within the chart editor which hasn't been there before.

**Comment by alison985** [comment]
I did a status commit of where I left off on this in this branch: https://github.com/alison985/mozilla-redash/tree/228_auto_pick_xaxis_type

**Comment by jezdez** [comment]
To clarify, the PR https://github.com/getredash/redash/pull/2542 has been merged upstream and I've asked @emtwo to figure out if this needs more work on our side.

**Comment by emtwo** [comment]
Yes, this is handled upstream now so we can close this.
