### ISSUE TITLE
3column messaging bug

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#229]
1. You have a bar chart visualization, the query has 2 columns in the result set, and you have a working visualization.
2. If you remove the value from the y column, you get the 3 column error message.

Expected: you should not get the 3 column error message in the visualization editor because you still only have 2 columns.

**Comment by madalincm** [comment]
I'm not sure about the 3 column error message but I can reproduce something similar for the following query: https://pipeline-sql.stage.mozaws.net/queries/107/source#122

When removing the value for the y column the following error appears:  "
You have more than 2 columns in your result set. To ensure the chart is accurate, please do one of the following:

    Change the SQL query to give 2 result columns. You can CONCAT() columns together if you wish.
    Select column(s) to group by.

"

Please view the following screencast: 
![morethan2columns](https://user-images.githubusercontent.com/15685441/29882348-66c8502c-8db5-11e7-9870-6e608d3db18e.gif)

I'm not sure this is the original issue. @alison985 do you think we should file a separate issue for this scenario or is the same as the original issue?

**Comment by alison985** [comment]
This is a separate issue but does not require a separate issue as it is the intended behavior for a result set with 3 columns. You have id, count(*), count(*) which is 3 columns. The issue this bug report is addressing is that the message was showing up when there was only 2 columns. The fix is on staging now and it is working for me in the happy path case.

**Comment by madalincm** [comment]
Thanks Alison for the info. i have retested this and I can't reproduce it:
![removey](https://user-images.githubusercontent.com/15685441/30032408-71d1acce-919e-11e7-970b-b75be8ceac34.gif)

Marking bug as verified fixed.
