### ISSUE TITLE
Schema explorer (or elsewhere) Needs more type information

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#23]
It would be nice if we had two types of type information available:
1. Type of DB - this is not apparent from a users perspective, and is leading to confusion (some mysql, some postgres, some redshift, presto, etc.)
2. Type of Columns - maybe this is already implemented and connectors need updated, but it sure makes things difficult without it

**Comment by alison985** [comment]
#1 is also in #46 and addressed in PR #85.

**Comment by alison985** [comment]
Blocked from front-end work by #152.

**Comment by alison985** [comment]
PR #173 for postgres
