### ISSUE TITLE
When changing a color in a pie chart multiple colors are changed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#242]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Open a query that has a pie chart visualization. In example: https://pipeline-sql.stage.mozaws.net/queries/119/source#141
2. Open the  Visualization Editor, color tab and modify the color for view_source field to green.

### Expected results:
Only view_source field changes color.

### Actual results:
Multiple color are changed in the chart.

### Notes/Issues:
Verified in FF55(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![colorchangepiechart](https://user-images.githubusercontent.com/15685441/29972757-e2ac872c-8f35-11e7-9e4c-0c92ce2a0ddb.gif)

**Comment by alison985** [comment]
PR #255

**Comment by madalincm** [comment]
Verified in FF55(Win7) in stmo-stage
I can still reproduce this issue. Please view this screencast:
![piechartcolorreopen](https://user-images.githubusercontent.com/15685441/30366482-e137de18-9873-11e7-9a1a-ee6cae00056a.gif)

**Comment by madalincm** [comment]
I'm still reproducing this issue in FF55(win7) in stmo-stage using this query: https://pipeline-sql.stage.mozaws.net/queries/141/source#188
Please view this screencast: 
![piechartcolorreopen2 gif](https://user-images.githubusercontent.com/15685441/30427971-7f1009c6-995a-11e7-8d04-294662159169.gif)
Reopening.

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-stage
The colors displayed in the piechart are changing correctly.
Postfix screencast:
![piechartcolorchangepostfix](https://user-images.githubusercontent.com/15685441/34829627-faa481ce-f6e9-11e7-815a-7257626365ec.gif)
