### ISSUE TITLE
The downloaded image of a chart does not contain all the information

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#243]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Steps to Reproduce:
1. Open a query that has a pie chart visualization. In example: https://pipeline-sql.stage.mozaws.net/queries/129/source#161
2. Hover over the chart a click the "Download plot  as a png" button.

### Expected results:
The image is downloaded. All the information is displayed in the image.

### Actual results:
The image is downloaded but only the first elements of the chart are displayed.

### Notes/Issues:
Verified in FF55(Win7).  Issue can be reproduced only in STMO stage
Screenshot for this issue:
![downloadimage](https://user-images.githubusercontent.com/15685441/29973782-64820486-8f39-11e7-92b3-b66c1cca7dae.gif)

**Comment by washort** [comment]
this appears to be working on stage currently.

**Comment by madalincm** [comment]
I have verified it in stage at in appears to be working now. Marking as verified-fixed for now and will log a new bug if this happens again. 
Thanks @washort 

![243working](https://user-images.githubusercontent.com/15685441/34942773-858e3900-fa01-11e7-96ab-5e79c66efab6.png)
