### ISSUE TITLE
add redash db size to status page

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#247]
from https://github.com/getredash/redash/issues/1411

**Comment by alison985** [comment]
Pending response from Arik on original issue.

**Comment by alison985** [comment]
PR #252

**Comment by alison985** [comment]
You get to the status page by clicking your name in the upper right hand corner and clicking on the "System Status" link in the menu.

**Comment by madalincm** [comment]
Verified as fixed in FF55(Win7) in stmo-stage
Postfix screencast:
![adddbsize](https://user-images.githubusercontent.com/15685441/30437519-7f91216a-9977-11e7-8d2d-5d606e93159f.png)
