### ISSUE TITLE
[Feature Request] Make it possible to give users edit permission for graphs/dashboards

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#257]
Use case: I want to create dashboards/graphs but also give certain users permission to modify them. It doesn't seem like there is a way to do that now.

cc @dmose

**Comment by dmose** [comment]
This has been implemented behind a flag in the main version of redash, and I _think_ the changes are already merged into our fork.

In [the Trello card](https://trello.com/c/9LvJzgXG/64-allow-others-to-edit-your-dashboards-and-queries), Arik sez that it basically just needs more real-world testing to be turned on default.  We could help with that.  :-)

Here's how:

> It's an environment variable that needs to be set -- REDASH_FEATURE_SHOW_PERMISSIONS_CONTROL to true. Should be harmless :)

**Comment by rafrombrc** [comment]
Related bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1315081

**Comment by jezdez** [comment]
We've deployed the feature to the STMO stage instance and I tested it with @robotblake. I'd appreciate it if anyone else would take a look at it before we push this out to prod (after the 57 launch).

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-stage. The option to grant permissions to another user was added. I have run a series of tests to cover adding an user/multiple users, removing them, actions performed by another user on the dashboard etc. Everything looks ok. Marking bug as verified fixed.
