### ISSUE TITLE
Clicking on Dashboard categories in Dashboards overview does not change URL

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#259]
### Issue Summary
STR:
1) visit https://sql.telemetry.mozilla.org/dashboards
2) Click on a dashboard category (e.g. Activity Stream)

Expected:
URL/path changes, e.g. https://sql.telemetry.mozilla.org/dashboards/Activity%20Stream

Actual:
URL remains `.../dashboards`

In practice, this creates the following user problems:
1. Clicking into a specific dashboard and clicking the browser back button brings the user to the dashboard overview, rather than the specific dashboard category that was previously selected.
1. It's impossible to share links dashboard categories, as well as bookmark them or return to them without clicking through the UI

### Technical details:
* Redash Version: ?
* Browser/OS: Firefox Nightly, 57

**Comment by washort** [comment]
fixed in https://github.com/mozilla/redash/commit/5356c1a75a2a38ce95a7d0bd5bebe71b883208f7

**Comment by madalincm** [comment]
Verified as fixed in FF58(Win7) in stmo-stage
![dashboardcategories](https://user-images.githubusercontent.com/15685441/35613484-f1281dbe-0674-11e8-845a-9447bae095e0.png)
Marking bug as verified fixed
