### ISSUE TITLE
Clicking "Execute" takes away focus from the query box

### ISSUE THREAD

**Issue by rayborn** [mozilla/redash#26]
_(I think that this is a regression, I've don't believe that I had this issue previously.)_

If you click "Execute" the focus is taken from the query editor.  This is annoying when doing query re-writes since I kept trying to type, often with a leading backspace which is the browser shortcut for "back".

**Comment by arikfr** [comment]
You can use `Cmd`/`Ctrl` + `Enter` to execute the query. This way you don't lose focus & don't have to take your hands from the keyboard.

**Comment by rayborn** [comment]
Thanks, still think that the focus should remain, but cmd + enter should be adequate for myself.

**Comment by rafrombrc** [comment]
Unfortunately, it's pretty fundamental to the web that when you click on a new element, that element gets the focus. We'd have to do something ugly like force the focus back to the query box if that's where it was before. Since there's a keyboard workaround we're going to close this as "wontfix".
