### ISSUE TITLE
redash query search is not flexible enough, hard to find things

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#260]
### Issue Summary
Redash query searching doesn't seem to use fuzzy text search and it makes it really hard to find anything if you didn't already know it existed.

For example, I type "android activity" into the search box and there are no results. However, there is a dashboard "Android: Activity Stream Metrics Summary" that is not being shown. Note that "android: activity" also finds no results.

**Comment by madalincm** [comment]
Verified in FF57(Win7) in stmo-stage.
I have tested this using the example from the first comment. I have created a new dashboard in stage named Android: Activity Stream Metrics Summary .  When searching for "Android: Activity" or "Android Activity" or the full name "Android Activity Stream Metrics Summary " no results are returned. Please view this screenshot:
![fulltext](https://user-images.githubusercontent.com/15685441/32279512-9ee8ec80-bf21-11e7-888a-150529e7a1f7.png)

reopening.

**Comment by jezdez** [comment]
@madalincm Thanks for the verification, but I'm afraid Redash doesn't (read: not yet) support searching for dashboards, but just queries. I'm working with the Redash author to rectify the problem and the PR #270 was the first step which changes the backend for the search.

That said, this ticket is about improving the query search, not adding dashboard search. I've opened #274 to explore this feature request. I'm closing this ticket as it effectively was solved.

**Comment by jezdez** [comment]
@robotblake Speaking of which, can you clarify if #270 has been deployed to stage at all?

**Comment by madalincm** [comment]
@jezdez I usually run a regression suite on every release which include some tests on query search. Except that, making sure nothing is broken, what other scenarios would make sense to run to test this fix? Can you please give me some directions?

**Comment by jezdez** [comment]
@madalincm Of course, the issue of this ticket was the main search field in the top navigation bar which will result in a full text search trough the created queries, but not the dashboards and alerts (which each have local Angular based searches).

So best would be to run tests against that search form and then see if the result list shows the results we expect. Does that make sense?

**Comment by arikfr** [comment]
Hi @madalincm,

(A bit off topic)

> I usually run a regression suite on every release which include some tests on query search. 

Can you share more about this suite? Is it just documented tests you manually do or some automated suite of tests?

I'll be happy to learn more about how you test releases, as it might be useful for upstream too.

I don't want to spam a random issue, so we can continue this over email (arik at redash.io).

Thanks :-)

**Comment by madalincm** [comment]
#277 Was fixed and is now marked as verified fixed. I've also run a full regression test suite against the full text search and everything looks good. Marking this bug as verified fixed.
