### ISSUE TITLE
redash query search does not differentiate between loading and no results

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#261]
### Issue Summary
STR
1) Search a query that won't have any results (e.g. aoeustnhaoeusnthaoeu)

Expected: "No results found"
Actual: No indication of loading or a completed query

This makes it really hard to determine if my query is taking a long time or my query doesn't work. This, in addition to #260, makes searching a rather annoying experience.

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-stage
 "No results found" text is displayed when the search does not return any queries.
Postfix screencast:
![noresults](https://user-images.githubusercontent.com/15685441/34828574-ad1554f4-f6e6-11e7-9614-6ae738e02ac5.png)
