### ISSUE TITLE
Tables and fields missing for Athena dataset

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash#268]
On production STMO:

https://sql.telemetry.mozilla.org/queries/new

When you select the Athena dataset, you should see the list of tables and their fields on the left.  It has disappeared, which makes writing queries much more difficult.

**Comment by jezdez** [comment]
The effect here is that when Redash frontend tries to fetch the schema from the Redash API it fails witha 500 error. The exception can be seen in https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/645052/ for example.

The actual error that has something to do with us tripping over using an internal API of pyathena apparently which changed when it got (recently?) updated in prod. Fortunately @robotblake has already written a patch for it over in #267. Once that's updated to remove the private API, this should be easy to deploy. Unless I'm misinterpreting things @robotblake?

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-prod. Issue is no longer reproducing. Marking bug as verified fixed.
Postfix screencast:
![atheneprod](https://user-images.githubusercontent.com/15685441/32439865-5592c700-c2f9-11e7-9fa1-6cbb61109813.png)
