### ISSUE TITLE
Re:Dash Graphs Returning Bad Request with Embed Link

### ISSUE THREAD

**Issue by hcrince** [mozilla/redash#27]
We are working on getting some of the charts within re:dash into the Data Collective and we have encountered an error with the embedding that we have never seen before.

Here is the error that we get for the visualization we wanted to embed:
https://sql.telemetry.mozilla.org/embed/query/1312/visualization/2281?api_key=17c0f75009ff05473779978c4c548b2289cc6a1b

What is should render is this in the Data Collective:
https://mozilla.metricinsights.com/extcontent/index/index/element/458/name/ER+by+OS

**Comment by arikfr** [comment]
This query has parameters?

**Comment by washort** [comment]
Good catch. 

This query does take a parameter, and we don't have `ALLOW_PARAMETERS_IN_EMBEDS` set.
Looks like this is fixed in the new version.

Until then, the easiest workaround would be to fork this query and remove the parameter, and embed the fixed version.

**Comment by hcrince** [comment]
Thanks, do we know when the 'new version' is expected?

Much appreciated.
Heather

**Comment by rafrombrc** [comment]
We have to coordinate with ops, and test to make sure things are working, etc., but we hope to have a new deployment by the end of this week.

**Comment by davismtl** [comment]
FWIW, I have other queries with parameters that have been successfully embedded into the Data Collective that didn't return an error message. For example:

https://mozilla.metricinsights.com/extcontent/index/index/element/461

**Comment by arikfr** [comment]
I recommend against setting `ALLOW_PARAMETERS_IN_EMBEDS` to true (specially if you share embeds in external environments). Also the new version does not address this (in fact, it broke the `ALLOW_PARAMETERS_IN_EMBEDS` functionality).

It's possible @davismtl's query works because it has a value in the `latest_query_data_id` column, but that's a fluke and something that was fixed (we no longer set this value for parameterized queries).

**Comment by rafrombrc** [comment]
Hi! Just commenting to summarize where we are with this... currently, it looks like allowing parameters in embedded graphs opens up a whole new can of security related worms; it's pretty much the definition of a SQL injection attack. Ideally embeds wouldn't contain parameters at all, instead the queries would be forked and a static version would be used for the embed. If there is a rigid requirement that we allow query parameters in the embedded graphs then we'll want to involve some folks from opsec to make sure they're comfortable with the results.

**Comment by rafrombrc** [comment]
Looks like support for the feature flag working again is landing upstream: https://github.com/getredash/redash/pull/1524

I'd still like to get some security review on the implications of turning this on for our installation.

**Comment by arikfr** [comment]
> I'd still like to get some security review on the implications of turning this on for our installation.

I highly recommend not enabling this. Specially if your instance is publicly available and not behind a VPN. It has both the security issue but also performance issue, as queries being executed in the web process.

The long term solution for this is to have proper sanitization of the parameters and move the merge of parameter + query into the query runner.
