### ISSUE TITLE
Add Dockerflow endpoints

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#272]
We're using [Dockerflow](https://github.com/mozilla-services/Dockerflow) for deploying Redash ourselves but miss the providing information as defined in the spec.

To do that we'll need to extend [python-dockerflow](http://python-dockerflow.readthedocs.io/) to have a Flask backend (in the form of a Flask extension).

**Comment by jezdez** [comment]
@robotblake @washort Any information of how monitoring happens right now?

**Comment by jezdez** [comment]
I've started to work on support for Flask in python-dockerflow, [WIP here](https://github.com/mozilla-services/python-dockerflow/pull/18)

**Comment by jezdez** [comment]
This will fix #68 as well, basically

**Comment by rafrombrc** [comment]
Code is done, pending review by Harold (which might take a week or two). Currently updating the documentation.
