### ISSUE TITLE
Ability to merge query results from different data sources

### ISSUE THREAD

**Issue by davismtl** [mozilla/redash#28]
As a product manager, I have multiple data sources in Re:Dash that I would like simultaneously query to merge results and plot into one graph chart. 

I have observed that different teams use different data sources too and there is no way to easily combine data from those various sources.

If we can create relations between these different data sources, it would be even better (e.g. Looker allows to do this).

Real life example: 
- Firefox, Activity Stream and Firefox accounts use different databases spanning Redshift and Presto. If we would like to compare the retention and engagement rate of these different types of users, we currently need to write 3 queries, need to export the results and merge them in a spreadsheet.

I've noticed this feature mentioned here: https://trello.com/c/8RbdZPGW/57-ability-to-merge-query-results-from-different-data-sources
However, I could not find a corresponding Github issue.

**Comment by arikfr** [comment]
See this: https://redash.io/help/queries/using-datasets-as-data-sources.html -- will it address your need?

It's currently only available in the hosted version, but I'm going to open source it after the 1.0 release.

**Comment by davismtl** [comment]
Yes, this seems to be moving in the right direction. This looks great and would surely allow us to do many new types of queries.

**Comment by emtwo** [comment]
+1 I am really looking forward to being able to do this!

**Comment by alison985** [comment]
This is not currently mentioned in the changelog.

**Comment by arikfr** [comment]
https://github.com/getredash/redash/pull/2072 :-)

**Comment by rafrombrc** [comment]
This is now deployed on stage, needs QA verification, assuming all is well it should land in production during our next deployment.

**Comment by madalincm** [comment]
I have read the documentation available in here http://help.redash.io/article/152-query-results-data-source
I do not understand the part where you need to create a new data source of type "Query Results". Is that something that needs to be done every time you create a query which results you will later use as a independent table?   I'm not sure how to do that @rafrombrc @arikfr  can you please help with some background in here?

I've tried in stmo-stage to create a simple query that I saved  (https://pipeline-sql.stage.mozaws.net/queries/179/source) After that I have tried to use the results of the above query writing something like this:

select id
from query_179
limit 10
I get the following error: "Error running query: relation "query_179" does not exist LINE 2: from query_179 ^ "

**Comment by rafrombrc** [comment]
I'm not 100% sure, but I think that creating the new data source is something that @robotblake would do as an underlying admin task, and once that's done 'Query Results' will start appearing in the drop down list of data sources. I'll dig further and will report back.

**Comment by rafrombrc** [comment]
Yup, that was it. Blake has added the 'Query Results' data set and it's now showing up in the drop-down for me on staging. :)

**Comment by madalincm** [comment]
I can see the 'Query Results' data set now in stage so we are good there but my above example is still not working for me. 
So I have the same query https://pipeline-sql.stage.mozaws.net/queries/179/source#table which has the id '179' and I try to use the results of this query in another one https://pipeline-sql.stage.mozaws.net/queries/182/source     but I'm geting the same error "Error running query: relation "query_179" does not exist LINE 2: from query_179 ^ "

the second query just select the id field from the results set of query_179:
select id
from query_179
limit 10

Am I doing something wrong? Do I need to do something else to add the result set of query_179 to the 'Query Results' data set or that should happen automatically when I execute the second query?

**Comment by jezdez** [comment]
@madalincm Can you check again, I changed to selecting specific fields and clicked the save button, and suddenly query 182 worked as intended.

**Comment by jezdez** [comment]
I'm wondering if that's an issue of the query results requiring a distinct saving before they are available or a matter of the query parser..

**Comment by madalincm** [comment]
It is working for me now. I've tried several scenarios and it looks good. After a query is saved it can be used in further queries as a distinct table as long as the data source for the new query is set to "Query results".
