### ISSUE TITLE
Changing the "Data Source" for a query, then clicking "Save" shows an error dialog

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#281]
### Issue Summary

If you change the data source against which a query is set to run, it gives the following error message:
```
It seems like the query has been modified by another user. Please copy/backup your changes and reload this page.
```

### Steps to Reproduce

1. Create and save a query against the "Presto" data source. Execute the query.
2. Change the data source to "Athena", and click "Save".

It appears that the change does get saved, and if you reload the page, the updated data source has been saved.

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-stage
Issue is no longer reproducing
Postfix screencast:
![changeddatasourcesave](https://user-images.githubusercontent.com/15685441/34833173-7a83210e-f6f7-11e7-9091-b7ff323d78ba.gif)
