### ISSUE TITLE
Add an option to turn off autocomplete for a user

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#282]
I really do not like the current autocomplete, and it actually slows me down quite a bit when I'm writing queries. Basically, when I'm trying to write a query, it autocompletes just about everything; and then if I press enter to try and make a newline it instead replaces my correct text with something wrong and unrelated. So I have to go back, erase it, put the original back in place, then press space, then do a newline.

**Comment by madalincm** [comment]
Verified as fixed in FF57(Win7) in stmo-stage
Auto completion can be now toggled on/off 
Postfix screencast:
![autocomplete](https://user-images.githubusercontent.com/15685441/34833405-f5c37800-f6f7-11e7-86a3-57b1dfc30fd0.gif)
