### ISSUE TITLE
Schema reference is missing telemetry_core_parquet

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#284]
### Issue Summary

When writing a query, there is a schema reference on the left side but it doesn't include the `telemetry_core_parquet` table:
![screenshot-2017-11-27 copy of 48853 fennec activity stream engagement release](https://user-images.githubusercontent.com/759372/33296350-f620cb1c-d38f-11e7-91c0-88ce69a493e1.png)

### Steps to Reproduce

1. Create a new query
1. Look in table for `telemetry_core_parquet`

Expected: Shown
Actual: Not shown

**Comment by rafrombrc** [comment]
Related: #285

**Comment by madalincm** [comment]
Can't be verified in stage. Will verify it in prod after the push.

**Comment by madalincm** [comment]
I am blocked from verifying queries on Athena in prod. I have logged #306

**Comment by madalincm** [comment]
Tables "telemetry_core_parquet" and "telemetry_core_parquet_v2" are displayed in production. Howerver when I tried to run queries against them no results are returned, I have logged #308 to track the issue.
Marking this bug as verified fixed.
