### ISSUE TITLE
Misleading error messages w sql syntax errors

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#290]
SQL syntax errors are generating scary error messages that look like bigger redash failures in sentry, we need to make sure users are seeing accurate errors and hopefully that they're not showing up in sentry at all.

**Comment by washort** [comment]
Example - https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/1816645/

Celery uses JSON for messaging instead of pickle now and thus fails here. It's still showing the error to the user.

**Comment by washort** [comment]
Fixed. The task code was returning an exception object rather than raising it.

**Comment by madalincm** [comment]
I have simulated some sql sytax errors and at this moment in stage the error messages look a bit generic:
![290](https://user-images.githubusercontent.com/15685441/38095879-2f4c95d4-337a-11e8-8852-ab453d764654.png)
Any kind of syntax error is generating a message that looks like that which might be not that helpful.

In production we would something much clearer about what the issue really is:
Error running query: QueryExecutionError(u"line 1:173: mismatched input 'rfom' expecting {<EOF>, ',', 'EXCEPT', 'FROM', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'ORDER', 'UNION', 'WHERE'}",) is not JSON serializable
