### ISSUE TITLE
Query search result is limited to 20 queries

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#298]
### Steps to Reproduce:
1. Open the stmo homepage: https://pipeline-sql.stage.mozaws.net/
2. Click on the Search Query field and enter a general search term, i.e: "test" and click on the magnifying glass icon to perform the search

### Expected results:
All the queries that match the search term are returned.

### Actual results:
Only 20 queries are returned.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Verified in FF57(Win7).  Issue can be reproduced only in STMO-stage and STMO-prod
![20results](https://user-images.githubusercontent.com/15685441/34781127-b22a8eb4-f62d-11e7-8df8-1d68c27c6d5f.gif)

**Comment by jezdez** [comment]
This is fixed in https://github.com/getredash/redash/pull/2041, just needs backporting.

**Comment by madalincm** [comment]
Verified as fixed in FF58(Win7) in stmo-stage
The results are no longer limited, marking bug as verified fixed.
![searchresults](https://user-images.githubusercontent.com/15685441/35399380-c055e6ca-01fc-11e8-81b0-2ae9b3d292e4.png)
