### ISSUE TITLE
The user icon is changing after saving a query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#299]
### Steps to Reproduce:
1. Open the new query page: https://pipeline-sql.stage.mozaws.net/queries/new
2. Save the query

### Expected results:
The user icon remains the same

### Actual results:
The user icon is changed after the query is saved

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Verified in FF57(Win7) Issue can be reproduced in stmo-stage
![usericon](https://user-images.githubusercontent.com/15685441/34783446-470e8070-f634-11e7-9411-5e5ef073c83f.gif)

**Comment by washort** [comment]
Pretty sure this is just a transient network error fetching the gravatar image; not seeing it on stage currently.

**Comment by madalincm** [comment]
Issue is no longer reproducing in stmo-stage. Marking bug as verified fixed.
