### ISSUE TITLE
Get auto-deploy to staging to happen when a properly formed deploy tag is applied

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#30]
We now have a docker container that can be used for redash deployment to s.t.m.o, but we need to smooth out the deployment process so we can move to a short iteration / deployment development process.

**Comment by rafrombrc** [comment]
Docker setup is in place, deployment story is much improved, build are parameterized, but it is not yet automatically deploying to stage when a release is tagged.

**Comment by arikfr** [comment]
I'm curious, how are you running the Docker containers -- using some cluster?
