### ISSUE TITLE
Stmo-stage is not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#307]
### Steps to Reproduce:
1. Open stmo-stage homepage https://pipeline-sql.stage.mozaws.net/
 
### Expected results:
Stmo-stage loads.

### Actual results:
Stmo-stage does not load. 502 error displayed

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Verified in FF57(Win7).  Issue can be reproduced in STMO-stage
![502stage](https://user-images.githubusercontent.com/15685441/35087105-aa6471da-fc37-11e7-911e-951970934983.png)

**Comment by washort** [comment]
fixed, stage now has new upstream redash UI stuff on it

**Comment by madalincm** [comment]
Verified as fixed in FF58(Win7) in stmo-stage
Stage is now loading. Marking bug as verified fixed.

**Comment by madalincm** [comment]
Stage is down again with the same 502 error code. Reopening issue.
