### ISSUE TITLE
Querying the telemetry_core_parquet table does not return anything

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#308]
### Steps to Reproduce:
1. Execute this queries:
 a) https://sql.telemetry.mozilla.org/queries/50314/source
 b) https://sql.telemetry.mozilla.org/queries/50313/source

### Expected results:
Some results are returned.

### Actual results:
No results are returned when querying against telemetry_core_parquet and telemetry_core_parquet_v2

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Verified in FF57(Win7).  Issue can be reproduced in STMO-prod
![parquetnoresults](https://user-images.githubusercontent.com/15685441/35213200-80dc6d64-ff65-11e7-869a-3c96d440c8a4.png)
![parquetnoresults2](https://user-images.githubusercontent.com/15685441/35213243-a005e74c-ff65-11e7-9117-1e6faff44cc0.png)

**Comment by jezdez** [comment]
There is a Bug opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1430199

**Comment by rafrombrc** [comment]
Verified as fixed on STMO production.

**Comment by madalincm** [comment]
Issue is no longer reproducing in stmo production. Marking bug as verified fixed.
