### ISSUE TITLE
Schema viewer should not automatically show versioned tables

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#31]
In Presto, we have both $TABLENAME, and $TABLENAME_$VERSION, where we have many historical versions of a table. Most of the time, people just need $TABLENAME. Not only does having all the versions clutter the menu, it also slows it down drastically and makes it difficult to use.

I would propose some way to optionally view all versioned datasets for a $TABLENAME.

Note that this is specifically a mozilla thing, and has to do with how we process ETL jobs in our pipeline. Parquet2hive guarantees this $TABLENAME_$VERSION and $TABLENAME convention.

**Comment by arikfr** [comment]
In the no so distant future I want to improve the schema browser & add a dedicated screen for it. As part of this I'm thinking of letting the user decide which tables he wants to show in the schema browser. So you will be able to hide all the $TABLENAME_$VERSION.

Re slow down: that shouldn't happen any more. How many tables/columns do you have?

**Comment by fbertsch** [comment]
I just verified again that the slow down occurs. It is very difficult to scroll through the list of tables.

We have 195 tables, of which 164 are versioned tables.

**Comment by arikfr** [comment]
Just noticed that the version you're deploying doesn't have the performance fix I made to the schema browser. So hopefully once you deploy master it will resolve the slow down.

**Comment by fbertsch** [comment]
Makes sense, that was going to be my guess as well. Would still like to see the other improvements to the schema browser!

**Comment by arikfr** [comment]
Me too ;-)

**Comment by washort** [comment]
We'll ignore table names on Presto of the form 'foo_vN' in the schema listing.
https://github.com/mozilla/redash/commit/bf1036181b32874974d2880640b3371d2bda55b4

**Comment by fbertsch** [comment]
I don't know if that's a good solution. The versioned tables have different schemas, they should still be available, but only when needed.

**Comment by washort** [comment]
The schema listing loads everything at once, so we'd have to invent some means for discerning when that should include versioned tables or not.

**Comment by fbertsch** [comment]
Simple Solution: A button to decide whether to show versioned tables (with copious documentation)

Complex Solution: A button next to each dataset, for whether to show version for that dataset (a little plus)

Sorry, didn't say it was going to be straightfoward :)

**Comment by rafrombrc** [comment]
Just confirming that this issue only represents filtering these tables in the UI, we may open another issue to cover the possibility of changing the API to support only pulling down the tables that we need. Yes, we'll add a toggle so the tables can be displayed.

**Comment by rafrombrc** [comment]
Recent updates show that the search box is responding much more quickly now, not sure why it was still slow last time I checked. We want to leave this open bc this filtering will still be useful, but deprioritizing bc it's no longer a major pain point.

**Comment by alison985** [comment]
PR #102
