### ISSUE TITLE
Missing message for loading queries i don't have access to

### ISSUE THREAD

**Issue by georgf** [mozilla/redash#310]
Trying to load [this query](https://sql.telemetry.mozilla.org/queries/50270/source) i don't get to load anything.

Presumably that is because i don't have access to that query (it's a search query).
We should show at least a message here to make it clear what the problem is.

<img width="939" alt="screen shot 2018-01-23 at 07 50 30" src="https://user-images.githubusercontent.com/407696/35285460-4b92a922-0012-11e8-9bda-aba0af4cb319.png">

**Comment by arikfr** [comment]
This was fixed in upstream.

**Comment by madalincm** [comment]
I'm not sure how we can simulate this issue in stage. Is there a way to limit access to a query for some specific users? @rafrombrc
