### ISSUE TITLE
Queries link from the header is no longer a dropdown menu

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#312]
### Steps to Reproduce:
1. Open stmo-stage: https://pipeline-sql.stage.mozaws.net/ and observe the Queries link

### Expected results:
The queries link is a drop down menu that contains and "All queries link" and a list of recent queries.

### Actual results:
The queries link hasn't got a drop down menu.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
The Dashboard link is a drop down menu. Also on the old UI the Queries link was a drop drop down. For consistency we should keep the queries link as a drop down menu.
![uichangesquerieslink](https://user-images.githubusercontent.com/15685441/35435544-cbbe7cf6-0293-11e8-82b6-fe2783051263.png)

**Comment by madalincm** [comment]
Verified in FF58(Win7x64) in stmo-stage
Issue is still reproducing:
![312reopen](https://user-images.githubusercontent.com/15685441/36734925-99a4db08-1bdd-11e8-98f8-679aae3a0513.png)

**Comment by washort** [comment]
The "New Query" item was moved under "Create" and the old "Queries" item moved to the top bar.
