### ISSUE TITLE
Data source schema is not automatically changed when the user select a new data source

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#314]
### Steps to Reproduce:
1. Open new query page: https://pipeline-sql.stage.mozaws.net/queries/new
2. Click on the data source drop down menu and select another data source

### Expected results:
The data source is automatically changed.

### Actual results:
The data source is not automatically changed. The user needs to refresh the schema to see the tables from the selected data source

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage

![uichangesschemarefresh](https://user-images.githubusercontent.com/15685441/35439511-b665ce62-02a3-11e8-8098-a2c5cb5423b0.gif)

**Comment by madalincm** [comment]
Verified in FF58(Win7x64) in stmo-stage
Issue is still reproducing:
![314reopen](https://user-images.githubusercontent.com/15685441/36734760-245d0d66-1bdd-11e8-97fc-aa4bdf7833f2.gif)

**Comment by washort** [comment]
This is working on stage currently.

**Comment by madalincm** [comment]
Verified as fixed in FF59(win7) in stmo-stage
marking bug as verified fixed.
