### ISSUE TITLE
The navigation displayed in the query source page is not centered

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#320]
### Steps to Reproduce:
1. Execute this query: https://pipeline-sql.stage.mozaws.net/queries/271/source
2. Scroll down and observe the navigation between result pages

### Expected results:
The navigation is centred

### Actual results:
The navigation aligned to left.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
![navigationalignment](https://user-images.githubusercontent.com/15685441/35445803-7c18d4ee-02bb-11e8-8207-0abc4e2007b2.png)

**Comment by madalincm** [comment]
Verified in FF58(Win7x64) in stmo-stage
Issue is still reproducing:
![320reopen](https://user-images.githubusercontent.com/15685441/36674445-c59c2ca4-1b0e-11e8-867c-e842073d33c1.png)

**Comment by alison985** [comment]
merged upstream

**Comment by alison985** [comment]
The upstream changes should have been caught in the latest rebase from upstream, so I'm moving this to done so @madalincm  can check it.

**Comment by madalincm** [comment]
Verified in FF61(Win7) in stmo-stage
Issue is no longer reproducing:
![ceneterednavquery](https://user-images.githubusercontent.com/15685441/43847779-21335532-9b3a-11e8-969e-8598340a06a6.png)
