### ISSUE TITLE
Long query result sets are breaking the page layout

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#321]
### Steps to Reproduce:
1. Open the new query page: https://pipeline-sql.stage.mozaws.net/queries/new
2.  Select redash metadata for data source
3. Execute this query: select * from queries limit 100
4. Scroll down and observe the displayed results

### Expected results:
The query is successfully executed, the results are correctly displayed.

### Actual results:
The query is successfully executed, the results are breaking the layout.

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
![uichangeslongresultdisplayissue gif](https://user-images.githubusercontent.com/15685441/35446424-566a2fd4-02bd-11e8-8652-9bbdd095f98e.gif)

**Comment by arikfr** [comment]
This and some other query page related issues are handled by https://github.com/getredash/redash/pull/2245. 

Although note that some of your other issues are related to changes done in your fork.

**Comment by madalincm** [comment]
The page layout is no longer broken but the results are truncated. #342 was logged to track that issue.
I will wait for #342 to be fixed before closing this

**Comment by madalincm** [comment]
Issue is no longer reproducing. Closing and marking as verified fixed.
