### ISSUE TITLE
Include the query search option in the all query page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#323]
### Issue Summary
We should include the search query functionality in the "All queries" page. At this moment in stage there are 2 distinct pages: 
1. All queries page:  https://pipeline-sql.stage.mozaws.net/queries?page=1 - this page does not include a search field (except the on from the page header) and the user can't sort the queries displayed in this page.
![uichangesallqueriespage](https://user-images.githubusercontent.com/15685441/35511257-dac9cb52-0503-11e8-94c1-c85806de0425.png)

2. Search page: https://pipeline-sql.stage.mozaws.net/queries/search - when the user open this page he sees a message that there are no results found when in fact no search has been performed so far. 
![uichangessearchpage](https://user-images.githubusercontent.com/15685441/35511275-e2a7876a-0503-11e8-8765-0934014970ec.png)

Having an extra Search tab seems redundant giving the fact that we have the search bar in the page header.  Moving it to the all query page would make the search flow more natural to the user. 

### Technical details:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in STMO-stage

**Comment by madalincm** [comment]
Verified in FF58(Win7x64) in stmo-stage
Issue is still reproducing

**Comment by jezdez** [comment]
This is related to #384

**Comment by rafrombrc** [comment]
This should be fixed when the discovery branch is merged upstream and then into our repo.

**Comment by jezdez** [comment]
This has been fixed by merging the discovery branch.
