### ISSUE TITLE
Provide re-usable building blocks for queries

### ISSUE THREAD

**Issue by mcomella** [mozilla/redash#328]
As someone who doesn't use sql.tmo often, every time I write a query, I need to find a previously written query to do the same tasks over and over again. Examples:
- Return all results < 6 months old
- Format date in a certain way
- Pull out data from list of DAUs/WAUs/MAUs

It'd be really great if there were reusable building blocks so every query didn't have to reproduce this functionality - think of it like functions for mozilla's redash!

**Comment by arikfr** [comment]
That's sort of what the query snippets are for... aren't they being used at Mozilla?

So query snippets will save you the trouble of finding and typing this all over again, but it won't update after you insert the snippet into the query.

**Comment by rafrombrc** [comment]
@arikfr Apparently not. ;)

@mcomella Do query snippets meet your need, or do you have a use case that they don't satisfy?

**Comment by mcomella** [comment]
@rafrombrc They look like they would, yes. However, I can't seem to find a way to access them through the sql.telemetry.mozilla.org interface.

**Comment by rafrombrc** [comment]
@mcomella Sorry for the delay in replying... I got lost in some confusion re: the availability of query snippets, because I found a page (here: https://help.redash.io/article/39-query-snippets-shortcuts) that says only admins can create them. Our experimentation shows that this is incorrect, however, non-admins can create them.

If you click on your name in the upper right hand corner, click on your name in the dropdown menu, you should see a 'query snippets' tag that will take you to the interface. The help.redash.io page linked above should help you get started (incorrect availability information notwithstanding).

**Comment by mcomella** [comment]
@rafrombrc Can query snippets be shared between users without copy/pasting then? As someone who infrequently uses re-dash, I think it'd be great to steal some snippets (like DAUs) from high frequency users on my team.

**Comment by mcomella** [comment]
Found it! :)

<img width="1406" alt="screen shot 2018-03-08 at 11 21 22" src="https://user-images.githubusercontent.com/759372/37171488-e8536814-22c2-11e8-8325-983fb1501155.png">

Caveat: I don't know if there's a way to search these query snippets without clicking through all the pages and doing find-in-page.

**Comment by rafrombrc** [comment]
@mcomella Snippets work via the autocomplete mechanism that is in effect when you're creating and/or editing a query. Every snippet has a "trigger", if you type that trigger in while you're in the query editor you should see the snippet show up as an autocomplete suggestion. Select it from the autocomplete dropdown, and the snippet will be inserted where the cursor is. So if you type 'hll_' while you're in the query editor you should see the snippet show up and become usable.

Hope this helps!

**Comment by mcomella** [comment]
So it does! Great! :)

Should we close this issue as WORKSFORME or perhaps there is an action item to publicize this?

**Comment by arikfr** [comment]
> @arikfr Also, I should draw your attention to the https://help.redash.io/article/39-query-snippets-shortcuts page which has inaccurate information about only admins being able to create query snippets. Is there a place to submit a bug for getting that page corrected?

@rafrombrc I missed your original message, but happy to share that all the help pages sources are now on GitHub (here's [the query snippets page](https://github.com/getredash/website/edit/master/website/_kb/user-guide/querying/query-snippets.md)).

I [already updated this page](https://github.com/getredash/website/commit/5c383b6c713ab7e7db0be58c68ed9ed9eea8ebcc) and removed the note about admins.
