### ISSUE TITLE
[Feature Request] S3 Data Source

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#329]
The use case for this would be nearly identical to that of the `JSON URL Fetcher` data source with the additional bonus of having the data behind the S3 bucket credentials.

This is useful for displaying analysis in Redash that was done with external sources and stored on S3 but cannot be publicly available.

**Comment by emtwo** [comment]
Note: it's possible to use basic HTTP auth but it would be part of the query string in redash so anyone could copy the URL from there and share it with someone outside of Mozilla.

**Comment by rafrombrc** [comment]
Do we still need this now that we have the workaround with the JSON URL Fetcher supporting authentication?

**Comment by emtwo** [comment]
No this is not needed anymore

**Comment by rafrombrc** [comment]
Great, thanks. Closing.
