### ISSUE TITLE
Bar graph using Log scale sometimes truncates values

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#334]
### Issue Summary

When using a categorical x-axis and a logarithmic scale y-axis, sometimes a bad value is selected as the max Y and results in data being truncated.

### Steps to Reproduce

Using a prestodb datasource, enter the following query (or [click here](https://sql.telemetry.mozilla.org/queries/51023/source#136895)):
```sql
with sample as (
    select 'a' as x, -1 as foo union
    select 'b' as x, 0 as foo union
    select 'c' as x, 1 as foo union
    select 'd' as x, 10 as foo union
    select 'e' as x, 100 as foo union
    select 'f' as x, 1000 as foo union
    select 'g' as x, 10000000000 as foo union
    select 'h' as x, 1000 as foo union
    select 'i' as x, 1000 as foo union
    select 'j' as x, 1000 as foo union
    select 'k' as x, 1000 as foo union
    select 'l' as x, 1000 as foo union
    select 'm' as x, 1000 as foo union
    select 'n' as x, 1000 as foo union
    select 'o' as x, 1000 as foo
)
select * from sample
```

Then create a chart with the `x` field on the x axis, the `foo` field on the y axis, configure the x axis as categorical, and set the y axis to logarithmic scale.

I would expect the Y axis to scale up to 10,000,000,000 (where x = 'g'), but instead the Y axis scales only to 10,000 and truncates the bar for `g`:
<img width="1200" alt="screen shot 2018-02-09 at 2 19 34 pm" src="https://user-images.githubusercontent.com/969479/36043095-84bf406c-0da4-11e8-9ef1-61829d02354b.png">

### Technical details:

* Redash Version:
* Browser/OS: Firefox Nightly 60.0a1 (2018-02-09) (64-bit) / macOS High Sierra
* How did you install Redash: sql.telemetry.mozilla.org

**Comment by mreid-moz** [comment]
As a workaround, you can manually enter a Max Value for the Y-axis.

**Comment by washort** [comment]
Looks like this is a `plotly` version issue. Upgrading my local deployment to the version used upstream fixed the problem for me.

**Comment by washort** [comment]
This works on stage, which uses the up-to-date plotly version.

**Comment by madalincm** [comment]
Verified as fixed in FF59(Win7) in stmo-stage
Postfix screencast:
![334](https://user-images.githubusercontent.com/15685441/38089554-82b43b58-3368-11e8-9d58-1b360354a343.png)
Marking bug as verified fixed.
