### ISSUE TITLE
Download dataset link broken until query is saved

### ISSUE THREAD

**Issue by georgf** [mozilla/redash#335]
- Start new query
- enter "describe main_summary"
- execute
- try downloading results as csv or excel

Results:
- links point to "<blah>/undefined/<blah>"

Once i save the query it's working.

**Comment by emtwo** [comment]
I am unable to reproduce this issue in my local dev build and on staging. I can successfully download query results for unsaved queries.

**Comment by emtwo** [comment]
This should be resolved in prod now

**Comment by madalincm** [comment]
Issue is no longer reproducing. Verified as fixed in FF59(win7) in stmo-stage and stmo-prod
