### ISSUE TITLE
data in re:dash embedded url link doesn't match data in re:dash

### ISSUE THREAD

**Issue by jtanumijaya** [mozilla/redash#337]
I think I found a bug with regards to re:dash embedded link.

This chart was created with a daily update:
https://sql.telemetry.mozilla.org/queries/1597?p_days=30#2842

And we use the embedded url link to show the chart in MDC:
https://sql.telemetry.mozilla.org/embed/query/1597/visualization/2842?api_key=af950aef5751c0184d6557c6d0649a872c338a83

However, there's a different in the two charts: 1. chart in re:dash is updated up to Feb 11, 2018 2. the chart in the embedded link is only up to Apr 11, 2017. Do we have to do anything to refresh the embedded link to be the same as the original chart?

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by washort** [comment]
This is how sharing a single visualization works - it references a single result, and doesn't change when new results are created. For something that keeps up with changes, sharing a dashboard with that visualization should work.
