### ISSUE TITLE
Allow dates formatted as YYYYMMDD to be displayed as a datetime

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#338]
### Issue Summary

Mozilla uses YYYYMMDD date format in a bunch of places, primarily in our representation of "submission date". When used on the x-axis of a chart, the system defaults to interpreting it as a datetime (see #228). The resulting chart *almost* works, but requires a change to categorical before data will be displayed properly. In contrast to #228, we could actually interpret these values as dates to make things work with the default settings, we would need to detect and parse them differently.

### Steps to Reproduce

1. Create a query with a YYYYMMDD-formatted date field ([example here](https://sql.telemetry.mozilla.org/queries/50014#135495))
2. Create a chart with this field on the X-axis
3. Observe the broken date handling when YYYYMMDD strings are treated as Datetime (the default)
4. Change the X-axis scale to "category"
5. Observe that the X-axis looks normal.

Note the current workaround is to re-format the data as "YYYY-MM-DD", which *is* interpreted as expected.

**Comment by mreid-moz** [comment]
Can we make it work as expected only when you explicitly pick "Datetime" Scale representation? That doesn't currently work either, and leaving the default representation as is would avoid problems with other 8-digit numeric strings (which I would expect to use some other representation, I usually use "Category" as a workaround, but could imagine Linear/Logarithmic being useful).

**Comment by rafrombrc** [comment]
That might be possible... we'll look into it.

**Comment by emtwo** [comment]
Progress here: https://github.com/getredash/redash/pull/3150

**Comment by emtwo** [comment]
Confirmed that this is now fixed in stmo: https://sql.telemetry.mozilla.org/queries/50014/source#135495
