### ISSUE TITLE
[User Interview Results] Queries in Redash should have "reviewed" flag

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#341]
A reviewed query should be flagged as such and visible in the UI. This makes it easier for someone to both:
1. Trust the results of the query
2. Feel more comfortable forking the query to extend it

Additionally, it should be possible to search and filter queries by the "reviewed" flag.

**Comment by fbertsch** [comment]
Drive-by comment: The reviewer's name should be visible, along with the author's.

**Comment by arikfr** [comment]
@jezdez that's a really cool use case for tags! I would love to hear how it works for you in a few months.

**Comment by jezdez** [comment]
@emtwo @fbertsch So now that tags are part of the queries UI, I suggest to start discussing ways to use this, e.g. with tags like `reviewed:fbertsch` for example. Is there anyone who'd be interested in formalizing the workflow for STMO users?

**Comment by emtwo** [comment]
I think that this might integrate well with https://github.com/mozilla/stmocli. Since people are already using it to review queries, perhaps it can make an additional API call to add a tag to that query.

**Comment by rafrombrc** [comment]
Closing this since it's now something that can be done w tags and policy rather than a distinct feature.
