### ISSUE TITLE
Query results are truncated

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#342]
### Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/queries/273/source
2. Execute the query and observe the results

### Expected results:
The query results and the pagination are correctly displayed.

### Actual results:
The results are truncated and the user is not able to see all the results and the results navigation

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7) Issue can be reproduced in STMO-stage

![uichangesresultstruncated](https://user-images.githubusercontent.com/15685441/36673888-0e6fd4f0-1b0d-11e8-841b-4b2b07d59c89.gif)

**Comment by washort** [comment]
@arikfr This is occuring upstream as well, not sure what the best long-term fix is so I just removed the fixed-layout behavior for now.

**Comment by arikfr** [comment]
Fixed in getredash/redash#2363.

**Comment by washort** [comment]
Upstream fix now on stage.

**Comment by madalincm** [comment]
This is no longer reproducing. Scroll bars are displayed and the user can use them to see all the results. Closing bug and marking as verified fixed.
