### ISSUE TITLE
Layout issue with the format button

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#343]
### Steps to Reproduce:
1. Open new query page: https://pipeline-sql.stage.mozaws.net/queries/new
2. Hover inside the the section where the query is written and observe the layout

### Expected results:
The format button is displayed correctly (there is a padding between the autocomplete checkbox and the format button, the button contains the "format" string)

### Actual results:
There is no padding between the autocomplete checkbox and the format button, the button does not contain the "format" string

### Notes/Issues:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
![uichangesformatbuttonlayoutissue](https://user-images.githubusercontent.com/15685441/36734394-0dd4b6da-1bdc-11e8-8b7a-6e9e4d6a19f2.png)

**Comment by alison985** [comment]
This is no longer reproducible upstream or on https://pipeline-sql.stage.mozaws.net/.

**Comment by madalincm** [comment]
The issue is no longer reproducing. Marking bug as verified fixed.
