### ISSUE TITLE
Y-axis is mislabeled / data is misleading

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#347]
### Issue Summary

In a stacked bar graph, the Y-axis labels do not match the actual data values, resulting in a visualization that is incorrect (too high) by an order of magnitude.

### Steps to Reproduce

1. Visit [this example graph](https://sql.telemetry.mozilla.org/queries/50773/source#136224)
2. Un-select everything but the "ROW" series
3. Observe the scale on the Y-axis compared to the hover-over value (or compare with the "table" view of the data)
4. See that the Y-axis shows the data ~10x larger than it really is.

**Comment by rafrombrc** [comment]
Similar in some ways to #334, these should both be kept in mind when digging in to this code.

**Comment by emtwo** [comment]
Dug into this a bit and noticed that if the x-axis scale is changed from `Category` to `Datetime` this issue disappears.

**Comment by emtwo** [comment]
This issue seems to be resolved upstream. Here is an example of a simplified query that reproduces the issue:

https://sql.telemetry.mozilla.org/queries/52016#138869

Running this query:
```
WITH sample as (
    select '2018-02-18' as x, 'US' as type, 574047 as foo union
    select '2018-02-18' as x, 'ROW' as type, 8215767 as foo)
select * from sample
```
 The issue is still reproducible on http://demo.redash.io but not with a fresh checkout of this repo.

**Comment by rafrombrc** [comment]
Seems to be resolved by upgrading plotly dependency.

**Comment by mreid-moz** [comment]
I'm still seeing this issue in the query linked in the initial summary - do you know when a fix will be deployed?

**Comment by rafrombrc** [comment]
Yes, sorry... 'closed' means the fix is merged and deployed on staging, ready for confirmation (or not) by QA. We *might* see this pushed to prod this week, but more likely will be next week.

**Comment by mreid-moz** [comment]
Cool, thanks!

**Comment by madalincm** [comment]
Verified as fixed in FF59(Win7) in stmo-stage
Postfix screencast:
![347](https://user-images.githubusercontent.com/15685441/38090290-d4edfd6c-336a-11e8-9529-6ed0de1dcca5.png)

Marking bug as verified fixed.
