### ISSUE TITLE
Dashboards should have owners

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#353]
If we gave dashboard owners:
 - People who look at dashboards would know who to talk to about it
 - We could have a "My Dashboards" page (gah! I just want to see the dashboards I created!)

**Comment by jezdez** [comment]
Great idea, let's move this upstream though since it'd definitely touch the data model and a lot of frontend code to land this.

**Comment by jezdez** [comment]
To clarify, we store already owners of dashboards, so this doesn't have to touch the data model only representation layer (showing owner in UI, adding filter to dashboard list).

**Comment by rafrombrc** [comment]
We've got a PR open upstream (getredash/redash#2934) that will display the owner on the dashboard page, and have opened an issue (getredash/redash#3059) and will soon open a PR to add 'my dashboards' as a filter on the dashboards page.

**Comment by jezdez** [comment]
https://github.com/getredash/redash/pull/2934 has been merged 🎉
