### ISSUE TITLE
New Alert button is not displayed in the alerts page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#354]
### Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/alerts

### Expected results:
A button to create a new alert is displayed.

### Actual results:
The "New Alert" button is not displayed. 

### Notes/Issues:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Verified in FF58(Win7).  Issue can be reproduced in STMO-stage
The user is able to create a new alert from the "Create" drop down menu
Screencast for this issue:
![nonewallertbutton](https://user-images.githubusercontent.com/15685441/38097138-3e35ce46-337d-11e8-96b1-6382b5d2ca1a.png)

**Comment by emtwo** [comment]
@madalincm could you please specify where this expected button should be? I see a button to create an alert in the "create" dropdown. Should there be one somewhere else? Thanks!

**Comment by madalincm** [comment]
A button is displayed in the create drop down menu but I think the users will have a problem finding it in there as in the old UI it used to be in the top right corner. 

This i probably not a bug as the button was intentionally, I think,  removed from the new UI but old users will have issues finding it in the drop down menu. In my opinion we should make it easier to find.

**Comment by alison985** [comment]
@rafrombrc Given this is a UI issue and this won't exist upstream, do we still want to do this?

**Comment by alison985** [comment]
@jezdez Same question I asked Rob above: Given this is a UI issue and this won't exist upstream, do we still want to do this?

**Comment by jezdez** [comment]
@alison985 Oh, interesting, I agree this is not needed since this was a distinct UX decision upstream that we should not try to diverge from. The cost of maintenance is currently (we don't have an extension API for frontend customizations) too high and I haven't seen bug reports from users about it either. I'd say we close this and revisit if we get specific feedback about it from our users. What do you think?

**Comment by alison985** [comment]
I agree with closing it. Thanks.
