### ISSUE TITLE
The autocomplete checkbox can't be unchecked

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#355]
### Steps to Reproduce:
1. https://pipeline-sql.stage.mozaws.net/queries/new
2. Click on the "Autocomplete" checkbox

### Expected results:
The autocomplete feature is turned off.

### Actual results:
Nothing happens, the autocomplete feature can't be turned off.

### Notes/Issues:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Verified in FF59(Win7).  Issue can be reproduced in STMO-stage

**Comment by washort** [comment]
Moved the checkbox next to the query format button.

**Comment by madalincm** [comment]
the checkbox is still in the same place in stmo stage and the issue is still reproducing. Reopening.
