### ISSUE TITLE
Graphs are squashed with new redesign

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash#359]
The new redesign of Redash is very nice!  But some graphs are getting squashed and are difficult to read now, example:

https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-experiment-57-release

![screenshot 2018-04-03 15 30 11](https://user-images.githubusercontent.com/119884/38271286-0fd225a6-3754-11e8-8f86-54ec994a56c1.png)

I think it's because the X axis labels aren't being truncated so the graph is being smushed.

**Comment by washort** [comment]
Looks like the X axis on this visualization is set to "Category" scale - does it look right if you change it to "Datetime"?

**Comment by emtwo** [comment]
Yes, changing to "Datetime" resolves this particular issue. However I do still think it's a regression because the x-axis used to truncate before.

Though one thing to note is that specific x-axis datetime issues should be resolved/reduced with this PR: https://github.com/mozilla/redash/pull/365
