### ISSUE TITLE
Schema refresh is not working for Athena data source

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#370]
### Steps to Reproduce:
1. Open https://pipeline-sql.stage.mozaws.net/queries/new or https://sql.telemetry.mozilla.org/queries/new
2. Select Athena as data source and click on the refresh schema button

### Expected results:
The schema is refreshed.

### Actual results:
The tables are no longer displayed, the following error message is displayed: "Schema refresh failed. Please try again later."

### Notes/Issues:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Verified in FF59(Win7).  Issue can be reproduced in STMO-stage and STMO-prod
Screencast for this issue: 
![schemarefresh](https://user-images.githubusercontent.com/15685441/38683109-6313df2a-3e75-11e8-8768-95aabb2e905b.gif)

**Comment by alison985** [comment]
@jasonthomas The Athena connection on https://pipeline-sql.stage.mozaws.net/ is setup to use the glue data catalog (and doesn't have access to the information_schema schema). Can you confirm that a) the Athena connection there has access to Glue and b) there is a schema for the datasource for it to grab?

**Comment by jasonthomas** [comment]
> a) the Athena connection there has access to Glue 

Yes, we are using the 'AmazonAthenaFullAccess' Policy which includes access to Glue https://docs.aws.amazon.com/athena/latest/ug/access.html

> b) there is a schema for the datasource for it to grab?

There are two tables in the database ```stmo```: ```churn``` and ```containers_testpilottest```. 

Querying the glue catalog directly returns a schema:


```
aws glue get-table --database-name stmo --name churn
{
    "Table": {
        "PartitionKeys": [
            {
                "Type": "string",
                "Name": "week_start"
            }
        ],
        "StorageDescriptor": {
            "OutputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat",
            "SortColumns": [],
            "InputFormat": "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
            "SerdeInfo": {
                "SerializationLibrary": "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe",
                "Parameters": {
                    "serialization.format": "1"
                }
            },
            "BucketColumns": [],
            "Parameters": {},
            "SkewedInfo": {
                "SkewedColumnNames": [],
                "SkewedColumnValueLocationMaps": {},
                "SkewedColumnValues": []
            },
            "Location": "s3://telemetry-parquet/churn/v2",
            "NumberOfBuckets": -1,
            "StoredAsSubDirectories": false,
            "Columns": [
                {
                    "Type": "string",
                    "Name": "channel"
                },
                {
                    "Type": "string",
                    "Name": "geo"
                },
                {
                    "Type": "string",
                    "Name": "is_funnelcake"
                },
                {
                    "Type": "string",
                    "Name": "acquisition_period"
                },
                {
                    "Type": "string",
                    "Name": "start_version"
                },
                {
                    "Type": "string",
                    "Name": "sync_usage"
                },
                {
                    "Type": "string",
                    "Name": "current_version"
                },
                {
                    "Type": "bigint",
                    "Name": "current_week"
                },
                {
                    "Type": "string",
                    "Name": "source"
                },
                {
                    "Type": "string",
                    "Name": "medium"
                },
                {
                    "Type": "string",
                    "Name": "campaign"
                },
                {
                    "Type": "string",
                    "Name": "content"
                },
                {
                    "Type": "string",
                    "Name": "distribution_id"
                },
                {
                    "Type": "string",
                    "Name": "default_search_engine"
                },
                {
                    "Type": "string",
                    "Name": "locale"
                },
                {
                    "Type": "string",
                    "Name": "is_active"
                },
                {
                    "Type": "bigint",
                    "Name": "n_profiles"
                },
                {
                    "Type": "double",
                    "Name": "usage_hours"
                },
                {
                    "Type": "double",
                    "Name": "sum_squared_usage_hours"
                },
                {
                    "Type": "bigint",
                    "Name": "total_uri_count"
                },
                {
                    "Type": "double",
                    "Name": "unique_domains_count_per_profile"
                }
            ],
            "Compressed": false
        },
        "Parameters": {
            "transient_lastDdlTime": "1493229005",
            "EXTERNAL": "TRUE"
        },
        "LastAccessTime": 0.0,
        "TableType": "EXTERNAL_TABLE",
        "Owner": "hadoop",
        "Name": "churn",
        "CreateTime": 1493229005.0,
        "Retention": 0
    }
}

```

**Comment by rafrombrc** [comment]
@jasonthomas to get dev athena credentials to @alison985 so she can do some testing to make sure this is resolved before merging and pushing to staging.

**Comment by jasonthomas** [comment]
@alison985 Can you generate a GPG key so I can send the credentials to you securely? Steps here https://mana.mozilla.org/wiki/display/SD/Generating+a+GPG+Public+Key

**Comment by alison985** [comment]
@jasonthomas  done

**Comment by jasonthomas** [comment]
Sent credentials via email.

**Comment by alison985** [comment]
@jasonthomas The connection is working (I can run a query and get results), but I'm not sure if the Glue piece is set up the same. Could there be an IP restriction on accessing Glue?

**Comment by jasonthomas** [comment]
No there isn't any IP restriction here.

I tested the provided credentials against AWS Glue APIs and it returns information.

For example returns a valid response:

```
import boto3
client = boto3.client('glue')
response = client.get_table(DatabaseName='stmo', Name='churn')
print response
```

You could also validate it by using aws cli `aws glue get-tables --database-name stmo`

**Comment by alison985** [comment]
So I went down many paths with this but it is actually fixed upstream already: https://github.com/getredash/redash/issues/2400

**Comment by madalincm** [comment]
Verified as fixed in FF60(Win7) in stmo-stage
Postfix screencast:
![athenaschemarefresh](https://user-images.githubusercontent.com/15685441/41108614-b0e98068-6a7d-11e8-9245-9369e8c15db1.gif)

**Comment by jezdez** [comment]
@mreid-moz This is now deployed to prod!

**Comment by mreid-moz** [comment]
Woot! Thanks for the heads up!
