### ISSUE TITLE
"Manage Permissions" is not responsive

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#373]
It takes several tries and/or a bit of waiting for a dropdown of users to show up when I click on "Manage Permissions" for a query

**Comment by jezdez** [comment]
I've filed https://github.com/getredash/redash/issues/2495 since that seems like a legitimate bug upstream.

**Comment by jezdez** [comment]
This was fixed upstream in https://github.com/getredash/redash/pull/2715.

**Comment by madalincm** [comment]
Issue is no longer reproducing in STMO-Rc
Marking bug as verified fixed.
