### ISSUE TITLE
Redash visualizations not rendering for some number types

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#374]
Here are two examples of graphs that did not work until the columns were cast to varchar:

https://sql.telemetry.mozilla.org/queries/47041/source#127382
https://sql.telemetry.mozilla.org/queries/52474#139768

**Comment by tdsmith** [comment]
Thanks!

**Comment by madalincm** [comment]
Verified as fixed in FF59(win7) in stmo-stage using the test queries from https://github.com/mozilla/redash/pull/378

Marking bug as verified fixed.

**Comment by jezdez** [comment]
@emtwo 🙏 🏆 🎉
