### ISSUE TITLE
Visualization not rendering correctly

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#375]
Viz in question: https://sql.telemetry.mozilla.org/queries/15435#38316

The two lines are plotting essentially the same numbers, yet are _way_ apart (the top one is off from what the values are on the axis). Does re:dash think the top line is for the right y-axis? The viz was not setup like that, and the settings don't say that either.

**Comment by alison985** [comment]
@fbertsch I forked your query here: https://sql.telemetry.mozilla.org/queries/53975/source#142831 In the DAU visual which incorrect the settings have it as "stacked" in the DAU 2 visual the Stacking setting is disabled and the graph displays appropriately. Can you confirm this resolves the issue for you?

**Comment by fbertsch** [comment]
@alison985 it does! Thanks!
