### ISSUE TITLE
Feature Request: Allow to Define a Default for {{variables}}

### ISSUE THREAD

**Issue by davismtl** [mozilla/redash#38]
I use {{variables}} frequently in my queries however the browser often forgets them so I need to keep re-entering them. Or if Re:Dash remembered queries, they are likely no longer valid.

Also, if I schedule the queries to run weekly, I don't know what variables they will use or if the schedules will even work.

User Story:
As a user, I would like to be able to define a default value for my query variables.

For example, if my variable is a date, I would like to define that default is today's date - 30 days.
This brings us up to par with most data tools that have date pickers that default to last 30 days.

**Comment by arikfr** [comment]
You can set a default value -- if you have a value set for the parameter, when saving the query, then this value will be used as default.

Scheduling doesn't work for queries with parameters. Although in theory we can use the default value here.

**Comment by davismtl** [comment]
Any best practice to set the default value of a date to be **today** or today -30? These are typical default start and end dates.

Use case: I often define date ranges in my queries and if the query remembers the last date entered, then it would it hard to schedule the query to refresh in the future.

**Comment by arikfr** [comment]
Unfortunately nothing for this :( One thing you can do is to have # of days in as parameter, for example:

`current_date - {{days}}`

So by default you can have 0 or 30 there. But that's an ugly workaround.

**Comment by davismtl** [comment]
I use that work around for a lot of my charts in my dashboard but then it makes it hard to just go look at a past period like the month of November.

Any chance we turn this issue into a feature request?

**Comment by rafrombrc** [comment]
Sure, we triage new issues from this tracker every Friday, if you repurpose the title to describe the ask more clearly we'll slot it in to our schedule.

**Comment by davismtl** [comment]
Done. I renamed the issue.

**Comment by rafrombrc** [comment]
Looking back through this conversation, there are actually two separate issues that have been surfaced:

1. We'd like to be able to use "current_date" as a default parameter
2. We'd like to be able to have scheduled queries use a default parameter just like non-scheduled queries can.

I've opened #43 and #44 to capture these requirements, am closing this issue.

**Comment by davismtl** [comment]
@rafrombrc 
Would your #2 include if no value is defined, default to X? Where X could be a date, string or int/float.

Examples: default to "release". Or default to version "51.1". Or default to value greater than "5" bookmarks.

**Comment by rafrombrc** [comment]
If I'm understanding you correctly, that's exactly what I'm saying. Right now you can do this with non-scheduled queries, simply by setting the parameter value and then saving the query. You can't do it with scheduled queries, however, and issue #43 captures that feature request.

**Comment by davismtl** [comment]
Perfect! thanks!
