### ISSUE TITLE
Add ability to search table column names in schema browser 

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#380]
This is tracking the upstream feature https://github.com/getredash/redash/issues/2484 which was requested in bug [1376458](https://bugzilla.mozilla.org/show_bug.cgi?id=1376458).

**Comment by alison985** [comment]
@jezdez There are no comments on this issue upstream. Should I @ people in the issue upstream, continuing waiting, or something else?

**Comment by jezdez** [comment]
@alison985 @'ing people that deal with UI changes would make most sense, yeah.

**Comment by alison985** [comment]
Upstream is good with us submitting a PR for this.

**Comment by alison985** [comment]
I currently have it working to search table or search column, but I can't get both searches working at the same time.

**Comment by alison985** [comment]
@jezdez I have this working!!! 🎈 🎉 

The problem is now the CodeClimate report. I got the Cognitive Complexity down from 10 to 6, but that's still higher than 5 and the function is 30 lines not 25 or under. Thoughts?

**Comment by jezdez** [comment]
YEAH YEAH YEAH!

I've opened https://github.com/getredash/redash/issues/2727 to track the issue of the too strict Code Climate Analysis configuration.

**Comment by alison985** [comment]
@jezdez Since in our latest Wednesday team meeting you said to not let CodeClimate errors get us caught up, is https://github.com/getredash/redash/pull/2681 something you can do a review on?

**Comment by jezdez** [comment]
Merged upstream in getredash#2681 \o/
