### ISSUE TITLE
Queries can be forked only from the their source page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#383]
### Steps to Reproduce:
1. Open a query page (i.e: https://pipeline-sql.stage.mozaws.net/queries/348#418)
2. Click on the options button
3. Click on the fork button

### Expected results:
The query can be forked

### Actual results:
The query can't be forked

### Notes/Issues:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Verified in FF59(Win7).  Issue can be reproduced in STMO-stage and STMO-prod
The query can be forked from the source page (i.e: https://pipeline-sql.stage.mozaws.net/queries/348#418)

**Comment by jezdez** [comment]
FWIW, this is broken on prod as well, so no blocker for m13.2.

**Comment by madalincm** [comment]
Closing a bug sends me a signal that the fix is available to be verified. So yeah, I think it is better to keep it open for now

**Comment by jezdez** [comment]
@alison985 As I said above, this was fixed upstream already, no need to have a separate and different fix in our fork.

**Comment by madalincm** [comment]
Verified as fixed in FF60(Win7) in stmo-stage
Postfix screencast: 
![forkquery](https://user-images.githubusercontent.com/15685441/41107272-b6c106e4-6a7a-11e8-9560-fbb1382e3efb.gif)
