### ISSUE TITLE
re:dash Search is responding slowly

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#385]
Steps to reproduce:
1. Search for just about anything in the top right

Expected result: Timely search results

Actual results: Waiting for at least 30 seconds

**Comment by jezdez** [comment]
I suppose that is closely related to #384 and it smells like the search vector column wasn't populated for some reason. My best guess it happened during a deploy where the rebased migrations weren't applied fully.

**Comment by jezdez** [comment]
I've opened https://github.com/getredash/redash/pull/2566 with the appropriate fixes.

**Comment by jezdez** [comment]
@emtwo @washort Would you mind taking a look at the PR upstream?

**Comment by jezdez** [comment]
This was merged upstream.
