### ISSUE TITLE
re:dash search shows no results while search is running

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#386]
Steps to reproduce:
- Search for something

Expected Results:
- The search is obvious that it's searching

Actual Results:
- The results show no `No results found`, which is terribly confusing, because it doesn't know if it's found results yet.

Screenshot: https://screenshots.firefox.com/aDlrgDSLp85o7r8f/sql.telemetry.mozilla.org

**Comment by jezdez** [comment]
Seems like a bug in upstream, could you file one there please?

**Comment by fbertsch** [comment]
On it.

**Comment by fbertsch** [comment]
@jezdez https://github.com/getredash/redash/issues/2493

**Comment by jezdez** [comment]
@fbertsch Thanks!

**Comment by rafrombrc** [comment]
This should be resolved when the upstream "discovery branch" gets merged, leaving this open to track the issue until that happens and the upstream fix is merged into our repo and our deployment.

**Comment by jezdez** [comment]
https://github.com/getredash/redash/pull/2573

**Comment by jezdez** [comment]
This was fixed in getredash#2573.
