### ISSUE TITLE
Cannot search for dashboards in new UI

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#39]
I cannot lookup `Activity Stream` dashboards. The tag is not listed on the left and search is returning nothing. Is there something in the UI I'm missing?

Screenshot below

Browser: Firefox Nightly 54

<img width="1680" alt="screen shot 2017-02-17 at 12 08 12 pm" src="https://cloud.githubusercontent.com/assets/784781/23075384/39063210-f50a-11e6-985c-e508df86d8e0.png">

**Comment by rafrombrc** [comment]
Just did a quick check, looks like a search for "activity" gives results, but "Activity" doesn't give any results, which is not how this should behave. Digging in, more soon.

**Comment by arikfr** [comment]
https://github.com/getredash/redash/pull/1612

**Comment by arikfr** [comment]
& https://github.com/getredash/redash/commit/2e751b3dadfd47f1729ddcf7eeff12a192c530c0

**Comment by rafrombrc** [comment]
This fix has been deployed and the issue seems to be resolved. :)
