### ISSUE TITLE
Change draft visibility

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#4]
Having all new queries be in draft state until explicitly set to public (see #3) will help remove a lot of noise from the signal, but also means that a lot of useful query examples will not be available to anyone who wants to reuse or learn from them. It would be nice to have an option (or maybe always?) have draft queries still visible in the search results, but clearly marked as such and shown separately from the public queries.

**Comment by washort** [comment]
https://github.com/getredash/redash/pull/1353
