### ISSUE TITLE
npm deprecation warnings when building docker image

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#404]
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm WARN deprecated mapbox-gl-supported@1.2.0: This package has been moved to @mapbox/mapbox-gl-supported
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by jezdez** [comment]
This seems easy to fix and should definitely land upstream.

**Comment by alison985** [comment]
@jezdez  Agree this *sounded* easy, but is actually a hard-to-track dependency tree. Here's someone else's issue https://github.com/plotly/react-plotly.js/issues/38 where they were told it's not worth updating them for some of the same warnings. Can we agree to close this ticket?

**Comment by jezdez** [comment]
@alison985 Sure, no need to fix deprecation warnings if there is no easy way forward, especially when it's a second or third level dependency. Plus, we can cross the bridge when the deprecation warning turns into an error. Thanks for checking it out nevertheless!

**Comment by arikfr** [comment]
I think they are being a bit lazy about this, because these deprecation warnings been around for a long time... but there isn't much we can do about this. 🤷‍♂️ 

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

This one is actually our own dependency, in case you want to take a stab at it.
