### ISSUE TITLE
funky data source selection for queries

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#406]
Data source seems to stick to a user instead of to a query.

**Comment by jezdez** [comment]
Could you elaborate what you're seeing specifically?

**Comment by jezdez** [comment]
@alison985 Is this a valid issue after we've merged the recent upstream?

**Comment by alison985** [comment]
Good news! This is not reproducing on https://pipeline-sql.stage.mozaws.net/ now, @jezdez.

**Comment by jezdez** [comment]
@alison985 YAY!!
