### ISSUE TITLE
unarchive a query

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#409]
There doesn't currently seem to be a way to unarchive a query. Since this could be selected accidentally, it seems like a feature worth adding. Otherwise you have to copy and paste the query to a new redash query.

**Comment by jezdez** [comment]
This should be filed upstream since it's definitely a feature worth adding but not Mozilla specific.

**Comment by alison985** [comment]
for future reference: https://discuss.redash.io/t/unarchive-a-query/1987
