### ISSUE TITLE
Percent Stacking Doesn't Look Correct

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#41]
Here's an example chart where this looks off:
https://sql.telemetry.mozilla.org/queries/653#1092

Current Behaviour: When hovering over the graph, any given section is listed as <= 0.01% and I'm not sure what this is a percent of.

Expected Behaviour: The graph should behave like before where the percent is determined relative to other values grouped onto the same x-axis value

**Comment by rtestard** [comment]
I hit this issue too on several of my graphs, would be great to get it fixed since it's breaking existing graphs shared through dashboards.

**Comment by spasovski** [comment]
PR https://github.com/getredash/redash/pull/1696 opened.
