### ISSUE TITLE
All re:dash graphs in Mozilla Data Collective no longer render correctly

### ISSUE THREAD

**Issue by hcrince** [mozilla/redash#42]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

Within the Mozilla Data Collective, all re:dash iframed content no longer is displayed.  It renders the following error message.
![image](https://cloud.githubusercontent.com/assets/22621016/23277623/637f78b8-f9c3-11e6-9062-a175fb801799.png)

Here is an direct example of a piece of content within the Data Collective:
https://www.mozdatacollective.com/extcontent/index/index/element/389/name/Firefox+MAU%2C+Smoothed+DAU%2C+ER

We checked the api_key for the specific report directly in re:dash and there was no change to any of the elements within the embed link.  Here is the link to the embedded report in re:dash: https://sql.telemetry.mozilla.org/queries/1687#2994

Please advise what may have changed that we need to consider to make the embedded re:dash charts work again.

**Comment by arikfr** [comment]
Fixed among many other things here: https://github.com/getredash/redash/pull/1607.

**Comment by rafrombrc** [comment]
As Arik says, this is already resolved upstream, and in fact should already be resolved in our codebase as well. We hope to have this code deployed and the issue resolved within the next few hours.

**Comment by rafrombrc** [comment]
Okay, the deployment has happened, and it looks like the Data Collective embeds are working again... I can see the embedded graph on the page linked above, anyway. I'll poke around a bit more to see if I find anything wonky, but I'm closing this issue, please reopen or file another if you find any other non-parameterized embedded graphs not working.
