### ISSUE TITLE
Port using unpublished queries in alerts to upstream

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#429]
Allow unpublished queries to be used as alerts (#97, PR: 101)

This is tracked on https://github.com/mozilla/redash/projects/3

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2660

**Comment by alison985** [comment]
@jezdez Just wanted to flag that the feedback on the PR upstream is essentially that it won't get merged upstream. Please advise on next steps.

**Comment by jezdez** [comment]
Okay, so I agree with Arik's arguments to be honest, and don't know how big of a feature this really is.

We'll have to wait for Rob to come back to maybe give some insight why this was added in the first place since the original ticket (#97) doesn't really say what the user story specifically was. My gut says this was a early-day issue of not having good progress/experience for maintaining queries inside Mozilla.

So the next steps are:

1. Ask Rob about context
2. Depending on the result of discussion either:
a) remove the feature completely
b) move the feature to redash-stmo (our extension package) 

Option 2b) is currently blocked by the missing ability to override only parts of the frontend extension, and we can't monkey patch the API endpoint of the Query search to always include drafts since it would mean breaking other API endpoint usages. All in all IMO not worth the effort.

**Comment by alison985** [comment]
@rafrombrc Could you please comment with context?

**Comment by rafrombrc** [comment]
Sheesh... I don't remember all of the details here. I *think* it was simply that we had some folks showing up in the channel confused about why they couldn't see their queries and use them in dashboards and alerts.

I personally don't think there's any reason why a user shouldn't be able to use their own queries in dashboards, whether or not they're published for public discovery, but if they won't merge it upstream there's not much we can do about it. I'm guessing that this isn't something that could be easily moved to an extension, so we have to decide whether or not we want to continue to maintain this feature in our fork

**Comment by madalincm** [comment]
We recently had a similar bug logged https://github.com/mozilla/redash/issues/449

Maybe a quick fix would be to display an warning message that not published queries can't be used in dashboards/alerts. In this way at least people would be informed why they are not able to use their queries.

**Comment by alison985** [comment]
I agree with @madalincm, moving to Ready.

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2765

**Comment by emtwo** [comment]
Working is continuing here: https://github.com/getredash/redash/pull/3347

**Comment by emtwo** [comment]
https://github.com/getredash/redash/pull/3347 is now merged upstream!
