### ISSUE TITLE
Scheduled queries should support default parameters

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#43]
If you save a queries that contains parameterized values, whatever values are set for those parameters will be used by default when that query is executed in the future. Unfortunately, this only works when the queries are run by hand, and not when the queries are automatically run via the scheduler. We'd like to extend this default parameter support to automatically scheduled queries.

**Comment by davismtl** [comment]
When will this be made available and how can I find out how to use this feature?

**Comment by rafrombrc** [comment]
This should be working on production now. I believe you can use it by a) creating a query, b) specifying some parameterized variables in the query, c) using the query source page to set the query parameters to the desired default values, d) saving the query, and e) specifying an execution schedule for the query. Please let me know if you have any issues with this.
