### ISSUE TITLE
Port partition key marker (Athena/Presto) to upstream

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#430]
Add partition key marker to Athena and Presto columns (#185, PR: #201)

This is tracked on https://github.com/mozilla/redash/projects/3

**Comment by alison985** [comment]
upstream PR https://github.com/getredash/redash/pull/2655

**Comment by alison985** [comment]
Revised PR https://github.com/getredash/redash/pull/2764

**Comment by alison985** [comment]
Next steps:
* Extend query runner base class to include hook (method) that can be used to design the output of the schema browser, per query runner type.
* Improve UX with icon not [P]

**Comment by alison985** [comment]
upstream PR: https://github.com/getredash/redash/pull/2826
Has a Javascript problem with autocomplete at the moment.

**Comment by rafrombrc** [comment]
We've decided to retract the upstream PR because this functionality can be rolled into the bigger schema browser improvements that Marina is currently  working on. We'll still keep this implementation in our fork until that lands.
