### ISSUE TITLE
Port moving events to server side to upstream

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#433]
Move all possible events serverside (#245, PR: #246)

Upstream issue: https://github.com/getredash/redash/issues/1501

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2661

**Comment by alison985** [comment]
Now needs a rebase.

**Comment by alison985** [comment]
revised PR https://github.com/getredash/redash/pull/2766

**Comment by jezdez** [comment]
Merged in https://github.com/getredash/redash/commit/34e39eda4a02916380b47c1e20849a372926e083.
