### ISSUE TITLE
Port ability to add a query to a dashboard from query page to upstream

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#434]
add ability to add query to dashboard from query page (#154, PR: #184)

Upstream issue: https://github.com/getredash/redash/issues/955

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2656

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2767

**Comment by jezdez** [comment]
Merged in https://github.com/getredash/redash/commit/8a50351520067fc3af6593263d8e1cc376292443.
