### ISSUE TITLE
The value corresponding to the x axis is not displayed when hovering over a chart

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#437]
### Steps to Reproduce:
1. Open this queries:
 https://data-stmo-rc.stage.mozaws.net/queries/4#5
 https://data-stmo-rc.stage.mozaws.net/queries/5#7
2. Hover over the chart

### Expected results:
When hovering over the chart the x value is displayed.

### Actual results:
Only the y value and the "group_value" are displayed

### Notes/Issues:
Verified in FF60(Win7). Issue can be reproduced in STMO-stage and STMO-RC
Screencast for this issue:
Line Chart:
![barchartxvaluemissing](https://user-images.githubusercontent.com/15685441/41717189-93811c4a-7561-11e8-9864-75b9f45b21fb.png)
Bar Chart:
![barchartxvaluemissing1](https://user-images.githubusercontent.com/15685441/41717230-b1e21afe-7561-11e8-94d6-03174a394d3a.png)

**Comment by madalincm** [comment]
Probably a regression from #395

**Comment by jezdez** [comment]
@madalincm Good catch, I can't seem to figure out how to fix this properly.

@alison985 I've reopened #395 just to make sure we follow up and think about a different solution (including closing as wontfix).

**Comment by jezdez** [comment]
This has been fixed by reverting #395 and is on release.

**Comment by madalincm** [comment]
The value is correctly displayed now. I have checked it in RC, Stage and Production
Marking the bug as verified fixed.
