### ISSUE TITLE
Datasources in Admin Status area represented as JSON document which is hard to read

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash#438]
### Steps to Reproduce

1. Visit https://data-stmo-rc.stage.mozaws.net/admin/status under General > Datasources 

### Expected results:

Not sure but maybe each datasource represented as row with corresponding state

### Actual results:

JSON document with Datasource state that overruns the viewable browser window with value:
'{"1":{"metadata":{"name":"Athena"},"queries":{"SELECT 1":{"last_run":1529574174.805765,"last_run_human":"2018-06-21 09:42:56","runtime":1.3036999702453613,"status":"SUCCESS"}},"status":"SUCCESS"},"2":{"metadata":{"name":"ActiveData"},"queries":{"SELECT 1":{"last_run":1529574176.121393,"last_run_human":"2018-06-21 09:42:56","runtime":null,"status":"FAIL"}},"status":"FAIL"},"3":{"metadata":{"name":"Query Results"},"queries":{"SELECT 1":{"last_run":1529574176.127106,"last_run_human":"2018-06-21 09:42:56","runtime":0.0005691051483154297,"status":"SUCCESS"}},"status":"SUCCESS"},"4":{"metadata":{"name":"ATMO"},"queries":{"SELECT 1":{"last_run":1529574176.130685,"last_run_human":"2018-06-21 09:43:16","runtime":null,"status":"FAIL"}},"status":"FAIL"},"5":{"metadata":{"name":"JSON URL Fetcher"},"queries":{"null":{"last_run":1529574196.288481,"last_run_human":"2018-06-21 09:43:16","runtime":null,"status":"FAIL"}},"status":"FAIL"},"6":{"metadata":{"name":"authenticated url test"},"queries":{"null":{"last_run":1529574196.194579,"last_run_human":"2018-06-21 09:43:16","runtime":null,"status":"FAIL"}},"status":"FAIL"},"7":{"metadata":{"name":"Redash Metadata"},"queries":{"SELECT 1":{"last_run":1529574196.197925,"last_run_human":"2018-06-21 09:43:16","runtime":0.08725690841674805,"status":"SUCCESS"}},"status":"SUCCESS"}}'

**Comment by jasonthomas** [comment]
![screenshot-2018-6-20 athena](https://user-images.githubusercontent.com/910992/41720953-6c6a7b44-7519-11e8-8567-366c05120c5f.png)

**Comment by jasonthomas** [comment]
![screen shot 2018-06-21 at 6 08 12 am](https://user-images.githubusercontent.com/910992/41720980-80929bec-7519-11e8-83b7-2a292eee3bc7.png)

**Comment by jezdez** [comment]
This is an issue in redash-stmo, so I've created a ticket there, https://github.com/mozilla/redash-stmo/issues/11

**Comment by emtwo** [comment]
Closing this as the redash-stmo issue here: https://github.com/mozilla/redash-stmo/issues/11 and commit to update to it here https://github.com/mozilla/redash/commit/6f4bfdbc6f0a62c91c3186a4c3b61c12f4d8dadb have been merged:

**Comment by madalincm** [comment]
Verified in FF66(Win7) in STMO-RC
Issue no longer reproducing:
![image](https://user-images.githubusercontent.com/15685441/55159545-f11aeb80-5169-11e9-8a08-47a9b0e61467.png)
