### ISSUE TITLE
Add support for 'current_date' as a default parameter

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#44]
It's possible to use static values as default parameter values in queries, but we have a need to use predefined variables such as 'current_date' as well.

**Comment by washort** [comment]
Since parameters are just done by string substitution, you can just put `now()` or any other SQL expression as a value for a parameter.

**Comment by arikfr** [comment]
Brilliant :)

One downside: you can't use the date picker in this case.

**Comment by rafrombrc** [comment]
@davismtl Does this solution (i.e. using `now()` as the default parameter) satisfy the use case that you're interested in?

**Comment by davismtl** [comment]
Yeah, I think it'll resolve a lot!
