### ISSUE TITLE
m15 upstream rebase

### ISSUE THREAD

**Issue by washort** [mozilla/redash#447]
M15 rebase
==========

Proposed new history at https://github.com/mozilla/redash/tree/m15-rebase

Rewrote "add ability to add query to dashboard from query page (re #154)" to work with new search
-------------------

Removed "Add navigation for tags in dashboard list (re #259)" since tags stuff was reworked upstream
-----------------------

Remove \'view full label (\#422)\' and \'Revert \"view full label (\#422)\"\'
-----------------------------------------------------------------------------

Remove \'change datasources sort from id to name (\#412)\'
----------------------------------------------------------

merged upstream

Remove \'319 remove menu line (\#414)\'
---------------------------------------

merged upstream

Documentation links for data sources (re \#6)
---------------------------------------------

Consolidation of:

-   Closes \#369: Correct datasource documentation link alignment.
    (\#394)
-   Expose data source version info in UI (re \#89)

\'Update redash-stmo. (\#360)\' consolidated into \'Install redash-stmo.\'
--------------------------------------------------------------------------

\'Don\'t delete latest query results (re \#363) (re \#35)\' consolidated into \'Aggregate query results (re \#35) (\#339)\'
---------------------------------------------------------------------------------------------------------------------------

\'fixup pie chart colors (fixes \#345)\' consolidated into \'change pie chart colors (re \#240)\'
-------------------------------------------------------------------------------------------------

Remove \'Migration that needs to be rolled back before landing \#339\'
----------------------------------------------------------------------

Toggle for query editor autocomplete (re \#282)
-----------------------------------------------

Consolidation of:

-   Closes \#368: Wrap Autocomplete and checkbox in span and pad.
-   move autocomplete checkbox next to format button (re \#282) (re
    \#355)

Rewrite \'change pie chart colors (re \#240)\'
----------------------------------------------

Rewrite changes to \`preparePieData\` in utils.js to fit upstream
changes.

allow x-axis label truncation (re \#249)
----------------------------------------

Consolidation of:

-   Closes \#359: Truncate x-axis by default.
-   Closes \#374: Truncating x-axis should be done to ticktext not x
    values.
-   Closes \#387: Only truncate \'category\' type labels.
-   Pad series text to be same length as x axis (re \#391) (\#392)

Rewrite \'add column type info to query runners (re \#152, \#23)\'
------------------------------------------------------------------

Upstream changed the postgres query

Remove \'make the enter button submit the form (re \#172)\'
-----------------------------------------------------------

fixed upstream

Remove \'dashboard textbox edit close fix (re \#111)\'
------------------------------------------------------

fixed upstream

add compare query version support (re \#7)
------------------------------------------

Consolidation of:

-   only show query versions when more than one exists (re \#194)
-   sort query version select options (re \#198)

Filter tables from schema browser (re \#31)
-------------------------------------------

Consolidation of:

-   works for filtering ~v~ literally (re \#31)
-   add toggle~tablestring~ (re \#130)
-   Filter versioned table names only (re \#130) (re \#356)

Upgrade to Celery 4.1.1
-----------------------

Consolidation of:

-   up celery version to fix kombu async error
-   upgrade to Celery 4.1.0

**Comment by washort** [comment]
@jezdez I'll force push this if it looks good to you.

**Comment by jezdez** [comment]
@washort Can you indicate in the diff the reasons for the removal and which are squashed?

**Comment by washort** [comment]
Branch updated, detailed changelog above

**Comment by washort** [comment]
master now updated. Added a couple more items to the top of the changelog as a result of rebasing onto upstream.
