### ISSUE TITLE
Schema viewer has poor performace w lots of tables

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#45]
Our main 'presto' data source has a lot of archived tables, which cause the schema browser to be very slow when trying to scroll or filter through the set of available tables. We have #31 open to have the archived tables be hidden by default, but it might be possible to improve the schema browser performance even without #31 being completed.

**Comment by arikfr** [comment]
How many tables are we talking about?

**Comment by rafrombrc** [comment]
Looks like we're approaching 300 tables in this source.

**Comment by arikfr** [comment]
300 isn't that much, but how many columns they have?
