### ISSUE TITLE
Refresh schedule is reset if the dashboard page is refreshed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#452]
### Steps to Reproduce:
1. Open any dashboard (i.e: https://data-stmo-rc.stage.mozaws.net/dashboard/134123412341234)
2. Click on the refresh drop down mene and select any time interval (i.e 1 hour)
3. Refresh the page

### Expected results:
The refresh schedule remains to what the user have set.

### Actual results:
The button returns to the original state

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage, RC and prod
![dashboardrefresh](https://user-images.githubusercontent.com/15685441/42696272-6006ee7e-86c0-11e8-91cd-554df2cb0766.gif)

**Comment by jezdez** [comment]
Having opened https://github.com/getredash/redash/issues/2688 I'm going to close this here.
