### ISSUE TITLE
Port accommodating '/' in dashboard tags

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#453]
Refs #48 (e.g. be89d48f)

**Comment by alison985** [comment]
@jezdez The variable name `TAGS_REGEX` and some distinctive parts of the string don't exist in /client/app/ or /redash/ directories. I believe this is part of tag related things that Arik is working on right now. I'm going to mark this as blocked and we can test to make sure / are allowed in tags after those changes are merged upstream.

**Comment by alison985** [comment]
Slashes work for me locally now that we have merged upstream with the tags code.

![screenshot 2018-08-12 17 57 44](https://user-images.githubusercontent.com/1840865/44007354-490dd4e8-9e59-11e8-9069-9ebfed75dad6.png)
