### ISSUE TITLE
Port making autocomplete for large schemas faster

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#454]
Refs #232 (5eaa9663)

**Comment by alison985** [comment]
PR upstream: https://github.com/getredash/redash/pull/2746

**Comment by jezdez** [comment]
This has been made moot as discussed in https://github.com/getredash/redash/pull/2746#discussion_r216154344 since getredash#2764 requires more UX work than just adding the a prefix. As such, we'll need to revisit considering making the search faster later when we get to working on this. I'm closing this ticket for now since this only was created to cover the idea of a direct 1:1 port.
