### ISSUE TITLE
Data Source type doesn't show up when there's no doc link

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#46]

**Comment by alison985** [comment]
In use: Presto, Redshift, Postgres, Athena.  Display sql dialect and link to sql documentation for any variant in query builder. Want to specify dialect whether there is a doc link or not.

**Comment by alison985** [comment]
https://github.com/mozilla/redash/pull/85

**Comment by madalincm** [comment]
The data source for Athena (Direct) is displayed even is not a link for any documentation. For Redash Metadata is also displayed. This are the only 2 which are displayed in stage, the rest of the verification will be done when the fix hits production.
