### ISSUE TITLE
Port toggle for query editor autocomplete

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#460]
Refs #282 (0604760f)

This should be done in coordination with https://github.com/getredash/redash/issues/2644 since that adds a button next to the Save/Execute buttons below the query editor since Arik said there: "If this finalizes at the final design, we can also place the "Format Query" button there (along with a toggle for autocomplete)."

**Comment by alison985** [comment]
PR Upstream https://github.com/getredash/redash/pull/2780

**Comment by jezdez** [comment]
Merged in https://github.com/getredash/redash/commit/588e0cce43d27faa8b8196ac0d4cc5c8ed7c36e4.
