### ISSUE TITLE
Investigate porting "Use saved values for parameters in scheduled queries"

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#461]
Refs #43 (a7b4f46e)

Investigate only since it seems as if the commit related to that issue only contains a test and the issue doesn't clearly state that this was an existing feature that just wasn't clear how to use.

Ironically https://github.com/getredash/redash/issues/2644 is working on this right now so it'd e splendid if we could donate that test (if it makes sense) to that.

**Comment by alison985** [comment]
Adding test passes in the upstream master branch from ~10 days ago, so I went ahead and made a PR to add it to upstream. https://github.com/getredash/redash/pull/2802

**Comment by jezdez** [comment]
Huzzah! Merged in upstream 👍
