### ISSUE TITLE
 Disable SQL auto-complete by default

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#464]
To quote @harterrt in [1477317](https://bugzilla.mozilla.org/show_bug.cgi?id=1477317):

> The SQL formatter in re:dash should not be enabled by default. It disagrees with the SQL style guide and is generally more harmful than helpful in my experience.

**Comment by harterrt** [comment]
I would still argue to remove the autosuggest functionality. For example typing `SELECT<enter>` gets autocompleted to `select`

**Comment by jezdez** [comment]
FTR we use the [sqlparse](http://sqlparse.readthedocs.io) library to do the reformatting, if you can match the style to the [provided options](http://sqlparse.readthedocs.io/en/latest/api/#formatting-of-sql-statements), sure it's possible to match it. Otherwise this would need to be replaced with something else.

I should note, this feature is planned to be ported upstream, so any solution would require a non-NIH approach.

**Comment by fbertsch** [comment]
Should we split the concern of the auto-complete and it's relation to SQL formatting into a separate issue?

**Comment by tdsmith** [comment]
It looks like autocomplete is provided by Ace and it reuses the syntax highlighting rules in https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/sql_highlight_rules.js#L39-L43 to suggest keywords.

**Comment by harterrt** [comment]
I'm fine with splitting this issue but my primary concern is with the autosuggest functionality. Sorry for the unclear description (and grumpy tone). 

The SQL formatter only triggers when clicked so it's not an issue for me. The autocomplete is on by default and does interfere with my workflow. As noted above, the autocomplete appears to prefer lower-cased keywords and makes distractions suggestions even when typing variable names.

For example, in this query I'm trying to filter on `submission_date` but after typing `sub` I get a suggestion to autocomplete to the function `days_ago`.
![submission-date-autocomplete](https://user-images.githubusercontent.com/193826/43110712-947ec700-8ebb-11e8-82bc-6df2a136d48c.png)

It would be better if this functionality was off by default.

**Comment by harterrt** [comment]
@jezdez What do you think about turning the auto-complete off by default?

**Comment by harterrt** [comment]
Friendly ping.

**Comment by jezdez** [comment]
@harterrt Whoops, missed this last week! 👐 

Yes, let's turn auto-complete off by default.

Also I was wrong in my [earlier comment](https://github.com/mozilla/redash/issues/464#issuecomment-406704818) and @tdsmith was correct, I simply confused formatting and auto-completion. Sorry!

**Comment by jezdez** [comment]
I've updated the title to better match what @harterrt wants.

BTW, I should note, since the default for the auto-complete is something that is set in the upstream repo (despite us having the additional fork feature of the autocomplete toggle) we'll have to consult with upstream to solve this by introducing a config value there to fully get this done.

**Comment by harterrt** [comment]
Hey all, just checking in on this. Do we have an ETA for when this may be turned off by default?

Thanks!

**Comment by jezdez** [comment]
Hey @harterrt, no estimate since it'll require changes upstream and we've been working on a related change in https://github.com/getredash/redash/pull/2746.

If you think this is urgent, we can make an exception and add the feature in our fork, but since we're trying to move changes in our custom fork upstream it would make sense to do that only if it's a blocker for your workflow. I hadn't read your issue so far with that scope, apologies in case that happened.

**Comment by jezdez** [comment]
@alison985 Do you think you could add this feature to https://github.com/getredash/redash/pull/2746?

**Comment by harterrt** [comment]
Thanks, @jezdez. I agree we should solve this upstream. It's an annoyance, but not worth maintaining it in the fork. I only pinged this thread to make sure the issue doesn't slip through the cracks.

When should I check back next? 4 weeks?

**Comment by jezdez** [comment]
@harterrt Understood, thanks for understanding. 4 weeks sound like a good timebox.

**Comment by alison985** [comment]
@jezdez Arik talks about local storage in https://github.com/getredash/redash/issues/2893 - Does that mean a cookie? Can you point me to where local storage is talked to in the code?

**Comment by alison985** [comment]
@jezdez Bumping up this question.

**Comment by jezdez** [comment]
@alison985 I think he refers to the web storage backend [`window.localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) which is a web platform technology key/value-store available in all major browsers.

**Comment by alison985** [comment]
@washort I think I'm running into a React difference. What's the React equivalent of $watch that we're using? A quick google shows multiple npm modules, and our package.json doesn't list one.

**Comment by rafrombrc** [comment]
Well, we have good news and bad news about this ticket. The bad news is that this particular effort to fix up auto-complete is being scrapped. The good news is that this effort has prompted the following decisions:

* Whether or not autocomplete is turned on will become a user preference that will be available on a per-user basis shortly after getredash/redash#3026 is merged (relevant discussion in getredash/redash#2984).

* Autocomplete will be getting a ground up overhaul in the upstream redash soon, tracked in getredash/redash#3067.

* Upstream will soon merge one of our band-aid fixes to autocomplete that helps minimize the performance issues: getredash/redash#3079.

**Comment by alison985** [comment]
@rafrombrc @jezdez For getredash#3079 I'm not sure we want that in the codebase after Janni's comments [here](https://github.com/getredash/redash/pull/2746#discussion_r213405473) when I tried to port it before.
