### ISSUE TITLE
Searching a keyword should include the same results as clicking the keyword

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#47]
When I search "Activity Stream" I don't get all of the dashboards with the "Activity Stream" tag. I've attached 2 screenshots. One with what a search looks like, and one with the tag clicked.

<img width="1680" alt="screen shot 2017-03-06 at 12 22 50 pm" src="https://cloud.githubusercontent.com/assets/784781/23621276/f960ef86-0267-11e7-8b29-35b535e33b02.png">
<img width="1680" alt="screen shot 2017-03-06 at 12 23 07 pm" src="https://cloud.githubusercontent.com/assets/784781/23621279/fd05274c-0267-11e7-88d0-c61557358149.png">

Is this intentional? It seems counter-intuitive to me.

**Comment by washort** [comment]
The intent is for search to only apply to the non-tag part of the title, and for selecting a tag to narrow the search to dashboards with that tag. So, yes, this is intentional.

**Comment by rafrombrc** [comment]
Closing this bc as Allen says this is intentional behavior. The real issue is #48, which we're in the process of resolving.
