### ISSUE TITLE
Query tables are not correctly added to a dashboard from the query page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#472]
### Steps to Reproduce:
1. Open a query page: https://pipeline-sql.stage.mozaws.net/queries/388/source#478
2. Click on the plus button next to the "Table" text
3. Search for a dashboard and add the query to that dashboard
4. Open the dashboard where you added the query: https://pipeline-sql.stage.mozaws.net/dashboard/testdashboardtoaddquery

### Expected results:
The query was added to the dashboard and is correctly displayed

### Actual results:
The query is added to the dashboard the the table is empty.

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
Please view this screenshot
![queryaddedtodashboard](https://user-images.githubusercontent.com/15685441/43463542-7cac5ae4-94e1-11e8-8f76-73550c329306.png)

**Comment by washort** [comment]
Looks like this is just a default-size issue. Resizing the widget displays all the data (and in your screenshot there's a scrollbar on  the widget)

**Comment by madalincm** [comment]
When you add a query directly from the dashboard the behavior is different: The query table is correctly displayed. 
As a user if you use the feature to add the query directly from the query page you will have to do an extra step which is to go to that dashboard and resize the the widget so data is correctly displayed. 

In conclusion there are 2 different behaviors when doing the same action from 2 different places which in my opinion is a bug.
