### ISSUE TITLE
Footer overlaps other elements in pages that contain page navigation

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#473]
### Steps to Reproduce:
 - Open all queries page: https://pipeline-sql.stage.mozaws.net/queries?page=1
or
- Open all dashboards page: https://pipeline-sql.stage.mozaws.net/dashboards?page=1

### Expected results:
The page footer is correctly displayed

### Actual results:
The page footer is overlapping some page elements

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
This issue appears to be reproducing in all the pages that include a page navigation and where the footer is displayed.
Probably a regression from the work done on page navigation #322 
Please view this screenshot:
![footeroverlap](https://user-images.githubusercontent.com/15685441/43463948-81c7f7b2-94e2-11e8-8792-35b041514c23.png)

**Comment by washort** [comment]
Fixed upstream in https://github.com/getredash/redash/commit/b0f0b49d1cadac960d400872eefe419d2e31a9e5

**Comment by emtwo** [comment]
This one is kind of nasty, I wonder if we should temporarily add the fix as a commit until we do another full merge?

**Comment by madalincm** [comment]
Verified as fixed in STMO-RC in FF61(win7 x64).
Closing and marking as verified fixed.
