### ISSUE TITLE
Tags section is not displayed in My queries page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#475]
### Steps to Reproduce:
1. Open all queries page: https://pipeline-sql.stage.mozaws.net/queries?page=1
2. Select My Queries from the right side menu
3. Observe tags section

### Expected results:
Tags are displayed. The user is able to filter own queries by tags

### Actual results:
The tags section is not displayed.

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
Please view this screencast:
![notagssectionmyqueries](https://user-images.githubusercontent.com/15685441/43466446-389027c6-94e8-11e8-88e5-957c1e531fcc.gif)

**Comment by rafrombrc** [comment]
If this is (as we suspect) missing upstream as well, let's open a PR for this upstream and not block our release on this one.

**Comment by alison985** [comment]
Issue opened upstream by @jezdez https://github.com/getredash/redash/issues/2828

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/3066

**Comment by alison985** [comment]
I closed PR https://github.com/getredash/redash/pull/3066 because the lack of tags on the My Queries page was intentional. The Tags API will need to be extended to support filtering the tags for both the My Queries page and query list search results.

**Comment by jezdez** [comment]
Since I've filed https://github.com/getredash/redash/issues/2828 upstream and this can be considered a general feature request I'm closing this ticket.

**Comment by madalincm** [comment]
The tags have been added to the My queries section. I have run some tests and everything seems to work ok. Marking bug as verified fixed.
