### ISSUE TITLE
Long tags cause page layout issues

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#476]
### Steps to Reproduce:
- Create a long tag and add it to a query
and
- Create a long tag and add it to a dashboard
- Open all dashboards page and observe the page layout:  https://pipeline-sql.stage.mozaws.net/queries
- Open all queries page and observe the page layout: https://pipeline-sql.stage.mozaws.net/dashboards?page=1

### Expected results:
There are no page layout issues

### Actual results:
The page is not correctly displayed

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
Please view this screencast:
![dashboardslongtags](https://user-images.githubusercontent.com/15685441/43467297-185c47f8-94ea-11e8-80b0-121b08940f0b.png)
![querieslongtags](https://user-images.githubusercontent.com/15685441/43467334-2c259f32-94ea-11e8-865f-9c6eb109e31e.png)

**Comment by jezdez** [comment]
Fixed in https://github.com/getredash/redash/pull/3006.

**Comment by madalincm** [comment]
The issue is no longer reproducing in STMO-rc
Marking as verified fixed.
