### ISSUE TITLE
There is no tag on the left for "Activity Stream A/B Testing"

### ISSUE THREAD

**Issue by emtwo** [mozilla/redash#48]
I assume the tags listen on the left are all coming from the term preceding a colon (:) in the dashboard title. So it's the same mechanism that was used to create the dashboard submenus prior to this change.

Based on this assumption, I would expect to find my "Activity Stream A/B Testing" tag available on the right but I don't see it.

Is my assumption correct about where those keywords are coming from? If not, how can I add dashboards under a certain keyboard?

**Comment by washort** [comment]
This is where the colon-separated keywords are pulled out: https://github.com/getredash/redash/blob/master/client/app/pages/dashboards/dashboard-list.js#L9

**Comment by rafrombrc** [comment]
We have a fix for this, deploying soon, turns out the regex for finding tags was blowing up on the "/" in your tag name. For now you can workaround by not using slashes in the tag part.

**Comment by alison985** [comment]
Verify that unicode upstream change and local / change didn't conflict.

**Comment by alison985** [comment]
Added back the / fix from this commit: https://github.com/alison985/redash/commit/c7eac5513ca8ac2fe11975ab09cca85d2514fc7a in this commit: https://github.com/alison985/redash/commit/2010969a3b3f607baa8898b4621718ab7154138d
