### ISSUE TITLE
No padding between the "unpublished" tag and the rest of the tags

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#480]
### Steps to Reproduce:
1. Open all queries page and click on the "rrrrrr" tag
2. Observe the query tags

### Expected results:
There are no display or layout issues.

### Actual results:
There is no padding between the unpublished tag and the rest of tags

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
Please view this screencast:
![paddingtags](https://user-images.githubusercontent.com/15685441/43528271-416ae114-95b1-11e8-86cb-c4ca1d3154cb.png)

**Comment by alison985** [comment]
In seeing if this was still upstream, I found another related issue which is that if you keep adding tags the table of queries expands horizontally behind the right sidebar.
![screenshot 2018-09-09 21 59 03](https://user-images.githubusercontent.com/1840865/45274162-b080ac80-b47b-11e8-8e16-88ce8cbd5fac.png)

**Comment by alison985** [comment]
PR upstream https://github.com/getredash/redash/pull/2803

**Comment by alison985** [comment]
We're now in this PR from kocsmy https://github.com/getredash/redash/pull/3006

**Comment by jezdez** [comment]
Fixed upstream!

**Comment by madalincm** [comment]
The issue is no longer reproducing in STMO-rc
Postfix screenshot: 
![nopadingfixed](https://user-images.githubusercontent.com/15685441/50228359-68ddbb00-03b0-11e9-82d2-1ef7a5e8765f.png)


Marking as verified fixed.
