### ISSUE TITLE
Order tags alphabetically

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#481]
### Issue Summary
Because all users are able to add tags we face the risk to have a large number of tags created. Displaying them in an inconsistent order will make finding the desired tag hard. Maybe it would most useful to order them alphabetically

### Steps to Reproduce:
1. Open all queries page or all dashboards page and observe the tags order

### Expected results:
The tags are ordered and the user is able to find the tag he wants easily 

### Actual results:
Tags are randomly displayed.

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage

**Comment by jezdez** [comment]
I'ved filed a ticket upstream, https://github.com/getredash/redash/issues/2819, to track this. I found the sort order to be wrong, showing the tags with the most items tagged to be last, not first.

**Comment by jezdez** [comment]
I've opened a PR in getredash#2833.

**Comment by jezdez** [comment]
This has been merged and released.
