### ISSUE TITLE
Unpublished queries can be added to dashboards from the query page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#482]
### Steps to Reproduce:
1. Open an unpublished query: https://pipeline-sql.stage.mozaws.net/queries/394/source#486
2. Click on the plus button next to the "Table" text
3. Search for a dashboard and add the query to that dashboard
4. Open the dashboard where you added the query: https://pipeline-sql.stage.mozaws.net/dashboard/dashboardunpublishedquery

### Expected results:
The query is not added to the dashboard.

### Actual results:
The query is added to the dashboard

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage

**Comment by emtwo** [comment]
I confirmed that you can still add published queries which is most important. This is currently a feature that only exists in stmo but is in the process of being ported upstream (https://github.com/getredash/redash/pull/2656) I left a note there so that this is taken into account during the port.

**Comment by alison985** [comment]
This is now part of this upstream PR: https://github.com/getredash/redash/pull/2767

**Comment by rafrombrc** [comment]
Made another request for review of the latest revisions, hope to see this merged v soon.

**Comment by alison985** [comment]
This was merged upstream.
