### ISSUE TITLE
Dashboard name can't be edited

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#483]
### Steps to Reproduce:
1. Open any dashboard page and try to edit the name

### Expected results:
Dashboard name can be edited

### Actual results:
The user is not able to change the dashboard name

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage, STMO-RC and STMO-prod

**Comment by emtwo** [comment]
@madalincm Are you referring to the fact that you can't edit the title in place by clicking on it? I think maybe this is because they changed the UI on purpose so that you need to open the dropdown on the right and click `edit` before in order to edit the title

**Comment by madalincm** [comment]
Yes that is the scenario. And also I think that you are right, this looks intentional as the title can be changed when in edit mode but giving the fact that this is different from how you do it for a query made me think that this would be a valid issue.

**Comment by rafrombrc** [comment]
Confirmed this is intentional behavior change.

**Comment by madalincm** [comment]
Based on the above comment marking this bug as invalid.
