### ISSUE TITLE
Refreshing a dataset throws an error

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#49]
### Issue Summary

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Window 7 64 Bit

### Steps to Reproduce
1. Open STMO page - https://sql.telemetry.mozilla.org/
2. Click on any query displayed under the Recent Queries section
3. Click on the Refresh query button

### Expected results:
The query is refreshed, the data set is displayed.

### Actual results:
The following error is displayed: Error running query: Should not have nextUri if failed

### Notes/Issues:
Verified in FF51 (Win7)  Issue can be reproduced in https://sql.telemetry.mozilla.org/
Screencast for this issue: https://www.screencast.com/t/B7UwE0Wsrl

**Comment by washort** [comment]
This is an error coming from the library Redash uses to talk to Presto: https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L254

Unfortunately this is an internal assertion hiding the real error message returned by Presto.

**Comment by rafrombrc** [comment]
I've just tried this with a couple of different queries using the 'Presto' data set on production and was unable to reproduce. Are you still seeing the error, @madalincm ?

**Comment by madalincm** [comment]
I have tried this again and I can't reproduce it in production but when I try it in stage the process never completes.  (Query in queue… 00:42:38)

**Comment by rafrombrc** [comment]
We've updated the stage deployment, can you test again and let us know if it's fixed?

**Comment by madalincm** [comment]
The issue is no longer reproducing in stage.
