### ISSUE TITLE
Refresh schedule form can’t be opened

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#50]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO page - https://sql.telemetry.mozilla.org/
2. Click on any query displayed under the Recent Queries section
3. Click on Refresh Schedule link

### Expected results:
The refresh schedule form is displayed.

### Actual results:
Nothing happens.

### Notes/Issues:
Verified in FF51 (Win7)  Issue can be reproduced in https://sql.telemetry.mozilla.org/
Screencast for this issue: https://www.screencast.com/t/QmWFNbj1q

**Comment by washort** [comment]
Appears to work in the current release.

**Comment by madalincm** [comment]
Verified as fixed in FF51 (Win7) in sql.telemetry.mozilla.org
Postfix screencast: 
![postfix51](https://cloud.githubusercontent.com/assets/15685441/24911750/bca2cdc4-1ed4-11e7-9b84-07bd56fcc206.gif)

Closing bug.

**Comment by washort** [comment]
I tested it in production; works for me in firefox 52 on linux. Really unsure what's going on there...

**Comment by madalincm** [comment]
Retested in production in Win 7, 10 (x64), Ubuntu 16.04 using FF Release and Nightly and I can reproduce the issue every time. I have checked the browser and the web console while reproducing but nothing relevant is displayed.

**Comment by madalincm** [comment]
I have tested the issue in stage and it appears to work.
![postfix50](https://cloud.githubusercontent.com/assets/15685441/25330522/986bc2da-28e8-11e7-9ea7-7b661d5ccc7c.gif)

Rechecked in production and I can still reproduce the issue.  Is there any fix pushed to stage for this issue?

**Comment by alison985** [comment]
Does not currently work on https://pipeline-sql.stage.mozaws.net/queries/7 for me, but does work on my local. I propose we re-test once the latest deployments are on staging.
