### ISSUE TITLE
M16 Rebase

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#503]
I've rebased on top of the recent Redash repo and pushed a m16-rebase branch to our fork repo:

https://github.com/getredash/redash/compare/master...mozilla:m16-rebase

### Commits removed

Because the features were fixed or ported upstream:

- accommodate '/' in dashboard tags (re #48)  https://github.com/mozilla/redash/commit/7d43c5ae21c65f5f43aeee03bcaa65712516bda7
- reject non-list dashboard layouts (re #25)  https://github.com/mozilla/redash/commit/31358be2f2e18f2dd19ab15c4238f56a51168b61
- Reject empty names for dashboards (re #76)  https://github.com/mozilla/redash/commit/d4813e4e7ec440ef9419a51162a9df64ac3b9a8f
- allow unpublished queries to be used as alerts (re #97) https://github.com/mozilla/redash/commit/cf7f8cf710ee1391b584e79be7a14e8e6e1b3559
- adding activedata query_runner (re #83) https://github.com/mozilla/redash/commit/c1f01d94a4c0c56e29e308c94a304bd43ebeb385
-  Re-prompt for login if an unauthorized Google account is used (fixes #79) https://github.com/mozilla/redash/commit/f33416ca9be3aeaec3b883ecf95180b8acae991c
- change pie chart colors (re #240) https://github.com/mozilla/redash/commit/db948e558d97456a2b3d903723bdcc3e85c0ef26 (https://github.com/getredash/redash/pull/2616)

# Commits combined

Since they were adding to the code churn

- all Circle CI and deploy specific changes
- datasource health extension commits (adding and removing)

**Comment by washort** [comment]
Looks great. r+

**Comment by jezdez** [comment]
woohoo!

**Comment by jezdez** [comment]
Reopening since there are a few bugs

**Comment by jezdez** [comment]
We've fixed the bugs that @madalincm reported in the m16-rebase branch and pushed it to release.
