### ISSUE TITLE
Schema refresh failed error displayed in create new query page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#505]
### Steps to Reproduce:
1. Open the create new query page: https://data-stmo-rc.stage.mozaws.net/queries/new
2. Select redash metadata as data source and click the refresh schema button

### Expected results:
Schema is refreshed.

### Actual results:
Schema refresh failed error is displayed

### Notes/Issues:
Issue is also reproducing for ATMO data source using the same steps. 
When using Athena data source the issue can be reproduced by pressing 2 or 3 times on the refresh data source button.
Verified in FF61(Win7 x64) issue can be reproduced in stmo-stage and stmo-rc
![schemarefreshfail](https://user-images.githubusercontent.com/15685441/44209407-12474280-a16c-11e8-82d6-5f35f0b47e0f.png)

**Comment by jezdez** [comment]
This commit seems to fail now for some reason: https://github.com/mozilla/redash/commit/13564e8fa6ba0403d5f7d11184900957644a3321

```
postgres_1  | ERROR:  syntax error at or near "t" at character 473
postgres_1  | STATEMENT:  
postgres_1  | 	        SELECT s.nspname as table_schema,
postgres_1  | 	               c.relname as table_name,
postgres_1  | 	               t.typname as column_type,
postgres_1  | 	               a.attname as column_name
postgres_1  | 	        FROM pg_class c
postgres_1  | 	        JOIN pg_namespace s
postgres_1  | 	        ON c.relnamespace = s.oid
postgres_1  | 	        AND s.nspname NOT IN ('pg_catalog', 'information_schema')
postgres_1  | 	        JOIN pg_attribute a
postgres_1  | 	        ON a.attrelid = c.oid
postgres_1  | 	        AND a.attnum > 0
postgres_1  | 	        AND NOT a.attisdropped
postgres_1  | 	        JOIN pg_type t
postgres_1  | 	        ON pg_type t
postgres_1  | 	        ON c.reltype = t.oid
postgres_1  | 	        WHERE c.relkind IN ('r', 'v', 'm', 'f', 'p')
postgres_1  | 	        

```

**Comment by jezdez** [comment]
In the pg.py query runner, that is

**Comment by jezdez** [comment]
This has something to do with the changes in https://github.com/getredash/redash/pull/2549 I think

**Comment by jezdez** [comment]
I've incorporated the #509 directly into the commit adding the feature.

**Comment by jezdez** [comment]
Merged into the m16-rebase branch and going out to release.

**Comment by madalincm** [comment]
or @washort  as @jezdez is on PTO :)

**Comment by jasonthomas** [comment]
> Yeah, looks like the ATMO data source might not be acessible by RC environment.

This should now be fixed.
