### ISSUE TITLE
Query search is not working when using the search box displayed in the page header/all queries page

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#506]
### Steps to Reproduce:
1. Open: https://data-stmo-rc.stage.mozaws.net/queries
2. Perform a search using the search box from the page header 

### Expected results:
The search is performed.

### Actual results:
The search is not performed.

### Notes/Issues:
Issue can be reproduced in FF61(Win7) in STMO-stage and STMO-RC
![searchnotworking](https://user-images.githubusercontent.com/15685441/44212830-1461cf00-a175-11e8-9f76-7c8913c3725c.gif)

**Comment by jezdez** [comment]
This is a bug from upstream and I filed a fix PR here: https://github.com/getredash/redash/pull/2750

**Comment by jezdez** [comment]
Merged upstream and into our m16-rebase branch, going out to release.

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7 x64) in stmo-rc
Postfix screencast:
![searchallqueriespage](https://user-images.githubusercontent.com/15685441/44263327-28660900-a227-11e8-942e-e18c0c5f212c.gif)
Marking as verified fixed.
