### ISSUE TITLE
Alerts can't be created

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#507]
### Steps to Reproduce:
1. Open the create new alert page: https://data-stmo-rc.stage.mozaws.net/alerts/new
2. Search for a query and add it to the alert

### Expected results:
The form to complete the alert details is displayed and the user can create the alert.

### Actual results:
The form is not displayed, the creation process can't be completed

### Notes/Issues:
Issue can be reproduced in STMO-RC. I have used
 this query in tests: https://data-stmo-rc.stage.mozaws.net/queries/68/source#84  To try to add it to an allert but it is not working. When trying to an identical query in stage the query can be added https://pipeline-sql.stage.mozaws.net/queries/397/source#489
![newalertnotworking](https://user-images.githubusercontent.com/15685441/44213919-92bf7080-a177-11e8-9595-c242b3af90b1.png)

**Comment by jezdez** [comment]
Another bug from upstream, with an PR no less: https://github.com/getredash/redash/pull/2741

Will merge there and rebase on top of it.

**Comment by jezdez** [comment]
I fixed this in the m16-rebase branch and it goes out to release.

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7 x64) in stmo-rc
Postfix screencast:
![newalertfixed](https://user-images.githubusercontent.com/15685441/44263107-53039200-a226-11e8-8fdd-0ce0cca9c065.png)
Marking as verified fixed.
