### ISSUE TITLE
Users page is empty

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#508]
### Steps to Reproduce:
1. Open this page: https://data-stmo-rc.stage.mozaws.net/users

### Expected results:
Users list displayed.

### Actual results:
Page is empty.

### Notes/Issues:
Issue can be reproduced in STMO-RC.
![userspage](https://user-images.githubusercontent.com/15685441/44218487-783ec480-a182-11e8-9daa-567266cdc473.png)

**Comment by jezdez** [comment]
This was a regression introduce when rebasing the rewritten user screen.

**Comment by jezdez** [comment]
Fixed in the m16-rebase branch and going out to release.

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7 x64) in stmo-rc
Postfix screencast: 
![userspagefixed](https://user-images.githubusercontent.com/15685441/44254308-17a79a00-a20b-11e8-84b3-4e935f893a2e.png)

Marking bug as verified fixed.
