### ISSUE TITLE
The embeded code window can’t be closed clicking the “x” button

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#51]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO page - https://sql.telemetry.mozilla.org/
2. Click on any query displayed under the Recent Queries section
3. Click on the embed button.
4. Click on the “x” buttton to close the pop-up window

### Expected results:
The pop-up window is closed

### Actual results:
The pop-up window is not closed.

### Notes/Issues:
Verified in FF51 (Win7)  Issue can be reproduced in https://sql.telemetry.mozilla.org/
Screencast for this issue: https://www.screencast.com/t/lWE0JIwNfrt

**Comment by washort** [comment]
Appears to be fixed in the current release.

**Comment by madalincm** [comment]
Verified as fixed in FF52 (Win7) in sql.telemetry.mozilla.org
Postfix screencast: 
![postfix51](https://cloud.githubusercontent.com/assets/15685441/24911750/bca2cdc4-1ed4-11e7-9b84-07bd56fcc206.gif)

Closing bug.
