### ISSUE TITLE
Query pages with parameters broken since last STMO deployment

### ISSUE THREAD

**Issue by kewisch** [mozilla/redash#517]
![image](https://user-images.githubusercontent.com/607198/44404492-426d5780-a557-11e8-9970-af208f878bea.png)

This is happening to me on e.g. https://sql.telemetry.mozilla.org/queries/4857?p_q_4857=guidhere since today, I heard there was a recent deploy.

I get `TypeError: "this.query is undefined"` in the error console, tested both in Firefox Nightly and Chrome.

**Comment by jezdez** [comment]
For the record, the query page is only broken if the has parameters, I've update the issue title accordingly.

**Comment by jezdez** [comment]
FWIW this was a regression introduced when recently rebasing our fork on top of the upstream Redash that led to breaking the feature introduced in #164. The commit in question that introduced the regression is 8c176cb7f9fa2636e9d993a5f17e21ad4abc084c.

**Comment by jezdez** [comment]
This will deployed very soon..

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7 x64) in stmo-stage
All the parameters types can be added to a query and the query page is no longer broken:
![queryparameters](https://user-images.githubusercontent.com/15685441/44412273-33939e80-a571-11e8-8e5a-6842c0112810.png)
Marking bug as verified fixed.

**Comment by jezdez** [comment]
Thanks @madalincm!
