### ISSUE TITLE
The user can’t log out from STMO

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#52]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO page - https://sql.telemetry.mozilla.org/
2. Click on your username displayed in top right corner and then on the Log out link.

### Expected results:
The user is successfully logged out.

### Actual results:
The page refreshes, the user is not logged out.

### Notes/Issues:
Verified in FF51 (Win7)  Issue can be reproduced in https://sql.telemetry.mozilla.org/
Screencast for this issue: https://www.screencast.com/t/6CIhCt48U

**Comment by rafrombrc** [comment]
Closing bc this is related to sql.t.m.o delegating auth back to our Google login. Not painful enough for us to tackle over the more pressing issues.
