### ISSUE TITLE
Landing page is empty

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/redash#546]
The landing page is currently empty when I load it:

https://screenshotscdn.firefoxusercontent.com/images/a604a8ec-4d7b-44d7-9df2-cbae34d4089d.png

Is this the desired behaviour?  It feels like it should be loading something but nothing shows up and I don't see any failed network requests?  If this is intentional then maybe it could show something else if there are no 'favorites', like existing dashboards.

**Comment by jezdez** [comment]
No, this has been fixed in the meantime upstream: https://github.com/getredash/redash/commit/93b34bcbce2b3df328e1c1fac4261fa83e8717b3

Once v5 is out we'll do another rebase (next week) and get those changes as well.
