### ISSUE TITLE
Presing “close” or  “x” button does not close the edit widget window.

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#55]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open a dashboard page that contains a text widget i.e. https://pipeline-sql.stage.mozaws.net/dashboard/test
2. Click on the option button and then on the edit button of the text box widget.
3. Click the “Close” or the “x” button.

### Expected results:
The window is closed.

### Actual results:
The window is not closed.

### Notes/Issues:
Verified in FF52(Win7).  Issue can be reproduced in STMO-stage and STMO-production
Screencast for this issue:
![textboxwidgetclose](https://cloud.githubusercontent.com/assets/15685441/24106978/3b597946-0d92-11e7-975b-1c9fc1f8c35e.gif)

**Comment by arikfr** [comment]
Fixed by https://github.com/getredash/redash/commit/6ff338964bd21115cbd493e7b6dc32b7aed8f0e9.

**Comment by madalincm** [comment]
Verified as fixed in STMO-stage FF52(Win7)
Postfix screencast: 
![postfix55](https://cloud.githubusercontent.com/assets/15685441/24502841/2f3c7870-1558-11e7-9ac3-f203104e7994.gif)

Closing bug.
