### ISSUE TITLE
Port adding column type info to query runners

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#564]
883c36bf66a1a410e841bf35363439266cbe5a07

#23, #152, PR: #173

**Comment by emtwo** [comment]
I think we can put this one on hold since the design might look a bit different and is being discussed here now: https://github.com/mozilla/redash/issues/376#issuecomment-386235023

**Comment by alison985** [comment]
Thanks for the comment @emtwo. I'm treating this as on hold for now.
