### ISSUE TITLE
Display issue for long info displayed on the x-axis of a chart

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#58]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open the following query: https://sql.telemetry.mozilla.org/queries/2054#3731
2. Observe the text displayed on x-axis.

### Expected results:
The text is correctly displayed.

### Actual results:
The text is truncated and is not correctly displayed.

### Notes/Issues:
Verified in FF52(Win7).  Issue can be reproduced in STMO-production.
Screencast for this issue:
![xaxistextissue](https://cloud.githubusercontent.com/assets/15685441/24157114/23e006b6-0e61-11e7-9437-d9b5a3f2a767.png)

**Comment by alison985** [comment]
After looking at a lot of javascript, there is already a built-in edit function for that part of the chart. If you have "Edit" privileges for the chart, and go to the X Axis tab of options in the Edit dialog and increase the height value, you can pick how many pixels the x axis labels get. Witness the example here: https://sql.telemetry.mozilla.org/queries/4879/source#9976 which I made by forking the original link.

**Comment by madalincm** [comment]
I agree with Alison. This functionality should be enough to avoid the display issues mentioned in the bug.
