### ISSUE TITLE
Port query version comparison in the front-end

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#583]
- #7: main feature (2a7c3541)
- #198: sort query version select options (ea7bcd0d)
- #194 only show query versions when more than one exists (508a9b74)

**Comment by alison985** [comment]
Ported here: https://github.com/StantonVentures/redash/tree/moz_583_query_versions tests pass and npm run build succeeds, but I have a funky error with the query testarea not showing more than 2 lines of code.

**Comment by alison985** [comment]
Made a WIP PR upstream to try to get help with the textarea issue. https://github.com/getredash/redash/pull/3021/

**Comment by rafrombrc** [comment]
This needs to be react-ified and then to integrate some design changes that have been requested to better match the rest of redash design. This is a good job for Davor to tackle when he returns next week.

**Comment by jezdez** [comment]
We've decided to deprecate the feature for now.
