### ISSUE TITLE
Implement Athena query runner

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#59]
This is sort of a feature request. Basically the current query_runner for Athena fails sometimes.

When running `SELECT * FROM telemetry.telemetry_core_parquet LIMIT 10`, re:dash errors with `Error running query: getArray`.

This can be fixed by using botocore in the query runner instead of the jdbc driver. See [0]. Also it looks like this is a known issue with the jdbc driver, and won't be fixed any time soon, see [1].

[0] https://github.com/robotblake/delphin/blob/master/run.py
[1] https://forums.aws.amazon.com/thread.jspa?threadID=246868&tstart=0

**Comment by washort** [comment]
New query runner: https://github.com/mozilla/redash/pull/61
