### ISSUE TITLE
React component of STMO is running in Dev mode

### ISSUE THREAD

**Issue by peterbe** [mozilla/redash#606]
It's not insecure but definitely slows down significantly.

**Comment by peterbe** [comment]
It's clearly built (bundled and minified) but it's missing the `NODE_ENV==production` or whatever it's called.

**Comment by washort** [comment]
Not sure where to locate this -- it seems to be built in production mode upstream (as seen on http://redash-preview.netlify.com/ ) and I don't see any changes to webpack or docker config in our fork that would change this. Is this an environment problem in our deploy system?

**Comment by peterbe** [comment]
"deploy system"?? Isn't the minified static asset bundles built before deployment? Perhaps it's word-pickery but in many of projects with React, the `yarn run build` step is run as part of the Docker build and then the generated minified assets are copied into the container. That means the docker image that is sent to dockerhub has the static assets within them.

**Comment by washort** [comment]
Ah, I see now. I've added the missing line to our webpack config.
