### ISSUE TITLE
Multiple failing tests

### ISSUE THREAD

**Issue by robotblake** [mozilla/redash#62]
Currently master is failing three different tests:

* `tests.models.test_changes:TestLogChange.test_logs_create_method` - unsure if this is still needed since it looks like we're intentionally not creating a Change entry on creation anymore
* `tests.test_models:QueryOutdatedQueriesTest.test_failure_extends_schedule` - this is due to some weirdness with the `ChangeTrackingMixin` and the `@listens_for` on `Query.query_text`
* `tests.test_cli:DataSourceCommandTests.test_interactive_new` - this test just hangs due to the addition "Documentation URL" field when running `./manage.py ds new`

This is currently blocking https://github.com/mozilla/redash/issues/30 as I can't verify any circle changes work while the tests are failing.

**Comment by robotblake** [comment]
Fix for `tests.test_models:QueryOutdatedQueriesTest.test_failure_extends_schedule`:

```diff
diff --git a/redash/models.py b/redash/models.py
index 885ffff6..cb438416 100644
--- a/redash/models.py
+++ b/redash/models.py
@@ -140,6 +140,9 @@ class ChangeTrackingMixin(object):
     skipped_fields = ('id', 'created_at', 'updated_at', 'version')
     _clean_values = None

+    def __init__(self, *a, **kw):
+        super(ChangeTrackingMixin, self).__init__(*a, **kw)
+
     def prep_cleanvalues(self):
         self.__dict__['_clean_values'] = {}
         for attr in inspect(self.__class__).column_attrs:
```

Fix for `tests.test_cli:DataSourceCommandTests.test_interactive_new`:

```diff
diff --git a/tests/test_cli.py b/tests/test_cli.py
index 97b65476..1abb3dfc 100644
--- a/tests/test_cli.py
+++ b/tests/test_cli.py
@@ -16,7 +16,7 @@ class DataSourceCommandTests(BaseTestCase):
         result = runner.invoke(
             manager,
             ['ds', 'new'],
-            input="test\n%s\n\n\nexample.com\n\ntestdb\n" % (pg_i,))
+            input="test\n%s\n\n\n\nexample.com\n\ntestdb\n" % (pg_i,))
         self.assertFalse(result.exception)
         self.assertEqual(result.exit_code, 0)
         self.assertEqual(DataSource.query.count(), 1)
```

**Comment by washort** [comment]
tests pass now.
