### ISSUE TITLE
Add timezone to query scheduling widget

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/redash#620]
![screenshot_2018-11-02 pollbot buildid uptake by channel](https://user-images.githubusercontent.com/953153/47934224-c2436680-dea4-11e8-851c-77ef3c78981c.png)

When scheduling queries using the time option, there's no indicator for what time zone you're setting the schedule for. It's local time, as I discovered by examining the request sent by my browser. The widget should be labeled with the time zone to avoid confusion.

**Comment by jezdez** [comment]
Yeah, good idea, but something we'll need to do upstream.

**Comment by jezdez** [comment]
Ooops, in fact this has been revamped upstream already and now looks like this:

<img width="469" alt="Screen-Shot-2019-04-05-10-14-25 92" src="https://user-images.githubusercontent.com/1610/55613744-b1688b00-578b-11e9-83a9-7515f6c3569d.png">

Fixed 💥
