### ISSUE TITLE
ctrl-space for autocomplete not working

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#625]
When the schema has too many tables automatic autocomplete stops working, Ctrl-space is supposed to invoke autocomplete anyway, but doesn't seem to be working in our fork.

**Comment by jezdez** [comment]
There is a new upstream ticket to track issues with autocomplete: https://github.com/getredash/redash/issues/2984

**Comment by jezdez** [comment]
And https://github.com/getredash/redash/issues/3067 for a v2 of autocomplete.

**Comment by arikfr** [comment]
If you want to fix this before updating to latest master, see my comment here: https://github.com/getredash/redash/issues/2707#issuecomment-438669778. It's a single line change to fix this.

**Comment by jezdez** [comment]
This has been fixed by rebasing on top of Redash v6.
