### ISSUE TITLE
Get Query Result data source working for everyone

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#629]
The query results data source is super useful and opens up a bunch of new use cases, but it's currently only available to a specific group, due to security concerns. We should resolve these security issues and get this rolled out to everyone.

**Comment by jezdez** [comment]
@jasonthomas Could you explain again the reasoning for limiting the query result data source to only a group of users? I'm trying to figure out if the [datasource](https://github.com/getredash/redash/blob/master/redash/handlers/query_results.py) is missing a feature or just has a bug.

**Comment by jasonthomas** [comment]
https://redash.io/help/user-guide/querying/query-results-data-source Note 3 is confusing to me and was my concern, specifically the part of regarding executing vs querying. I want to make sure that users that don't have access to a restricted data source cannot query results (using the Query Result Datasource) from queries associated with a restricted data source.

**Comment by rafrombrc** [comment]
Hrm. We'll need to do some testing to verify, but reading that carefully I think that means the following is true:

* A user can only create and execute a 'query results' query if they have access to the data sources for all of the underlying queries they are accessing. This is A Good Thing ®.

* If a user with access to a restricted data source creates and executes a query results query to access that data source, then anyone who has access to the query results data set will be able to *see* the output from the latest run. This isn't necessarily bad, but it is a footgun.

If I'm right, then that means it would be possible for someone w access to sensitive data to inadvertently expose that data to other STMO users by using a query results query carelessly. We could try to prevent this by training users who have access to sensitive data to never use query results queries against that data, but not sure if OpSec would go for that. Still, it's not as bad as what I think Jason was fearing.

Might be worth considering extending query results data source to explicitly exclude certain data sources, even if the user has access to that data source?

**Comment by washort** [comment]
https://github.com/mozilla/redash/pull/812 addresses this.
