### ISSUE TITLE
Date Variable Forces Today's Date

### ISSUE THREAD

**Issue by davismtl** [mozilla/redash#64]
### Issue Summary

When using a {{date_variable}} and defining the data type as **Date**, it auto-fills today's date but then prevents from changing it.

### Steps to Reproduce

1. Create a query with a date as a variable
2. Define variable as date format in the variable settings
3. Try to edit the date
4. Result: it always switches back to today's date

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

* Redash Version: Whatever version Mozilla is using on April 18th
* Browser/OS: Firefox 54

**Comment by arikfr** [comment]
Can you check if this happens on demo.redash.io? I think I might have fixed this on upstream.

**Comment by davismtl** [comment]
Looks good to me!

**Comment by davismtl** [comment]
(deleted last comment, I just checked the wrong thing)

I will test it out again.

**Comment by davismtl** [comment]
In the demo site, there are no longer settings for variables. It was only when I set the data type to a date format that the bug would happen.

**Comment by arikfr** [comment]
I just tried and can confirm that there are settings for parameters. You need to be on the source view (the one with the query).

**Comment by davismtl** [comment]
ok thx

**Comment by rafrombrc** [comment]
@davismtl Are your needs handled here? Is it safe for us to close this issue?

**Comment by davismtl** [comment]
I have not run into any problems lately. Thanks!
