### ISSUE TITLE
Favicon is gone

### ISSUE THREAD

**Issue by davismtl** [mozilla/redash#65]
For the last month, the favicon has disappeared from Re:Dash.

Pinned tabs look like: 
![image](https://cloud.githubusercontent.com/assets/19537086/25154607/2d5d1a9e-2446-11e7-933a-cc439bf212f9.png)

Regular tabs look like:
![image](https://cloud.githubusercontent.com/assets/19537086/25154627/43eb97fe-2446-11e7-9e1a-6f7d4aaad9ac.png)

This is not a blocker but just really annoying.

Sometimes, it's just the small things that make a big difference. ;)

**Comment by arikfr** [comment]
Fixed in upstream here: https://github.com/getredash/redash/commit/3c7c93fc9f09cfa17319aef14da3d23ec6e46641.

**Comment by davismtl** [comment]
Thanks
