### ISSUE TITLE
Request to enable web hook notifications on stmo

### ISSUE THREAD

**Issue by hwine** [mozilla/redash#674]
We (secops) would like to trigger actions based on redash alerts. 

AIUI, web hooks are a built in notification channel for alerts, but are not enabled in stmo.

If there's a good reason to have them not enabled, we can do a weird dance with AWS email -> sns. (I.e. this isn't blocking, but would make life easier for us)

**Comment by jasonthomas** [comment]
I am assuming that admins are only able to create alert destinations. We can configure webhook alert destination for you just let us know the details. 

We will need:
URL
Username (optional)
Password (optional)
