### ISSUE TITLE
mozlog format / logging 2.0

### ISSUE THREAD

**Issue by robotblake** [mozilla/redash#68]
We're working towards getting all apps we run to use our "Logging 2.0" centralized logging pipeline, as part of that process we configure the apps we run to use mozlog format.

There are a variety of different libraries that can be used if you search for "python mozlog" but I wonder if our best bet might be to extend the [python-dockerflow](https://github.com/mozilla-services/python-dockerflow) library that @jezdez made to include Flask support similar to its Django support.

**Comment by fbertsch** [comment]
+1 on Flask support, for python-dockerflow, then we can use it for python_mozaggregator as well!

**Comment by jezdez** [comment]
That reminds me to finish that branch, I have a half working Flask extension built. Will do next week.

**Comment by alison985** [comment]
Hi @jezdez, I wanted to follow up on the status of the Flask extension for python-dockerflow. I don't see a mention of it in the repo.

**Comment by alison985** [comment]
Spoke to @robotblake, removing from M7.

**Comment by jezdez** [comment]
I've started to work on Flask support in python-dockerflow [here](https://github.com/mozilla-services/python-dockerflow/pull/18)
