### ISSUE TITLE
Display "data scanned" when using AthenaDirect runner

### ISSUE THREAD

**Issue by robotblake** [mozilla/redash#69]
One of the things we'd like to be able to do when people run queries using the AthenaDirect runner is to display the amount of data that Athena scanned. The amount of data scanned lets us know how "expensive" a query is as well as giving a heads up that a query may not be as efficient as it could be.

This is supported by the boto + athena client using something like...
```python
qeid = '00000000-0000-0000-0000-000000000000'
result = client.get_query_execution(QueryExecutionId=qeid)
qbytes = result['QueryExecutionDetail']['Stats']['ProcessedBytes']
```

**Comment by alison985** [comment]
https://github.com/mozilla/redash/pull/99
