### ISSUE TITLE
Support version control for queries

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#7]
Users would like to be able to keep track of edits made to their queries, with the ability to see prior versions, to see diffs between versions, and to revert to earlier versions. Requiring an explicit action to save a version is acceptable. It seems reasonable to still use the database as the production source of the currently active query, rather than trying to load the query directly from whatever versioning mechanism is used.

**Comment by fbertsch** [comment]
Another interesting point brought up in bug 1315081 is, if we have a repo, one can put in a PR for a query.

**Comment by washort** [comment]
Backend support for this is in redash master now. All edits to queries and dashboards are saved to a `changes` table.

**Comment by spasovski** [comment]
- [ ] solve current version number being wrong (too high)
- [ ] CSS z-index cleanup (ideally by moving to Stylus)
- [ ] figure out proper place to wait for XHR API response

**Comment by rafrombrc** [comment]
Relevant: getredash#1550.

**Comment by rafrombrc** [comment]
Reopening bc there are JS errors preventing this from working correctly in production.

**Comment by madalincm** [comment]
This has been now pushed to production. We will log any new related issues as separated bugs. Marking this bug as verified fixed.
