### ISSUE TITLE
In visualization editor, "Please check your Internet connection" error message covers "Save" button.

### ISSUE THREAD

**Issue by groovecoder** [mozilla/redash#70]
### Issue Summary

In visualization editor, "Please check your Internet connection" error message covers "Save" button.

![redash-errors-covers-save](https://cloud.githubusercontent.com/assets/71928/25403185/2be7e57e-29c1-11e7-9f88-8d5d64bffe7b.png)

### Steps to Reproduce

1. Create/edit a visualization
2. Lose your internet connection (DDoS yourself ... or I guess just unplug your internet?)
3. The `toast.toast-warning` message element covers the save element

### Technical details:

* Redash Version: sql.telemetry.mozilla.org
* Browser/OS: Mac Firefox
* How did you install Redash: sql.telemetry.mozilla.org

**Comment by alison985** [comment]
If you either a) scroll over and then scroll off the message or b) click on the message it goes away. To do anything further would require forking the angular-toastr library. I double checked these findings with @spasovski.
