### ISSUE TITLE
Rearm seconds value is not maintained after creating a new alert

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#71]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Click the New alert button fill the form and click the save button

### Expected results:
All the information introduced in the creation form are kept after the save button is clicked

### Actual results:
Rearm seconds value is not maintained after the save button is clicked..

### Notes/Issues:
Verified in FF53(Win7).  Issue can be reproduced in STMO-stage and STMO-production.
Screencast for this issue:
![rearmseconds](https://cloud.githubusercontent.com/assets/15685441/25438800/30fc625a-2aa3-11e7-9cbc-17c6d3dc4a70.gif)

**Comment by alison985** [comment]
Addressed in PR #90.

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in stmo-stage
Postfix screencast:
![rearmsecvalue](https://user-images.githubusercontent.com/15685441/27450750-60b84742-5795-11e7-9df4-68fdb875a3da.gif)
