### ISSUE TITLE
All `Athena (Direct)` query failures give the same error message

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#72]
If an Athena query fails for any reason (whether there's a problem on the server side or the user fat fingers a table or field name) it always returns exactly the same error message:

"Error running query: Waiter QueryCompleted failed: Waiter encountered a terminal failure state"

It'd be great if there was any way to provide more useful feedback to the user.

**Comment by washort** [comment]
https://github.com/mozilla/redash/commit/6b7861319160b73310b3397ad630487a2e579805

**Comment by madalincm** [comment]
I have verified this in stage executing a query like: "select something from stmo.churn limit 20" The error I get is "Error running query: Waiter QueryCompleted failed: Waiter encountered a terminal failure state" when it should be something like "Error running query: column "something" does not exist.."

**Comment by madalincm** [comment]
I have re-verified this in stage and the error messages are looking good.
I have tried different scenarios for wrong/missing columns, tables, wrong syntax and everything looks good. 
I couldn't reproduce the condition to receive a failure from the server to see how the error messages are looking. @rafrombrc  any ideas on how can we do that?
