### ISSUE TITLE
`sampledb.elb_logs` table doesn't work

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#73]
The `sampledb.elb_logs` table in the Athena data source always returns an error. I'm told this is due to S3 permission issues, and that there's no easy way to get Athena to not show this table in the table list. Ideally all of the tables showing up in the schema would work.

**Comment by washort** [comment]
https://github.com/mozilla/redash/commit/0ad235aa1e3d0fda6782a3f65152718c9f83d837

**Comment by madalincm** [comment]
Running queries on sample.elb_logs down not work. I've tried queries like:
select request_ip from sampledb.elb_logs limit 20
select request_port from sample.elb_logs limit 20
and I get the same "Error running query: Waiter QueryCompleted failed: Waiter encountered a terminal failure state"

**Comment by madalincm** [comment]
Now when trying to execute the above queries the following error is displayed: "Error running query: Insufficient permissions to execute the query."

**Comment by madalincm** [comment]
The table is removed. Closing for now.
