### ISSUE TITLE
Not all fields in the `stmo.containers_testpilottest` table work

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#74]
If you run `select uuid, event from stmo.containers_testpilottest limit 20;` against the Athena data source the query will return, but if you run `select * from stmo.containers_testpilottest limit 20;` it will give an error. Apparently this is due to Athena's lack of support for mixed case field names. Be great to get the parquet files fixed up so all columns will work.

**Comment by rafrombrc** [comment]
Blocked on all of the parquet files being updated to lowercase all of the field names.

**Comment by rafrombrc** [comment]
This table should be removed from the available list when #75 is finished.

**Comment by madalincm** [comment]
The table is now removed. Closing the issue.
