### ISSUE TITLE
Query versions page does not contain any information

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#741]
### Steps to Reproduce:
1.  Open a query page (i,e: https://data-stmo-rc.stage.mozaws.net/queries/96)
2. Click on the options button - query versions

### Expected results:
The query versions page is open and it contains the details for all the older query versions

### Actual results:
The query versions page is blank

### Notes/Issues:
This issue can be reproduced in FF64 in STMO-rc and STMO-stage
Screencast for this issue:

![blankqueryversionspage](https://user-images.githubusercontent.com/15685441/50227526-99bcf080-03ae-11e9-8863-9b1741e570c9.gif)

**Comment by jezdez** [comment]
This was just missing the new init code pattern as added in https://github.com/getredash/redash/commit/0fe1b5f9d439c4d9b76c592ad4c17f4e4c51d86e.

This is now fixed in dd470bf5a073c5e725a917036ba475573a0d252e.

**Comment by jezdez** [comment]
I've pushed this to the release branch, so it's going out to the rc environment now.

**Comment by jezdez** [comment]
As suspected the release branch contained the fix, but the master didn't. I've updated them to contain the same changes. This should be fixed soon in stage, too. It's working in prod since we've tagged the release from the release branch that already contained the fix.
