### ISSUE TITLE
A dashboard name can be removed completely

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#76]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open a published dashboard page
3. Go to options - Edit Dashboard and delete the dashboard name
4. Save the results

### Expected results:
The dashboard name can't be empty

### Actual results:
The dashboard name can be empty 

### Notes/Issues:
Verified in FF53(Win7).  Issue can be reproduced in STMO-stage a
Screencast for this issue:
![emptydashboardname](https://cloud.githubusercontent.com/assets/15685441/25667265/accc4c0a-302b-11e7-8322-111e01bc78b5.gif)

**Comment by madalincm** [comment]
Not sure if the fix hit stage so far. I'm still able to reproduce this in stage. 
Example of new dashboard having an empty name: https://pipeline-sql.stage.mozaws.net/dashboard/testdashboard

**Comment by alison985** [comment]
After the rebase in #82, I can't reproduce this locally.

**Comment by madalincm** [comment]
I can't reproduce it in stage (verified in Win7 x64, FF54)
I can't no longer remove a dashboard name but the save button is still clickable after removing the name. After user removes the name and tries to click the save button the button should not be active or a warning message should be displayed. 
Please view this screencast: 
![savebutton](https://user-images.githubusercontent.com/15685441/27227727-4a8c9442-52ad-11e7-8847-3cb370e2f3fc.gif)

**Comment by alison985** [comment]
PR #87

**Comment by madalincm** [comment]
Verified as fixed in FF54(Win7) in stmo-stage
Postfix screencast:
![warningnamedashboard](https://user-images.githubusercontent.com/15685441/27450628-f1f0ece2-5794-11e7-8e7b-235c85d5db40.gif)
