### ISSUE TITLE
Track TypeError raised on Celery exception 

### ISSUE THREAD

**Issue by jezdez** [mozilla/redash#766]
Sentry issue: [DATA-STMO-PROD-SA](https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/5058838/)

I've filed https://github.com/getredash/redash/issues/3280 upstream to handle this.

**Comment by jezdez** [comment]
Sentry issue: [DATA-STMO-PROD-SA](https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/5058838/)

**Comment by washort** [comment]
merged upstream https://github.com/getredash/redash/pull/3499
