### ISSUE TITLE
Query results are not displayed after initial query

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#774]
### Issue Summary

When running a new query for the first time, sometimes the results do not appear in table view so you cannot see what was returned, nor can you create a visualization.

### Steps to Reproduce

1. visit sql.tmo
2. click "New Query"
3. enter a simple query, for example `SELECT active_hours_sum FROM clients_daily WHERE submission_date_s3 = '20190115' LIMIT 10`
4. click "Execute"
5. wait a few moments for the query to complete

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected the results table to appear, but it does not. You can download the results as CSV, and as a workaround, you can force the results to appear by saving the query.

Screenshot:
![screenshot_redash](https://user-images.githubusercontent.com/969479/51389812-e0b01a00-1b03-11e9-993e-bff0a1919b04.png)

### Technical details:

* Redash Version: 6.0.0 (dev)
* Browser/OS: Fx Nightly 66 on MacOS Mojave
* How did you install Redash: This is the version deployed at sql.tmo

**Comment by mreid-moz** [comment]
Hmm, I updated to the latest nightly and can no longer reproduce this issue. Yay?

**Comment by tdsmith** [comment]
I'm seeing this in 65.0b10 and @felixlawrence hit it in current nightly, so it isn't just you. Could you reopen?

**Comment by mmccorks** [comment]
I'm also seeing this in 65.0 release

**Comment by washort** [comment]
This looks like a client side issue; the data is fetched from the server properly, it's just not displayed. It's reproducible by switching data sources before making a query.

**Comment by mreid-moz** [comment]
Any idea when this fix might be rolled out?
