### ISSUE TITLE
Unable to view schemas in schema browser for BigQuery data sources

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash#785]
### Issue Summary

When viewing the 'BigQuery' data source on STMO the schema browser does not list the current tables available.  Generally there are less than 100 tables in BQ, as of right now there is about 59. There are times it has showed the table information but it has only happened 3-4 times.

The request to `https://sql.telemetry.mozilla.org/api/data_sources/49/schema` returns with HTTP 200 after about 18 seconds but the response body contains ```{"error": {"message": "Error retrieving schema.", "code": 2}}```.

This might be related https://github.com/getredash/redash/issues/2422

### Steps to Reproduce
1. Visit STMO
2. Select the BigQuery data source from the Data source drop down menu

**Comment by emtwo** [comment]
Opened up this PR upstream which resolves this issue: https://github.com/getredash/redash/pull/3382

We can also do a "hot fix" in our fork here if this is urgent.

**Comment by jezdez** [comment]
This was merged upstream and deployed.
