### ISSUE TITLE
Improve wrong domain auth message

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#79]
When a user is authenticated via Google using an account other than one that has access to sql.t.m.o, the error message is misleading ("sql.telemetry.mozilla.org is not redirecting properly", see https://bugzilla.mozilla.org/show_bug.cgi?id=1362348).

**Comment by alison985** [comment]
When I first tried to re-create this last week it kept going back to the list of google accounts without showing an error message. In the weekly meeting it was suggested to try it in a different browser. 

In firefox 53.0.3 (64-bit) today, staging give this message:
![Screenshot 2017-06-22 13.39.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b2c9f2e8b24c1300b4dd77/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416713e7b56e37a23cbb071f1132c43434d0eee1e020a17b8eb8339a3be3b798d085ded80385d75c46810feb88249b600bd26df5d99a4fedb1294b7607caddecd5d340c061a83fe593ca8984ece58f54fe04457b65e.png) and landed on this URL: https://pipeline-sql.stage.mozaws.net/oauth/google_callback?state=/&code=4/8tloZ2_by3TLqrqeIGi-9i7D4rcZehDhfIosb7FvVbY#

In a Chrome incognito window today, it first gives a too many redirects error message before finalizing landing on a 500 internal server error at https://pipeline-sql.stage.mozaws.net/oauth/google_callback?state=/&code=4/XZuM-zib6vX0QVslLECcqptyZTmh8N3bxKrbjTU5ikU#

**Comment by alison985** [comment]
You can also hit a 429 Too Many Requests page. "50 per 1 hour".

**Comment by alison985** [comment]
To be clear, to re-create this situation logout of re:Dash, logout of a mozilla google account, login to a personal or other google account, try to log into redash.

**Comment by alison985** [comment]
VictorC verified fixed via email on 7/31.
