### ISSUE TITLE
Pie chart title doesn't show

### ISSUE THREAD

**Issue by kewisch** [mozilla/redash#796]
### Issue Summary

The pie chart is incorrectly titled.

### Steps to Reproduce

1. Create a pie chart and set X and Y columns
2. Go to the series tab and set a label for the series.

Results:
* The pie chart is still titled by the name of the column

Expected:
* The pie chart should be titled using the label for the series

### Technical details:

* Redash Version: 6.0.0 (dev) / STMO

**Comment by kewisch** [comment]
![image](https://user-images.githubusercontent.com/607198/52142196-4ea62680-2658-11e9-82d3-fa7517dc8f53.png)

**Comment by washort** [comment]
https://github.com/getredash/redash/pull/3484

**Comment by jezdez** [comment]
This has been merged upstream!

**Comment by madalincm** [comment]
Verified in FF66(Win7) in STMO-RC
Issue is no longer reproducing:
![image](https://user-images.githubusercontent.com/15685441/55158905-a6e53a80-5168-11e9-9084-31be5156c923.png)
