### ISSUE TITLE
Executing a query takes a long time

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#80]
### Issue Summary:

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Window 7 64 Bit

### Steps to Reproduce:
1. Open STMO homepage - https://pipeline-sql.stage.mozaws.net/
2. Open the new query page
3. Enter a simple query like "select geo from stmo.churn limit 20" and click the Execute button

### Expected results:
The query is run, results are displayed.

### Actual results:
The query never finishes executing. 

### Notes/Issues:
Verified in FF53(Win7).  Issue can be reproduced in STMO-stage

**Comment by alison985** [comment]
I can't reproduce this on staging or production. 

On staging for the Athena(Direct) data source I tried `select distinct channel from telemetry.vtabs_daily limit 20` which took 16s.

On production for the Presto data source I tried `select geo from default.churn limit 20` which ran in 2s.

@madalincm - could you confirm this is no longer an issue?

**Comment by madalincm** [comment]
I have retested this in production and the original issue is no longer reproducing. We can close this.
