### ISSUE TITLE
Rebase on redash master

### ISSUE THREAD

**Issue by wlach** [mozilla/redash#82]
Redash master has a nice fix for a bug that causes us to see a slow script dialog when looking at a query which returns a large dataset. It would be nice to get that on our instance:

https://github.com/getredash/redash/commit/a087fe4bcd15c9a938c13f64594d8a2312c948e4

**Comment by alison985** [comment]
Submitted a path to upstream for the 5 tests related to the multi_org.html template: https://github.com/getredash/redash/pull/1826

**Comment by alison985** [comment]
PR https://github.com/mozilla/redash/pull/84
