### ISSUE TITLE
Error when querying `approx_quantile` in BigQuery

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#822]
### Issue Summary

When querying using `approx_quantile`'s direct result from BigQuery, re:dash errors out with a Python error.

### Steps to Reproduce

1. Write a query using `approx_quantile`: https://sql.telemetry.mozilla.org/queries/61517/source

I've gotten two errors in response:
- `int() argument must be a string or a number, not 'list'`
- `float() argument must be a string or a number` 

I've worked around this issue by `UNNEST`ing the resulting array and casting each element to a string.

**Comment by washort** [comment]
Sentry issue: [DATA-STMO-PROD-D4](https://sentry.prod.mozaws.net/operations/data-stmo-prod/issues/3460854/)

**Comment by washort** [comment]
PR opened upstream. https://github.com/getredash/redash/pull/3480

**Comment by jezdez** [comment]
Merged upstream!
