### ISSUE TITLE
Add an ActiveData query runner

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/redash#83]
I would like to use redash's powerful features with our ActiveData[1] instance.  It accepts SQL, via RESTful request, so is just different enough to demand it has it's own query runner.

I made a query runner [2] and now I would like guidance to get it integrated into Mozilla's redash.

[1] https://wiki.mozilla.org/Auto-tools/Projects/ActiveData
[2] https://github.com/klahnakoski/ActiveData-redash-query-runner/blob/master/active_data.py

**Comment by rafrombrc** [comment]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1364149

**Comment by alison985** [comment]
This is where I'm at: https://github.com/mozilla/redash/compare/master...alison985:83_activedata_query_runner I have no idea why it won't save the Host URL field.

**Comment by klahnakoski** [comment]
Here is the original query runner: https://github.com/klahnakoski/ActiveData-redash-query-runner/blob/master/active_data.py

The `__init__()` method is commented out in your version.  That may be the problem.

**Comment by klahnakoski** [comment]
...also this version demands a `host_url` property, but my version wanted a `url` property

**Comment by klahnakoski** [comment]
please change `properties.host_url.default` from `http://127.0.0.1:5000` to `https://activedata.allizom.org:80`

           'properties': {
               'host_url': {
                   'type': 'string',
                   'title': 'Host URL',
                   'default': 'http://127.0.0.1:5000' #,
                   #'info': 'Do not end with a trailing slash.'
               },

**Comment by alison985** [comment]
Thanks @klahnakoski. I updated future references to host_url instead of url, uncommented __init__() (which was giving me problems earlier), and changed the host_url.default, but it still won't save the host_url field input. Tagging @robhudson.

**Comment by alison985** [comment]
Being discussed here: https://discuss.redash.io/t/adding-a-new-query-runner-i-have-a-data-source-field-that-wont-save/864/3

**Comment by klahnakoski** [comment]
This is exciting!  Is there a staging instance with this query runner?

**Comment by alison985** [comment]
@klahnakoski could you please review the comments @robhudson made on this PR? https://github.com/mozilla/redash/pull/109

There is a staging instance here: https://pipeline-sql.stage.mozaws.net/ but I don't have permissions to add a datasource.

**Comment by klahnakoski** [comment]
@alison985 : may I assume you are making the required code changes?

**Comment by alison985** [comment]
@klahnakoski The changes were made. Another issue with Athena was preventing it from working on staging for a bit, but it is now up on staging https://pipeline-sql.stage.mozaws.net/queries/new. You can login with Mozilla google credentials I believe. The data source in the drop-down is called, aptly, ActiveData. If you find any issues, please open new github issues.

**Comment by klahnakoski** [comment]
@alison985  who do I talk to about getting this pushed to production?
