### ISSUE TITLE
Support preview of "how much data will be read when I run this query" for BigQuery data sources

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#833]
The BigQuery console shows you how much data your query will read before you execute it. This is pretty helpful in determining whether to further filter, how often to schedule, etc. It would be great to include this information in re:dash too, if possible.

**Comment by mreid-moz** [comment]
Here's an example of how this looks in practice:

<img width="786" alt="screen shot 2019-02-21 at 4 44 58 pm" src="https://user-images.githubusercontent.com/969479/53200503-13b06680-35f8-11e9-8909-4dba6f5b3f6f.png">

**Comment by jezdez** [comment]
I'm just going to state here that this isn't something we should implement in our fork to make sure this is tested properly and works as expected. I'd feel better if we'd create a ticket upstream because of that.

**Comment by washort** [comment]
In terms of API this is very straightforward, just specifying a `dryRun` parameter when submitting a query. I'm not sure what the UX should look like, since we don't have any other run-as-you-type features right now.

**Comment by washort** [comment]
I've implemented this as an extension in redash-stmo. https://github.com/mozilla/redash-stmo/pull/27
