### ISSUE TITLE
Re:Dash Alerts Can't Be Edited Once Created (and It's Impossible to Add Recipients)

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#88]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1315825:

I created this Alert:
https://sql.telemetry.mozilla.org/alerts/5

I experienced the following problems:
- Did not allow me to define recipients of alert before saving (defaulted to just me)
- Unable to edit the alert after saving (cannot select any field)
- It does not seem to have saved my "Rearm" in seconds

Since I can't edit, I can't add teammates to the alert and I can't try to re-add the "Rearm".

Other suggestions: 
- allow to test alert to make sure it is properly setup.
- allow to define recipients before hitting save
- put some instructions in the page to give additional guidance (or link to a page with details)

**Comment by alison985** [comment]
In staging you can add and remove recipients from an alert.

In staging you can edit the alert by making a change and clicking "Save" again.

Rearm seconds issue was addressed in issue #71 and PR #90.

Does that address this ticket in full @rafrombrc?

**Comment by rafrombrc** [comment]
I think it does. I'd say let's go ahead and let this ride the deploy process, once it's in production we can comment on the bugzilla bug and get the original reporter to verify that their issues are resolved.

**Comment by rafrombrc** [comment]
I've made a comment with a 'needinfo' request on the bugzilla bug, hopefully we'll get confirmation that the issues are resolved soon.

**Comment by davismtl** [comment]
So, I've been testing and got alerted.

Question: if I have multiple series in a chart (segmented by OS for example) for a given chart, to which data point will the threshold apply? Can we pick one specific one? Will it take the average of all of them?
