### ISSUE TITLE
Expose data source version info in UI

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#89]
We've done work to get the data source type showing up in the UI, but sometimes the features supported vary from version to version (see https://bugzilla.mozilla.org/show_bug.cgi?id=1369085). We should investigate whether it's possible for us to expose add'l info about the data source so folks know what they're dealing with.

**Comment by rafrombrc** [comment]
Let's experiment w running a query to obtain the data source version when we load the table set and displaying it in the UI, hopefully it won't slow things down too much.

**Comment by alison985** [comment]
PR #94

**Comment by alison985** [comment]
PR updated but still doesn't change when datasource changes.

**Comment by alison985** [comment]
PR updated.
