### ISSUE TITLE
Error running query: failed communicating with server.

### ISSUE THREAD

**Issue by wagnerand** [mozilla/redash#910]
### Issue Summary

I'm trying to update some dashboards, and for some of the queries on that dashboard, I get `Error running query: failed communicating with server. Please check your Internet connection and try again.`
Sometimes, the error does not show, but the data doesn't seem to update either.

### Steps to Reproduce

1. Just click on "Refresh" on a dashboard page a bunch of times.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

No error, up to date results.

### Technical details:

* Redash Version: sql.t.m.o
* Browser/OS:
* How did you install Redash:

**Comment by jezdez** [comment]
Not sure what caused this, since I can't find errors in Sentry on Feb 26.

@wagnerand 
1) Can you still reproduce this?
2) Which dashboards were the ones with the errors?

**Comment by wagnerand** [comment]
I believe this has been fixed in the meantime.
