### ISSUE TITLE
BigQuery Schemas are not showing

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#916]
At https://sql.telemetry.mozilla.org/queries/new, the schemas have stopped showing. I get an error that a schema refresh has failed.

**Comment by emtwo** [comment]
Closing this as it's probably a dupe of https://github.com/mozilla/redash/issues/785 which will be available with the next merge. @fbertsch feel free to re-open if you think it's a different issue.

**Comment by fbertsch** [comment]
I think you're right. I was mistaken because the schemas _did_ show for a little while, but that must have just been one of those happy accidents.
