### ISSUE TITLE
Syntax auto completion is not working for Athena

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#92]
### Issue Summary

Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Window 7 64 Bit

### Steps to Reproduce
1. Open new query page: https://pipeline-sql.stage.mozaws.net/queries/new
2. Select Athena (Direct) for data source and start to write your query

### Expected results:
Suggestions to write your query are displayed.

### Actual results:
No suggestions are displayed.

### Notes/Issues:
Verified in FF54 (Win7)  Issue can be reproduced in stmo-stage
Screencast for this issue:  
![syntaxsuggestion](https://user-images.githubusercontent.com/15685441/27481399-0a33a200-5825-11e7-8b22-39e08e597370.gif)

Please observe how this is working in production when using Athena data source:
![syntaxsuggestionprod gif](https://user-images.githubusercontent.com/15685441/27481430-3a921e72-5825-11e7-88a7-d9ae0d5803e9.gif)

**Comment by rafrombrc** [comment]
Oops, closed prematurely, sorry. We may not fix this one, bc we're likely to switch to a newly released upstream direct Athena query runner instead of the custom one that we built, and this issue might not exist on the new one. Still, we don't yet know, reopening now.

**Comment by arikfr** [comment]
This functionality is not related to the query runner. Make sure you get the same schema with both types of query runner. My guess is that the one that is using "Athena Direct" is getting back more tables, and passing the 5000 tokens threshold.

It's worth upgrading to the upstream one regardless, as I've seen performance improvements with it.

**Comment by alison985** [comment]
Moving this to Done so current status (post issue #98 upstream merge can be tested. Also change to "Athena" instead of "AthenaDirect" to get upstream benefits.

**Comment by rafrombrc** [comment]
Autocomplete is still not working w Athena data source, reopened for investigation.

**Comment by washort** [comment]
@arikfr is correct, the Athena schema passes the 5000-token threshold for automatic completion. (Implemented here: https://github.com/mozilla/redash/blob/master/client/app/pages/queries/query-editor.js#L74-L84 )

We can change this threshold, but the immediate workaround is using Ctrl+Space to request completions while typing.

**Comment by rafrombrc** [comment]
Not gonna fix, this is intentional behavior.
