### ISSUE TITLE
Bold text is not displayed as bold in text boxes

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#926]
### Steps to Reproduce:
- Open this dashboard: https://data-stmo-rc.stage.mozaws.net/dashboard/boldtext
- Observe the text

### Expected results:
The text marked as bold using the markdopwn syntax **text** is displayed as bold

### Actual results:
The text is displayed as normal text

### Notes/Issues:
Verified in FF66(Win7).  Issue can be reproduced in STMO-RC
Please view this screenshot: 
![image](https://user-images.githubusercontent.com/15685441/55158508-ca5bb580-5167-11e9-869c-010bffd841cd.png)

**Comment by madalincm** [comment]
It is not a regression as this can be seen in production too, and it is not reproducing on chrome.. makes me think it is an firefox issue.

**Comment by jezdez** [comment]
This is working for me, not sure if this was a fix from upstream or if this is a local issue on your system regarding fonts? @madalincm Could you check please?

<img width="593" alt="Screen-Shot-2019-08-02-12-23-12 84" src="https://user-images.githubusercontent.com/1610/62363856-67689980-b520-11e9-8935-9dd50cde33cb.png">

**Comment by madalincm** [comment]
Not reproducing anymore. Tried on Win7x64 and MacOS 10.14.1 FF68 on dev stage and prod.
