### ISSUE TITLE
Can't execute queries on Athena in RC

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#938]
### Steps to Reproduce
1. Execute this query: https://data-stmo-rc.stage.mozaws.net/queries/129/source

### Expected results:
The query can be executed

### Actual results:
Error message displayed: 
Error running query: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 5B11DF4645EDCBE0; S3 Extended Request ID: FYsQ3WwLKojymDrJr92cbBnNvJG5C1DKhnXlm4x68o2+lCR4aGVuYFKike5ioB7jFqePpg6nRK0=)

### Notes/Issue
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC and STMO-prod
Please view this screenshot: 
![image](https://user-images.githubusercontent.com/15685441/55957609-6ceb5c80-5c6f-11e9-99a7-26d5acf0517d.png)

**Comment by jasonthomas** [comment]
This is related to my S3 permission lock down and should be resolved. I've updated the query also to use churn data instead since the containers_testpilottest is not working.
