### ISSUE TITLE
Data source schema not displayed for some data sources

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#940]
### Steps to Reproduce
1. Open new query page and select Athena as the data source

### Expected results:
The schema is displayed

### Actual results:
Schema not displayed
The GET request to get the schema fails with a 502 error

### Notes/Issue
The issue can be also reproduced when using the sczops_monitoring_reports data source
Verified in FF66 win7x64 Issue can be reproduced in GCP envinronment (https://prod.stmo.prod.dataops.mozgcp.net/queries/new)
Please view this screencast: 
![image](https://user-images.githubusercontent.com/15685441/56033649-a6829d00-5d2d-11e9-93d6-cab61126747f.png)

**Comment by madalincm** [comment]
Issue no longer reproducing. Marking as verified fixed.

**Comment by jezdez** [comment]
Closing as this is fixed.
