### ISSUE TITLE
redash UI is slow after using the schema browser

### ISSUE THREAD

**Issue by badboy** [mozilla/redash#941]
### Issue Summary

Using the schema browser in any capacity makes the site UI really slow.

### Steps to Reproduce

1. Create a new query, select a data source, e.g. Athena or Presto
2. Search for a schema, e.g. main_summary
3. Wait for it to show
4. Start typing a query or scrolling through the schema list

Now everything is really slow, typing the query has a significant delay.

### Technical details:

* Redash Version: stmo as currently deployed.
* Browser/OS: Firefox 68 nightly.
* How did you install Redash: stmo

**Comment by emtwo** [comment]
This is still an issue in our latest release

**Comment by jezdez** [comment]
This is kind of mind-boggling, since the autocomplete that I would have expected to trigger this isn't enabled for the data sources where this shows up.

So my gut says this may be happening in the versioned table button code.

**Comment by jezdez** [comment]
This should be fixed now that we're using React for rendering the schema browser items. Soon to be in production.
