### ISSUE TITLE
Column autocomplete suggestions only show 'Column' and not its name

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/redash#947]
### Issue Summary

Column autocomplete suggestions only show 'Column' and not its name

### Steps to Reproduce

Tested with data sources 'Active Data' and 'Treeherder'
1. Create a new query.
2. Set data source to 'Treeherder'.
3. Type in the name of a table as shown in the left column and add a ".", e.g. "job."
Actual result: Autosuggestions shown but rows have empty areas where the column name should be shown: "<many whitespaces> Column". The issue can be observed for some time now. Regression from https://bugzilla.mozilla.org/show_bug.cgi?id=1529388 ?

### Technical details:

* Redash Version: Version: 7.0.0+b5331-m20.4 (1b8ba7c6) 
* Browser/OS: Firefox Nightly 68.0a1 20190503041749
* How did you install Redash: provided by Mozilla

**Comment by washort** [comment]
Autocomplete is populated from the schema, and the editor code hasn't been updated to match the new schema format @emtwo developed.

**Comment by emtwo** [comment]
@washort lol we both made the same commit
