### ISSUE TITLE
The versioned tables toggle button not displayed for some data sources

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#956]
### Steps to reproduce:
1. Open the new query page: https://data-stmo-rc.stage.mozaws.net/queries/new
2. Select the Presto data source

### Expected results:
The toggle button for versioned tables is displayed

### Actual results:
Toggle button not displayed

### Notes
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC
The issue is reproducing for the following data sources:
- Athena Prod
- Presto
- Query Results

**Comment by madalincm** [comment]
There are still some data sources that do not have the toggle button. For example Athena Prod. Is this an issue?

**Comment by emtwo** [comment]
The admin setting for the toggle was not on for Athena Prod. I've just turned it on and confirmed the toggle is showing up.

**Comment by jezdez** [comment]
Worksforme.

**Comment by madalincm** [comment]
Not reproducing anymore. Tried on Win7x64 and MacOS 10.14.1 FF68 on dev stage and prod.
