### ISSUE TITLE
Footer links are not displayed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#957]
### Steps to reproduce:
1. Open the homepage: https://data-stmo-rc.stage.mozaws.net/

### Expected results:
3 links are displayed in the page footer: Redash • Documentation • Contribute

### Actual results:
The links are not displayed

### Notes
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC
The issue is reproducing on all the pages.

**Comment by washort** [comment]
The footer was removed upstream in https://github.com/getredash/redash/commit/e9711a0b9c7ffa48adfd9e9150b4cb255a1f07f0 .
