### ISSUE TITLE
AttributeError in models.py

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#96]
This appears in the terminal interface though doesn't appear to be impinging on running: 

server_1    | [2017-06-26 07:03:47,023][PID:2067][ERROR][root] Error with DataSource#to_dict (data source id: 7)
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/data_sources.py", line 72, in get
server_1    |     d = ds.to_dict()
server_1    |   File "/app/redash/models.py", line 477, in to_dict
server_1    |     'syntax': self.query_runner.syntax,
server_1    | AttributeError: 'NoneType' object has no attribute 'syntax'
server_1    | [2017-06-26 07:03:47,050][PID:2067][ERROR][root] Error with DataSource#to_dict (data source id: 8)
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/data_sources.py", line 72, in get
server_1    |     d = ds.to_dict()
server_1    |   File "/app/redash/models.py", line 477, in to_dict
server_1    |     'syntax': self.query_runner.syntax,
server_1    | AttributeError: 'NoneType' object has no attribute 'syntax'
server_1    | [2017-06-26 07:03:47,054][PID:2067][ERROR][root] Error with DataSource#to_dict (data source id: 9)
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/data_sources.py", line 72, in get
server_1    |     d = ds.to_dict()
server_1    |   File "/app/redash/models.py", line 477, in to_dict
server_1    |     'syntax': self.query_runner.syntax,
server_1    | AttributeError: 'NoneType' object has no attribute 'syntax'
server_1    | [2017-06-26 07:03:47,056][PID:2067][ERROR][root] Error with DataSource#to_dict (data source id: 11)
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/data_sources.py", line 72, in get
server_1    |     d = ds.to_dict()
server_1    |   File "/app/redash/models.py", line 477, in to_dict
server_1    |     'syntax': self.query_runner.syntax,
server_1    | AttributeError: 'NoneType' object has no attribute 'syntax'

**Comment by arikfr** [comment]
You have some data source (query runner) type in use, which is not enabled in the current setup.

**Comment by alison985** [comment]
Agreed this goes away once code for #93 is available.

**Comment by alison985** [comment]
Madalin, there is no way for you to have seen this as it was output to the console. I'm confirming it's verified fixed.
