### ISSUE TITLE
Reverting a query to a previous version is not taking place until the page is refreshed

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#960]
### Steps to reproduce:
1. Open a query that has more than 1 version
2. Go to Options menu - Query versions
3. Select an older version and click the Revert to version x button

### Expected results:
The query is reverted to the selected version

### Actual results:
The older version of the query is not displayed. If the user refreshes the page the correct version is displayed.

### Notes
Verified in FF66 win7x64 Issue can be reproduced in STMO-RC and STMO-prod
Please view this screencast: 
![queryVersioning](https://user-images.githubusercontent.com/15685441/58188816-f73ccc80-7cc1-11e9-9ae3-1980a1c2507d.gif)

**Comment by emtwo** [comment]
I was able to reproduce this bug in r-c but it seems to also exist in release. I don't think we should block this release on it.

**Comment by jezdez** [comment]
The query versions feature has been deprecated.
