### ISSUE TITLE
Consider adding a banner that gives information about missing data

### ISSUE THREAD

**Issue by fbertsch** [mozilla/redash#961]
We have now deleted a substantial amount of data, and queries may look strange for awhile. Since re:dash doesn't support annotations, we should consider a small banner at the top that indicates the dates of the outage, and points to the bug with details about deletion. Bonus points for pointing to a list of affected datasets directly.

**Comment by jezdez** [comment]
@fbertsch Is this still relevant?

**Comment by fbertsch** [comment]
Nope, I would say it's not any longer, it's been long enough and most queries aren't hitting that data anymore.
