### ISSUE TITLE
Consider creating a "redash-users" mailing list that's synchronized with redash metadata

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/redash#963]
### Issue Summary

It would be nice to send a communication to recent redash users - feature announcements, new data sources, outages, etc.

### Steps to Reproduce

1. Have something to say to people who use redash
2. ...?

**Comment by jezdez** [comment]
Great idea! Alternatively, a Slack channel?

**Comment by rafrombrc** [comment]
I've created an "stmo-authors" [google group](https://groups.google.com/a/mozilla.com/forum/#!forum/stmo-authors), populated using a [query](https://sql.telemetry.mozilla.org/queries/63268) showing all folks who have performed an authoring function within the last 6 months. A bit more work will be required to figure out how to keep it in sync w stmo usage, but I'm calling this one done.
