### ISSUE TITLE
Show user's unpublished queries in dashboard 'Add Widget' search

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#97]
When a user is adding widgets to a dashboard, only published queries show up in the "Search a query by name" text box. Ideally unpublished queries owned by the current user would also be available for use here.

**Comment by rafrombrc** [comment]
Also we have the same problem w setting up alerts... only published queries show up, but we'd like users to be able to set up alerts on their own unpublished queries.

**Comment by arikfr** [comment]
Actually it's like this on purpose:
1. It gives incentive to users to publish their queries instead of keeping to themselves.
2. It avoids the confusion of why someone can use a certain query while others can't.

**Comment by alison985** [comment]
Based on @arikfr's comment I only added unpublished queries to the alerts search, NOT the dashboard add widget search. PR #101

**Comment by madalincm** [comment]
Unpublished queries are showing up only in alerts search but not on dashboards. Marking bug as verified fixed.
