### ISSUE TITLE
String labels are not visible in widget dashboard view

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/redash#974]
### Issue Summary
After adding a graph as a widget to a Dashboard, the labels are not visible and there's no apparent way to make them visible, which renders the graph not very useful.
![Screenshot_2019-07-17 Athena Presto to BigQuery Migration](https://user-images.githubusercontent.com/953153/61403739-94b81500-a89b-11e9-8870-8d3a87cb57b1.png)
Link to live example: https://sql.telemetry.mozilla.org/dashboard/athena-presto-to-bigquery-migration

### Steps to Reproduce

1. Add a graph with string labels on the X axis to a dashboard

### Technical details:

* Redash Version:
* Browser/OS: Firefox Nightly
* How did you install Redash:

**Comment by jezdez** [comment]
The labels show up for me for the provided link, so I think the recent merge has fixed this. Please reopen if that's not the case!
