### ISSUE TITLE
Issue when running queries on Presto data source

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash#976]
### Steps to reproduce:
1. Execute this query:  https://stage.stmo.nonprod.dataops.mozgcp.net/queries/125/source#162

### Expected results:
The query is executed

### Actual results:
The following error is displayed:
Error running query: HTTPConnectionPool(host='data-presto.data.mozaws.net', port=8080): Max retries exceeded with url: /v1/statement (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faddbc14250>: Failed to establish a new connection: [Errno 110] Connection timed out',))

### Notes
Verified in FF68(Win7) Issue can be reproduced in https://stage.stmo.nonprod.dataops.mozgcp.net/queries/new

The issue can be also reproduced when running a trivial query. i.e : select addon_id from default.addons limit 10

**Comment by jasonthomas** [comment]
I allowed ingress from stmo-nonprod cloud nat instance to presto's AWS ELB and this now works.

**Comment by rafrombrc** [comment]
This was due to access to Presto not being allowed from GCP dev and staging environments. Jason turned this on, it's working now.

**Comment by madalincm** [comment]
Verified using the same query on stage on Win7x64 FF68. There were no issues this time. Marking bug as verified fixed.
