### ISSUE TITLE
Use upstream Athena query runner

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/redash#98]
There is an upstream PR (https://github.com/getredash/redash/pull/1809) that uses a standardized Athena query runner instead of the custom one that we built. We should pull this into our repo and use that instead of our custom one, first on stage and eventually on production.

**Comment by alison985** [comment]
@madalincm For this one can you please test the 'dashboard can have no name' issue again? Thanks.

**Comment by alison985** [comment]
Need to undo the revert.
