### ISSUE TITLE
" Operation timed out after 6.0 hours" even though query was only running for a few minutes

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/redash#991]
I was running this query:
https://sql.telemetry.mozilla.org/queries/65865/source

And got this error message after a few minutes:
"Error running query: Operation timed out after 6.0 hours. Consider reducing the amount of work performed by your operation so that it can complete within this limit."

The query took 9 minutes in the bigquery console.

**Comment by jezdez** [comment]
This was found to be a BQ-side issue on Slack. @sunahsuh Right?

**Comment by sunahsuh** [comment]
Yeah, sounds like it. I'll close this here since we're chatting with Google support about it there
